import {useEffect,useState} from 'react';
import {api} from './client';
import {useAuth} from './Auth';
import {CourseCover} from './CourseCover';
import {Link,navigate} from './router';
import type {Course,Enrollment,Language,Progress,Session,Subject} from './types';
import {formatTimestamp} from './time';

type Props={language:Language;t:(key:string)=>string};
export function CourseCard({course,t,progress=0}:{course:Course;t:(key:string)=>string;progress?:number}){
  return <article className="course-card" data-course-id={course.id}><Link to={'/courses/'+course.id}><CourseCover subject={course.subject_id}/></Link><div className="course-card-body"><div className="section-title"><span className={'availability '+(course.available?'available':'planned')}>{t(course.available?'availableNow':'comingSoon')}</span><span className="muted">{course.available?t('practicalCourse'):t('plannedSyllabus')}</span></div><h3><Link to={'/courses/'+course.id}>{course.title}</Link></h3><p>{course.summary}</p>{course.available?<><div className="course-metadata"><span>{course.lesson_count} {t('guidedLabs')}</span><span>{course.minutes} {t('minutesShort')}</span></div>{progress>0&&<div className="course-progress"><progress value={progress} max={course.lesson_count}/><small>{progress}/{course.lesson_count} {t('completedLessons')}</small></div>}</>:<p className="muted">{t('courseAvailability')}</p>}<Link to={'/courses/'+course.id} className="course-card-link">{t(course.available?'viewCourse':'viewPlan')} →</Link></div></article>;
}

export function CourseLibrary({language,t,subjectId}:{subjectId?:string}&Props){
  const [courses,setCourses]=useState<Course[]>([]),[subjects,setSubjects]=useState<Subject[]>([]),[query,setQuery]=useState(new URLSearchParams(window.location.search).get('q')??''),[error,setError]=useState('');
  useEffect(()=>{let live=true;Promise.all([api<Course[]>('/courses?language='+language),api<Subject[]>('/subjects?language='+language)]).then(([c,s])=>{if(live){setCourses(c);setSubjects(s);setError('');}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[language]);
  const subject=subjects.find(item=>item.id===subjectId),featured=courses.find(item=>item.available);
  const visible=courses.filter(item=>(!subjectId||item.subject_id===subjectId)&&(item.title+' '+item.summary).toLocaleLowerCase().includes(query.toLocaleLowerCase().trim()));
  if(subjectId&&subjects.length&&!subject)return <NotFound t={t}/>;
  return <>{error&&<p className="notice error" role="alert">{t(error)}</p>}{subject?<section className="subject-heading"><p className="course-kicker">{t(subject.family)}</p><h1>{subject.title}</h1><p>{subject.summary}</p>{!subject.available&&<p className="planned-note">{t('plannedHelp')}</p>}<Link className="text-button" to="/">← {t('browseAll')}</Link></section>:<><section className="catalog-hero"><div><span className="course-kicker">{t('coursePlatform')}</span><h1>{t('browseHeadline').split('\n').map((line,i)=><span key={i}>{line}<br/></span>)}</h1><p>{t('browseIntro')}</p><Link className="primary" to="/courses/sql-data-qa">{t('browseCourses')} →</Link><div className="hero-proof"><span>✓ {t('realSQL')}</span><span>✓ ENG / VIE</span><span>✓ {t('handsOn')}</span></div></div><div className="featured-course">{featured&&<><span className="course-kicker">{t('featured')}</span><CourseCard course={featured} t={t}/></>}</div></section><section className="subject-section"><div className="section-title"><h2>{t('subjectAreas')}</h2><span>{t('subjectIntro')}</span></div><div className="subject-grid">{subjects.map(s=><Link key={s.id} to={'/subjects/'+s.id} className={'subject-tile subject-'+s.id}><span className="subject-symbol">{s.id==='sql'?'⌘':s.id==='api'?'{}':'◇'}</span><strong>{s.title}</strong><small>{t(s.available?'availableNow':'comingSoon')}</small></Link>)}</div></section></>}
  <section className="course-library"><div className="section-title"><div><p className="course-kicker">{t('handsOn')}</p><h2>{t('courseLibrary')}</h2></div><label className="course-search"><span aria-hidden="true">⌕</span><input type="search" aria-label={t('searchCourses')} placeholder={t('searchPlaceholder')} value={query} onChange={e=>setQuery(e.target.value)}/></label></div>{!subjectId&&<div className="subject-links"><Link to="/">{t('allSubjects')}</Link>{subjects.map(s=><Link key={s.id} to={'/subjects/'+s.id}>{s.title}</Link>)}</div>}<div className="course-grid">{visible.map(c=><CourseCard key={c.id} course={c} t={t}/>)}</div>{!visible.length&&courses.length>0&&<p className="empty">{t('noCourses')} <button className="text-button" onClick={()=>setQuery('')}>{t('clearSearch')}</button></p>}</section></>;
}

export function CoursePage({id,language,t}:{id:string}&Props){
  const auth=useAuth();const [course,setCourse]=useState<Course|null>(null),[stats,setStats]=useState<Progress[]>([]),[sessions,setSessions]=useState<Session[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[track,setTrack]=useState('ALL'),[difficulty,setDifficulty]=useState('ALL'),[search,setSearch]=useState('');
  useEffect(()=>{let live=true;setCourse(null);setError('');api<Course>('/courses/'+id+'?language='+language).then(c=>{if(live)setCourse(c);}).catch(e=>{if(live)setError(e.message);});if(auth.user)Promise.all([api<Progress[]>('/progress'),api<Session[]>('/sessions?language='+language)]).then(([p,s])=>{if(live){setStats(p);setSessions(s);}}).catch(e=>{if(live&&e.message!=='STALE_REQUEST')setError(e.message);});else{setStats([]);setSessions([]);}return()=>{live=false;};},[id,language,auth.user?.user_id]);
  if(error==='NOT_FOUND')return <NotFound t={t}/>;
  if(!course)return <p className="working">{t(error||'loading')}</p>;
  const labs=course.chapters?.flatMap(c=>c.lessons)??[],done=stats.filter(s=>s.completed&&labs.some(l=>l.id===s.lab_id)).length;
  const visible=(lab:typeof labs[number])=>(track==='ALL'||lab.track===track)&&(difficulty==='ALL'||lab.level===difficulty)&&(lab.title+' '+lab.summary).toLocaleLowerCase().includes(search.toLocaleLowerCase().trim());
  const next=labs.find(l=>!stats.some(s=>s.lab_id===l.id&&s.completed))??labs[0];
  const start=()=>{if(!next)return;const to=`/courses/${id}/lessons/${next.id}`;navigate(auth.user?to:'/signup?next='+encodeURIComponent(to));};
  return <>{error&&<p className="notice error" role="alert">{t(error)}</p>}<section className="course-detail-hero"><div><p className="course-kicker">{t(course.available?'practicalCourse':'comingSoon')}</p><h1>{course.title}</h1><p>{course.summary}</p><div className="course-metadata"><span>ENG / VIE</span>{course.available&&<><span>{course.lesson_count} {t('guidedLabs')}</span><span>{course.chapters?.length} {t('chapters')}</span><span>{course.minutes} {t('minutesShort')}</span></>}</div>{course.available?<div className="button-row"><button className="primary" disabled={auth.loading||busy} onClick={start}>{t(done?'continueCourse':'beginCourse')} →</button>{auth.user&&<button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);setNotice('');try{await api('/courses/'+id+'/enroll',{});setNotice('courseAdded');}catch(e){setError(e instanceof Error?e.message:'network');}finally{setBusy(false);}}}>{t('enrollCourse')}</button>}</div>:<p className="planned-note">{t('courseAvailability')}</p>}{notice&&<p className="notice pass" role="status">{t(notice)}</p>}{auth.user&&course.available&&<div className="course-progress"><progress value={done} max={course.lesson_count}/><small>{done}/{course.lesson_count} {t('completedLessons')}</small></div>}</div><CourseCover subject={course.subject_id} large/></section>
  <section className="course-overview-grid"><div className="panel"><h2>{t(course.available?'outcomes':'plannedSyllabus')}</h2><ul className="check-list">{course.objectives.map(o=><li key={o}>✓ {o}</li>)}</ul></div>{course.prerequisites.length>0&&<div className="panel"><h2>{t('prerequisites')}</h2><ul>{course.prerequisites.map(o=><li key={o}>{o}</li>)}</ul></div>}</section>
  {course.available&&<section className="curriculum"><div className="section-title"><h2>{t('curriculum')}</h2><span>{course.lesson_count} {t('lessons')}</span></div><div className="curriculum-filters"><label>{t('lessonSearch')}<input type="search" aria-label={t('lessonSearch')} value={search} onChange={e=>setSearch(e.target.value)}/></label><label>{t('topic')}<select aria-label={t('topic')} value={track} onChange={e=>setTrack(e.target.value)}>{['ALL','FOUNDATION','SQL_ADVANCED','INCREMENTAL','FRESHNESS','SCD'].map(v=><option key={v} value={v}>{t(v)}</option>)}</select></label><label>{t('difficulty')}<select aria-label={t('difficulty')} value={difficulty} onChange={e=>setDifficulty(e.target.value)}>{['ALL',...new Set(labs.map(l=>l.level))].map(v=><option key={v} value={v}>{t(v)}</option>)}</select></label></div>{!labs.some(visible)&&<p className="empty">{t('noLessons')}</p>}{course.chapters?.filter(ch=>ch.lessons.some(visible)).map((chapter,i)=><section className="chapter" key={chapter.id}><div className="chapter-heading"><span>{String(i+1).padStart(2,'0')}</span><h3>{chapter.title}</h3><small>{chapter.minutes} {t('minutesShort')}</small></div><div className="chapter-lessons">{chapter.lessons.filter(visible).map(lab=>{const completed=stats.some(s=>s.lab_id===lab.id&&s.completed),ongoing=sessions.find(s=>s.lab_id===lab.id&&s.status==='ACTIVE');return <article className="lesson-card" key={lab.id} data-lab-id={lab.id}><span className={'lesson-number '+(completed?'done':'')}>{completed?'✓':String(lab.order).padStart(2,'0')}</span><div><h3>{lab.title}</h3><p>{lab.summary}</p></div><span className="muted">{lab.minutes} {t('minutesShort')}</span><button className="text-button" disabled={auth.loading} onClick={()=>{const to=`/courses/${id}/lessons/${lab.id}`+(ongoing?'?session='+ongoing.session_id:'');navigate(auth.user?to:'/signup?next='+encodeURIComponent(to));}}>{t(completed?'reviewLesson':ongoing?'continue':'openLesson')} →</button></article>;})}</div></section>)}</section>}</>;
}

export function MyLearning({language,t,history=false}:{history?:boolean}&Props){
  const auth=useAuth(),[courses,setCourses]=useState<Course[]>([]),[enrollments,setEnrollments]=useState<Enrollment[]>([]),[sessions,setSessions]=useState<Session[]>([]),[stats,setStats]=useState<Progress[]>([]),[error,setError]=useState(''),[more,setMore]=useState(false),[busy,setBusy]=useState(false);
  useEffect(()=>{let live=true;Promise.all([api<Course[]>('/courses?language='+language),api<Enrollment[]>('/enrollments'),api<Session[]>('/sessions?language='+language),api<Progress[]>('/progress')]).then(([c,e,s,p])=>{if(live){setCourses(c);setEnrollments(e);setSessions(s);setStats(p);setMore(s.length===50);setError('');}}).catch(e=>{if(live&&e.message!=='STALE_REQUEST')setError(e.message);});return()=>{live=false;};},[language,auth.user?.user_id]);
  return <><section className="learning-heading"><p className="course-kicker">{t('yourLearning')}</p><h1>{t(history?'history':'myLearning')}</h1><p>{history?t('historyHelp'):auth.user?.display_name}</p></section>{error&&<p className="notice error" role="alert">{t(error)}</p>}{!history&&<><div className="course-grid">{enrollments.map(e=>courses.find(c=>c.id===e.course_id)).filter((c):c is Course=>!!c).map(c=><CourseCard key={c.id} course={c} t={t} progress={stats.filter(p=>p.completed).length}/>)}</div>{enrollments.length===0&&!error&&<section className="panel learning-empty"><h2>{t('noEnrollments')}</h2><p>{t('noEnrollmentsHelp')}</p><Link className="primary" to="/courses/sql-data-qa">{t('browseCourses')}</Link></section>}</>}
  <section className="panel learning-history"><div className="section-title"><h2>{t(history?'history':'recentAttempts')}</h2>{!history&&<Link className="text-button" to="/history">{t('viewHistory')} →</Link>}</div>{(history?sessions:sessions.slice(0,5)).map(s=><div className="session-row" key={s.session_id}><div><strong>{s.title??s.lab_id}</strong><p className="muted">{formatTimestamp(s.started_at,language)} · {s.mode}</p></div><span className={'badge '+s.status.toLowerCase()}>{t(s.status)}</span><Link className="secondary" to={`/courses/sql-data-qa/lessons/${s.lab_id}?session=${s.session_id}`}>{t('view')}</Link></div>)}{!sessions.length&&<p className="empty">{t('empty')}</p>}{history&&more&&<button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{const older=await api<Session[]>('/sessions?language='+language+'&offset='+sessions.length);setSessions([...sessions,...older]);setMore(older.length===50);}catch(e){setError(e instanceof Error?e.message:'network');}finally{setBusy(false);}}}>{t('more')}</button>}</section></>;
}
export function NotFound({t}:{t:(key:string)=>string}){return <section className="panel access-prompt"><h1>{t('notFound')}</h1><p>{t('notFoundHelp')}</p><Link className="primary" to="/">{t('browseAll')}</Link></section>;}
