import {useEffect,useRef,useState} from 'react';
import {useAuth} from './Auth';
import {api,ApiError,draftKey,saved,save} from './client';
import {CloudWorkspace} from './CloudWorkspace';
import {Link,navigate} from './router';
import {SqlEditor} from './SqlEditor';
import {GuidanceText} from './GuidanceText';
import {Simulation} from './Simulation';
import {EtlControls,HttpEvidence} from './Task10Workspace';
import {formatTimestamp} from './time';
import type {Course,Language,Lesson,Progress,QueryResult,Session} from './types';

export function Badge({value,t}:{value:string;t?:(key:string)=>string}){return <span className={'badge '+value.toLowerCase()}>{t&&['ACTIVE','COMPLETED','REVEALED'].includes(value)?t(value):value}</span>;}
export function Json({value}:{value:unknown}){return <pre className="json">{JSON.stringify(value,null,2)}</pre>;}
export function Result({result,t}:{result:QueryResult|null;t:(key:string)=>string}){
  if(!result)return <p className="empty">{t('noResult')}</p>;
  return <><div className="section-title"><Badge value={result.status}/><span>{result.rows?.length??0} {t('rowsShown')}</span></div>{result.error&&<p className="notice error" role="alert">{t(result.error)}</p>}{result.truncated&&<p className="notice">{t('truncated')}</p>}{result.columns?.length>0&&<div className="table-scroll"><table><thead><tr>{result.columns.map((column,index)=><th key={index}>{column}</th>)}</tr></thead><tbody>{result.rows.map((row,index)=><tr key={index}>{row.map((cell,i)=><td key={i}>{cell===null?<span className="null">NULL</span>:cell}</td>)}</tr>)}</tbody></table></div>}</>;
}

export function LessonPlayer({courseId,labId,requestedSession,fresh,language,t}:{courseId:string;labId:string;requestedSession:string|null;fresh:boolean;language:Language;t:(key:string)=>string}){
  const user=useAuth().user!;
  const [course,setCourse]=useState<Course|null>(null),[lesson,setLesson]=useState<Lesson|null>(null),[stats,setStats]=useState<Progress[]>([]),[session,setSession]=useState<Session|null>(null);
  const [sqlText,setSql]=useState(''),[conclusion,setConclusion]=useState(''),[mode,setMode]=useState('CHALLENGE'),[scenario,setScenario]=useState('');
  const [result,setResult]=useState<QueryResult|null>(null),[verdict,setVerdict]=useState<string|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
  const sid=useRef(''),busyRef=useRef(false),epoch=useRef(0);
  const base=`/courses/${courseId}/lessons/${labId}`;
  const key=(kind:string,id=sid.current||labId)=>draftKey(user.user_id,kind,id);
  const active=session?.status==='ACTIVE';
  const http=lesson?.exercise_type==='HTTP';const eng=language==='ENG';
  function load(value:Session){const changed=sid.current!==value.session_id;sid.current=value.session_id;setSession(value);setMode(value.mode);if(changed){setSql(saved(key('sql'),value.queries.at(-1)?.sql??value.practice_sql));setConclusion(saved(key('answer')));setResult(saved(key('result'))==='clear'?null:value.queries.at(-1)?.result??null);setVerdict(value.submissions.at(-1)?.status??null);}}
  useEffect(()=>{const n=++epoch.current;setLoading(true);setError('');(async()=>{
    const c=await api<Course>('/courses/'+courseId+'?language='+language);
    const l=c.chapters?.flatMap(ch=>ch.lessons).find(l=>l.id===labId);
    if(!l)throw Error('lessonUnavailable');
    const p=await api<Progress[]>('/progress');
    let candidate=requestedSession;
    if(!candidate&&!fresh){const rows=await api<Session[]>('/sessions?lab_id='+labId+'&limit=1');candidate=rows[0]?.session_id??null;}
    const value=candidate?await api<Session>('/sessions/'+candidate+'?language='+language):null;
    if(value&&value.lab_id!==labId)throw Error('NOT_FOUND');
    if(n!==epoch.current)return;
    setCourse(c);setLesson(l);setStats(p);
    if(value)load(value);else{sid.current='';setSession(null);setSql(saved(key('sql',labId),l.practice_sql));setConclusion('');setResult(null);setVerdict(null);}
  })().catch(e=>{if(n===epoch.current&&e.message!=='STALE_REQUEST')setError(e instanceof ApiError&&e.detail?(eng?'Evidence validation: ':'Kiểm tra evidence: ')+e.detail:e.message);}).finally(()=>{if(n===epoch.current)setLoading(false);});return()=>{epoch.current++;};},[courseId,labId,requestedSession,fresh,language,user.user_id]);
  async function action(work:()=>Promise<void>){if(busyRef.current)return;busyRef.current=true;setBusy(true);setError('');try{await work();}catch(e){if(e instanceof Error&&e.message!=='STALE_REQUEST')setError(e instanceof ApiError&&e.detail?(eng?'Evidence validation: ':'Kiểm tra evidence: ')+e.detail:e.message);}finally{busyRef.current=false;setBusy(false);}}
  function changeSql(value:string){setSql(value);save(key('sql'),value);}
  async function update(){load(await api<Session>('/sessions/'+sid.current+'?language='+language));setStats(await api<Progress[]>('/progress'));}
  async function start(){if(!lesson)return;const value=await api<Session>('/sessions?language='+language,{lab_id:labId,mode,scenario:mode==='SANDBOX'&&scenario?scenario:null});load(value);setSql(lesson.practice_sql);save(key('sql'),lesson.practice_sql);setResult(null);setVerdict(null);navigate(base+'?session='+value.session_id,true);}
  function restart(){if(busy)return;sid.current='';setSession(null);setScenario('');setResult(null);setVerdict(null);setConclusion('');setSql(lesson?.practice_sql??'');navigate(base+'?new=1',true);}
  const outline=<nav aria-label={t('chapterNav')}>{course?.chapters?.map(ch=><section key={ch.id}><h3>{ch.title}</h3>{ch.lessons.map(l=><Link className={'outline-lesson '+(l.id===labId?'current':'')} aria-current={l.id===labId?'page':undefined} key={l.id} to={`/courses/${courseId}/lessons/${l.id}`}><span>{stats.some(s=>s.lab_id===l.id&&s.completed)?'✓':String(l.order).padStart(2,'0')}</span>{l.title}</Link>)}</section>)}</nav>;
  if(loading&&!lesson)return <p className="working" role="status">{t(error||'loading')}</p>;
  if(!lesson||!course)return <p className="notice error" role="alert">{t(error||'lessonUnavailable')}</p>;
  return <div className="player-grid"><aside className="course-outline"><Link className="text-button" to={'/courses/'+courseId}>← {t('backToCourse')}</Link><h2>{t('courseContents')}</h2>{outline}</aside><div className="lesson-area"><details className="mobile-outline"><summary>{t('courseContents')}</summary>{outline}</details><Link className="text-button back" to={'/courses/'+courseId}>← {t('backToCourse')}</Link><div className="lesson-heading"><div><p className="course-kicker">{t('lessonMeta')} · {lesson.minutes} {t('minutes')}</p><h1>{lesson.title}</h1><p>{lesson.summary}</p></div>{session&&<div className="attempt-controls"><Badge value={session.status} t={t}/><button className="secondary new-attempt" disabled={busy} onClick={restart}>{t('restart')}</button></div>}</div>{error&&<p className="notice error" role="alert">{t(error)}</p>}{(busy||loading)&&<p className="working" role="status">{t('loading')}</p>}
  <div className="workspace"><section className="panel instructions"><h2>{t('instruction')}</h2>{lesson.introduction&&<><h3>{eng?'Introduction':'Giới thiệu'}</h3><p>{lesson.introduction}</p><h3>{eng?'Purpose':'Mục đích'}</h3><p>{lesson.purpose}</p></>}<h3>{t('objectives')}</h3><ul>{lesson.objectives.map(o=><li key={o}>{o}</li>)}</ul><h3>{t('theory')}</h3><GuidanceText structured={courseId==='sql-data-qa'||courseId==='etl-testing'} text={lesson.theory}/><h3>{t('steps')}</h3><ol>{lesson.steps.map(s=><li key={s}>{s}</li>)}</ol><pre className="example">{lesson.practice_sql}</pre><p className="muted">{t('expected')}: {lesson.practice_expected}</p><button className="secondary" disabled={busy||!active} onClick={()=>changeSql(lesson.practice_sql)}>{t('useExample')}</button><details><summary>{t('schema')}</summary>{Object.entries(lesson.schema).map(([name,definition])=><div key={name}><h4>{name}</h4><p className="muted">{t('grain')}: {definition.grain}</p><div className="table-scroll"><table><tbody>{Object.entries(definition.columns).map(([column,type])=><tr key={column}><td>{column}</td><td>{type}</td></tr>)}</tbody></table></div></div>)}</details></section>
  <section className="work-column">{!session?<section className="panel"><div className="challenge-box"><h2>{t('challenge')}</h2><GuidanceText structured={courseId==='sql-data-qa'||courseId==='etl-testing'} text={lesson.requirement}/></div><h2>{t('start')}</h2><p>{t('modeHelp')}</p><div className="form-row"><label>{t('mode')}<select aria-label="Mode" value={mode} disabled={busy} onChange={e=>{setMode(e.target.value);setScenario('');}}><option value="CHALLENGE">CHALLENGE</option><option value="SANDBOX">SANDBOX</option></select></label>{mode==='SANDBOX'&&<label>{t('scenario')}<select aria-label="Scenario" value={scenario} disabled={busy} onChange={e=>setScenario(e.target.value)}><option value="">{t('random')}</option>{lesson.scenarios.map(s=><option key={s} value={s}>{t(s)}</option>)}</select></label>}</div><button className="primary" disabled={busy} onClick={()=>action(start)}>{t('start')} →</button></section>:<>
  {session.cloud_evidence&&<CloudWorkspace session={session} busy={busy} language={language} onAction={op=>action(async()=>{load(await api<Session>('/sessions/'+sid.current+'/simulation?language='+language,{action:op}));save(key('result'),'clear');setResult(null);setVerdict(null);})} onImport={(filename,file_format,content)=>action(async()=>{load(await api<Session>('/sessions/'+sid.current+'/evidence-import?language='+language,{filename,file_format,content}));save(key('result'),'clear');setResult(null);setVerdict(null);})}/>}
  {session.etl_simulation&&<EtlControls session={session} busy={busy} language={language} onAction={op=>action(async()=>{load(await api<Session>('/sessions/'+sid.current+'/simulation?language='+language,{action:op}));save(key('result'),'clear');setResult(null);setVerdict(null);})}/>}
  {session.simulation&&<Simulation state={session.simulation} enabled={!!active&&session.mode==='SANDBOX'} busy={busy} t={t} onAction={op=>action(async()=>{load(await api<Session>('/sessions/'+sid.current+'/simulation?language='+language,{action:op}));save(key('result'),'clear');setResult(null);setVerdict(null);})}/>}
  <section className="panel editor-panel"><div className="section-title"><h2>{http?(eng?'API request & checks (JSON)':'Request API & kiểm tra (JSON)'):t('sql')}</h2><span className="muted">{session.mode}{session.scenario_id?' · '+t(session.scenario_id):''}</span></div><SqlEditor kind={lesson.exercise_type} value={sqlText} onChange={changeSql} disabled={busy||!active}/><div className="editor-actions"><button className="primary" disabled={busy||!active||!sqlText.trim()} onClick={()=>action(async()=>{setResult(await api<QueryResult>('/sessions/'+sid.current+'/query',{sql:sqlText}));save(key('result'),'show');await update();})}>{http?(eng?'Send HTTP & test':'Gửi HTTP & kiểm tra'):t('run')} ▷</button><span className="muted">{http?'GET /orders · 10 pages · 3 attempts/page · 50–300 ms':`SELECT · 100 ${t('rowCount')} · 2s`}</span></div></section>
  <section className="panel query-result"><h2>{t('result')}</h2><Result result={result} t={t}/>{result?.http&&<HttpEvidence result={result} language={language}/>}</section>
  <section className="panel challenge-answer"><div className="challenge-box"><h2>{t('challenge')}</h2><GuidanceText structured={courseId==='sql-data-qa'||courseId==='etl-testing'} text={lesson.requirement}/></div><p className="muted">{http?(eng?'Submit your JSON test plan against independent clean and defective HTTP cases. Your written answer is saved; it is not automatically graded.':'Nộp kế hoạch JSON để chấm trên case HTTP sạch và lỗi độc lập. Câu trả lời được lưu, không được chấm tự động.'):t('submissionHelp')}</p><label className="field-label" htmlFor="conclusion">{t('conclusion')}</label><textarea id="conclusion" maxLength={4096} value={conclusion} disabled={busy||!active} placeholder={t('conclusionHelp')} onChange={e=>{setConclusion(e.target.value);save(key('answer'),e.target.value);}}/><div className="button-row"><button className="primary" disabled={busy||!active||!conclusion.trim()||!sqlText.trim()} onClick={()=>action(async()=>{const value=await api<{status:string}>('/sessions/'+sid.current+'/submit?language='+language,{sql:sqlText,conclusion});setVerdict(value.status);await update();})}>{http?(eng?'Submit API test':'Nộp kiểm tra API'):t('submit')}</button><button className="secondary" disabled={busy||!active||session.hints_used>=3} onClick={()=>action(async()=>{await api('/sessions/'+sid.current+'/hint?language='+language,{});await update();})}>{t('hint')} ({session.hints_used}/3)</button><button className="text-button" disabled={busy||!active} onClick={()=>{if(window.confirm(t('revealConfirm')))action(async()=>{load(await api<Session>('/sessions/'+sid.current+'/reveal?language='+language,{}));});}}>{t('reveal')}</button></div>{verdict&&<div className={'notice '+verdict.toLowerCase()} role="status"><Badge value={verdict}/><p>{t(verdict)}</p></div>}{session.hints.length>0&&<><h3>{t('hints')}</h3><ol>{session.hints.map(h=><li key={h}>{h}</li>)}</ol></>}{session.solution_sql&&<div className="solution"><h3>{t('solution')}</h3><pre>{session.solution_sql}</pre>{session.explanation&&<GuidanceText structured={courseId==='sql-data-qa'||courseId==='etl-testing'} text={session.explanation}/>}<button className="secondary" disabled={busy} onClick={restart}>{t('restart')}</button></div>}</section>
  <details className="panel"><summary>{t('queryHistory')} ({session.query_count}) / {t('submissionHistory')} ({session.submission_count})</summary>{session.queries.map(q=><details key={q.query_id}><summary>{formatTimestamp(q.executed_at,language)} · {q.result.status}</summary><pre>{q.sql}</pre><Result result={q.result} t={t}/></details>)}{session.query_count>session.queries.length&&<button className="secondary" disabled={busy} onClick={()=>action(async()=>{const older=await api<Session['queries']>('/sessions/'+sid.current+'/history/queries?offset='+session.queries.length);setSession({...session,queries:[...older,...session.queries]});})}>{t('more')} · {t('queryHistory')}</button>}{session.submissions.map(s=><div className="history-item" key={s.submission_id}><Badge value={s.status}/><span>{formatTimestamp(s.submitted_at,language)}</span><pre>{s.sql}</pre><p>{s.conclusion}</p></div>)}{session.submission_count>session.submissions.length&&<button className="secondary" disabled={busy} onClick={()=>action(async()=>{const older=await api<Session['submissions']>('/sessions/'+sid.current+'/history/submissions?offset='+session.submissions.length);setSession({...session,submissions:[...older,...session.submissions]});})}>{t('more')} · {t('submissionHistory')}</button>}</details>
  </>}</section></div></div></div>;
}
