import {useEffect,useRef,useState} from 'react';
import {api} from './client';
import {useAuth} from './Auth';
import {Badge,Json} from './LessonPlayer';
import {PipelineGuide} from './PipelineGuide';
import {formatTimestamp} from './time';
import type {Fault,Language,Quality,Run} from './types';

export function PipelinePage({language,t}:{language:Language;t:(key:string)=>string}){
  const user=useAuth().user!;
  const [runs,setRuns]=useState<Run[]>([]),[run,setRun]=useState<Run|null>(null),[quality,setQuality]=useState<Quality|null>(null),[faults,setFaults]=useState<Fault[]>([]),[scenario,setScenario]=useState('wrong_net_amount'),[faultQuality,setFaultQuality]=useState<unknown>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const gate=useRef(false),live=useRef(true),chosen=useRef('');
  const date=(value:string)=>formatTimestamp(value,language);
  async function inspect(id:string){const [r,q]=await Promise.all([api<Run>('/runs/'+id),api<Quality|null>('/runs/'+id+'/quality')]);if(live.current){chosen.current=id;setRun(r);setQuality(q);setFaultQuality(null);}}
  async function refresh(){const [r,f]=await Promise.all([api<Run[]>('/runs'),api<Fault[]>('/faults')]);if(live.current){setRuns(r);setFaults(f);return r;}return [];}
  async function action(work:()=>Promise<void>){if(gate.current)return;gate.current=true;setBusy(true);setError('');try{await work();}catch(e){if(live.current&&e instanceof Error&&e.message!=='STALE_REQUEST')setError(e.message);}finally{gate.current=false;if(live.current)setBusy(false);}}
  useEffect(()=>{live.current=true;action(async()=>{const r=await refresh();if(r[0])await inspect(r[0].run_id);});return()=>{live.current=false;};},[user.user_id]);
  return <><p className="course-kicker">SOURCE → BRONZE → SILVER → GOLD → TARGET</p><div className="section-title"><h1>{t('pipeline')}</h1><button className="primary" disabled={busy} onClick={()=>action(async()=>{const value=await api<Run>('/runs',{});await refresh();await inspect(value.run_id);})}>{t('runPipeline')}</button></div>{error&&<p className="notice error" role="alert">{t(error)}</p>}{busy&&<p className="working" role="status">{t('loading')}</p>}<PipelineGuide t={t}/>{runs.length>0&&<><label className="run-selector">{t('selectedRun')}<select value={run?.run_id??runs[0].run_id} disabled={busy} onChange={e=>action(()=>inspect(e.target.value))}>{runs.map(r=><option key={r.run_id} value={r.run_id}>{date(r.started_at)} · {r.run_id.slice(0,8)} · {r.is_shared?t('sampleRun'):r.execution_status}</option>)}</select></label><p className="muted">{t('timestampHelp')}</p></>}{run&&<>{run.is_shared&&<p className="notice">{t('sampleRunHelp')}</p>}<details className="pipeline-times"><summary>{t('timeDetails')}</summary><dl><dt>{t('startedAt')}</dt><dd><time dateTime={run.started_at}>{date(run.started_at)}</time><br/><code>UTC: {new Date(run.started_at).toISOString()}</code></dd>{run.completed_at&&<><dt>{t('completedAt')}</dt><dd><time dateTime={run.completed_at}>{date(run.completed_at)}</time><br/><code>UTC: {new Date(run.completed_at).toISOString()}</code></dd></>}</dl></details><section className="panel run-status"><div>{t('execution')} <Badge value={run.execution_status}/></div><div>{t('quality')} <Badge value={run.data_quality_status}/></div><button className="secondary" disabled={busy||!!run.is_shared||run.execution_status!=='SUCCESS'} onClick={()=>action(async()=>{await api('/runs/'+run.run_id+'/quality',{});await inspect(run.run_id);})}>{t('runQuality')}</button></section><div className="stage-grid">{run.stages?.map(s=><article className="panel stage" key={s.name}><span className="eyebrow">{s.name}</span><strong>{s.row_count?.toLocaleString()}</strong><span>{t('rowCount')}</span><Badge value={s.execution_status}/><details><summary>{t('evidence')}</summary><Json value={s.metrics}/></details></article>)}</div>{quality&&<section className="panel"><div className="section-title"><h2>{t('quality')}</h2><Badge value={quality.status}/></div>{quality.results.map(c=><details key={c.rule_id}><summary><Badge value={c.status}/> {c.rule_id}</summary><h4>{t('expectedValue')}</h4><Json value={c.expected}/><h4>{t('actual')}</h4><Json value={c.actual}/><h4>{t('evidence')}</h4><Json value={c.evidence}/>{c.error&&<p className="notice error">{c.error}</p>}</details>)}</section>}
  <section className="panel"><h2>{t('faults')}</h2><p className="muted">{t('faultHelp')}</p><div className="button-row"><select aria-label="Fault scenario" value={scenario} disabled={busy||!!run.is_shared} onChange={e=>setScenario(e.target.value)}>{['missing_order','duplicate_order','null_net_amount','wrong_net_amount'].map(s=><option key={s} value={s}>{t(s)}</option>)}</select><button className="secondary" disabled={busy||!!run.is_shared||run.execution_status!=='SUCCESS'||faults.some(f=>f.pipeline_run_id===run.run_id&&f.status==='APPLIED')} onClick={()=>action(async()=>{await api('/faults',{scenario,run_id:run.run_id});setFaultQuality(null);await refresh();})}>{t('applyFault')}</button></div>{faults.filter(f=>f.pipeline_run_id===run.run_id).map(f=><div className="history-item" key={f.fault_run_id}><div className="button-row"><strong>{t(f.scenario_id)}</strong><Badge value={f.status}/>{f.status==='APPLIED'&&<><button className="secondary" disabled={busy} onClick={()=>action(async()=>{setFaultQuality(await api('/faults/'+f.fault_run_id+'/quality',{}));})}>{t('validateFault')}</button><button className="text-button" disabled={busy} onClick={()=>action(async()=>{await api('/faults/'+f.fault_run_id+'/reset',{});setFaultQuality(null);await refresh();})}>{t('resetFault')}</button></>}</div><details><summary>{t('evidence')}</summary><Json value={f.mutation_evidence}/></details></div>)}{faultQuality!==null&&<Json value={faultQuality}/>}</section></>}</>;
}
