import type {Language,QueryResult,Session} from './types';
export function HttpEvidence({result,language}:{result:QueryResult;language:Language}){
 const http=result.http;if(!http)return null;
 const eng=language==='ENG';
 return <div className="http-evidence"><div className="section-title"><strong>GET /orders</strong><span>{http.request_count} {eng?'HTTP requests':'request HTTP'}</span></div><p>{eng?'Transport execution':'Thực thi truyền tải'}: <strong>{http.execution_status}</strong> · {eng?'Quality under your checks':'Chất lượng theo checks của bạn'}: <strong>{http.data_quality_status}</strong></p><p className="muted">{eng?'This quality result uses your checks. Submission also tests independent clean and defective cases.':'Kết quả này dùng checks của bạn. Khi nộp, hệ thống còn chấm trên các case sạch và lỗi độc lập.'}</p><div className="table-scroll"><table><thead><tr>{(eng?['Page','Attempt','Status','Time','Final']:['Trang','Lần','Status','Thời gian','Cuối']).map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{http.trace.map((step,i)=><tr key={i}><td>{step.page}</td><td>{step.attempt}</td><td>{step.status??'TIMEOUT'}</td><td>{step.elapsed_ms} ms</td><td>{step.final?'✓':'↻'}</td></tr>)}</tbody></table></div><details><summary>{eng?'HTTP response bodies and headers':'Body và header response HTTP'}</summary>{http.trace.map((step,i)=><div key={i}><h4>{step.page} / {step.attempt} · {step.status??'TIMEOUT'}</h4><pre className="json">{JSON.stringify({headers:step.headers,body:step.body},null,2)}</pre></div>)}</details><details><summary>{eng?'Collected records':'Bản ghi đã thu thập'} ({http.records.length})</summary><pre className="json">{JSON.stringify(http.records,null,2)}</pre></details>{http.replayed_batches>0&&<details open><summary>{eng?'PostgreSQL Target after two replays':'Target PostgreSQL sau hai lần replay'} ({http.target.length})</summary><pre className="json">{JSON.stringify(http.target,null,2)}</pre></details>}</div>;
}
export function EtlControls({session,busy,language,onAction}:{session:Session;busy:boolean;language:Language;onAction:(action:string)=>void}){
 const state=session.etl_simulation;if(!state)return null;const eng=language==='ENG';
 const enabled=session.status==='ACTIVE'&&session.mode==='SANDBOX';
 const actions=session.lab_id==='lab_017_etl_replay'?['RESET','NEXT','REPLAY']:session.lab_id==='lab_018_etl_recovery'?['RESET','RECOVER']:['RESET','RUN'];
 const labels:Record<string,string>=eng?{RESET:'Reset',NEXT:'Next batch',REPLAY:'Replay batch',RUN:'Run ETL',RECOVER:'Recover load'}:{RESET:'Đặt lại',NEXT:'Batch tiếp',REPLAY:'Replay batch',RUN:'Chạy ETL',RECOVER:'Khôi phục load'};
 return <section className="panel etl-controls"><h2>{eng?'ETL execution workspace':'Không gian chạy ETL'}</h2><p>{eng?'Batch':'Batch'} {state.batch_no} · {eng?'Controls change your session tables; rerun the SQL check after each action.':'Điều khiển thay đổi bảng trong session của bạn; chạy lại SQL sau mỗi thao tác.'}</p>{!enabled&&<p className="muted">{eng?'Start an active SANDBOX to use the controls.':'Bắt đầu SANDBOX đang ACTIVE để dùng điều khiển.'}</p>}<div className="button-row">{actions.map(action=><button className="secondary" key={action} disabled={busy||!enabled} onClick={()=>onAction(action)}>{labels[action]}</button>)}</div><div className="table-scroll"><table><thead><tr>{(eng?['Step','Action','Execution','Target','Rejects','Checkpoint']:['Step','Thao tác','Thực thi','Target','Reject','Checkpoint']).map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{state.steps.map(s=><tr key={s.step_no}><td>{s.step_no}</td><td>{s.operation}</td><td><span className={'badge '+s.execution_status.toLowerCase()}>{s.execution_status}</span></td><td>{s.target_rows}</td><td>{s.rejected_rows}</td><td>{s.checkpoint}</td></tr>)}</tbody></table></div>{!state.steps.length&&<p className="empty">{eng?'No batch has run since reset.':'Chưa chạy batch sau khi đặt lại.'}</p>}</section>;
}
