"""ENG/VIE guided practice for advanced SQL and data pipeline QA."""

def text(title, summary, objectives, theory, steps, practice, expected, requirement, hints, explanation):
    return dict(title=title,summary=summary,objectives=objectives,theory=theory,steps=steps,
                practice_sql=practice,practice_expected=expected,requirement=requirement,
                hints=hints,explanation=explanation)


CATALOG = {
 "lab_007_join_grain": {
  "order":7,"level":"ADVANCED","track":"SQL_ADVANCED","minutes":35,
  "ENG":text("JOIN without multiplying revenue","Aggregate to the intended grain before joining.",
   ["Diagnose many-to-many fanout","Use CTEs to reconcile order-level totals"],
   "order_lines has one row per order/line; order_payments has one row per order/payment. Joining them directly by order_id multiplies every line by every payment. Two lines and two payments produce four rows. SUM(DISTINCT amount) is not a repair: different lines can legitimately have the same amount. Aggregate each side to order grain before joining. Target totals must match the sum of lines, including zero amounts.",
   ["Count lines and payments per order.","Run the example and compare its inflated sum with an independent line sum.","Build an expected CTE grouped by order_id.","FULL JOIN Target and count missing, unexpected or unequal order totals."],
   "SELECT l.order_id, COUNT(*) AS joined_rows, SUM(l.net_amount) AS joined_revenue FROM order_lines l JOIN order_payments p USING(order_id) GROUP BY l.order_id ORDER BY l.order_id;",
   "Even clean data can produce inflated revenue in this exploratory JOIN. The defect is in the query grain, not necessarily the Target.",
   "Return violation_count: FULL JOIN rows between the order-level SUM(order_lines.net_amount) and target_order_totals with a missing key or distinct amount. Count an order once even if multiple lines contributed. Target keys are unique in this exercise.",
   ["Inspect multiplicity on both sides before summing.","Aggregate order_lines alone, with GROUP BY order_id.","FULL JOIN the aggregate to Target and use IS DISTINCT FROM; count the violating rows."],
   "Pre-aggregation prevents fanout. FULL JOIN also detects missing and unexpected orders. Exact NUMERIC compares cents; equal overall revenue cannot prove each order is correct."),
  "VIE":text("JOIN mà không nhân đôi doanh thu","Tổng hợp về đúng grain trước khi JOIN.",
   ["Chẩn đoán fanout do JOIN nhiều-nhiều","Dùng CTE đối soát tổng tiền từng order"],
   "order_lines có grain order/line; order_payments có grain order/payment. JOIN trực tiếp bằng order_id sẽ lặp mỗi line theo số payment. Hai line và hai payment tạo bốn dòng. SUM(DISTINCT amount) không sửa được lỗi: các line khác nhau có thể cùng số tiền hợp lệ. Tổng hợp mỗi phía về grain order trước khi JOIN. Tổng Target phải bằng SUM các line, kể cả số 0.",
   ["Đếm line và payment của từng order.","Chạy ví dụ và so tổng bị nhân với SUM line độc lập.","Viết CTE kỳ vọng GROUP BY order_id.","FULL JOIN Target, đếm order thiếu, thừa hoặc sai tổng."],
   "SELECT l.order_id, COUNT(*) AS joined_rows, SUM(l.net_amount) AS joined_revenue FROM order_lines l JOIN order_payments p USING(order_id) GROUP BY l.order_id ORDER BY l.order_id;",
   "Ngay dữ liệu sạch cũng có thể bị nhân doanh thu bởi JOIN khám phá này. Grain truy vấn sai chưa đồng nghĩa Target sai.",
   "Trả violation_count: số dòng FULL JOIN giữa SUM(order_lines.net_amount) ở grain order và target_order_totals có key thiếu/thừa hoặc amount khác. Mỗi order sai tính một lần, dù có nhiều line. Bài này đảm bảo key Target duy nhất.",
   ["Xem số dòng mỗi key ở cả hai phía trước khi SUM.","Chỉ tổng hợp order_lines bằng GROUP BY order_id.","FULL JOIN tổng kỳ vọng với Target, dùng IS DISTINCT FROM rồi đếm dòng vi phạm."],
   "Tổng hợp trước JOIN tránh fanout. FULL JOIN bắt cả order thiếu và thừa. NUMERIC giữ chính xác từng cent; tổng revenue bằng nhau chưa chứng minh từng order đúng."),
 },
 "lab_008_latest_version": {
  "order":8,"level":"ADVANCED","track":"SQL_ADVANCED","minutes":35,
  "ENG":text("Pick the latest version deterministically","Rank events with CTEs and ROW_NUMBER.",
   ["Partition versions by business key","Resolve timestamp ties with event_id"],
   "Source contains multiple versions of each order. Latest means greatest (updated_at, event_id), not greatest amount or last physical row. Two events may share updated_at; larger event_id is the documented winner. ROW_NUMBER over each order with both fields descending provides one deterministic record. MAX(updated_at) followed by a join can return both tied events. Compare key completeness and all selected fields.",
   ["Inspect Source events ordered by key, time and event ID.","Create a ranked CTE partitioned by order_id.","Keep rn=1 and FULL JOIN current Target.","Count missing/unexpected keys or distinct event ID, time or amount."],
   "SELECT order_id,event_id,updated_at,net_amount,ROW_NUMBER() OVER(PARTITION BY order_id ORDER BY updated_at DESC,event_id DESC) AS rn FROM source_order_events ORDER BY order_id,rn;",
   "One order has a timestamp tie. The larger event_id must win even though its amount is not a MAX rule.",
   "Return violation_count: FULL JOIN rows between each latest Source event and target_current_orders with missing/unexpected keys or unequal event_id, updated_at or net_amount (NULL-safe). Each key counts once.",
   ["Latest is a tuple ordering, not MAX(amount).","Use ROW_NUMBER PARTITION BY order_id ORDER BY updated_at DESC,event_id DESC.","Filter rn=1, FULL JOIN and compare the three fields using IS DISTINCT FROM."],
   "Deterministic tie-breaking avoids ambiguous current snapshots. An inner join misses missing keys; a time-only rank can silently choose the wrong tied event."),
  "VIE":text("Chọn phiên bản mới nhất có quy tắc","Xếp hạng event bằng CTE và ROW_NUMBER.",
   ["Chia phiên bản theo business key","Giải quyết timestamp bằng nhau bằng event_id"],
   "Source chứa nhiều phiên bản mỗi order. Mới nhất là bộ (updated_at, event_id) lớn nhất, không phải amount lớn nhất hay dòng vật lý cuối. Khi timestamp bằng nhau, event_id lớn hơn thắng theo quy tắc bài. ROW_NUMBER theo order với cả hai cột giảm dần chọn đúng một bản ghi. MAX(updated_at) rồi JOIN lại có thể trả cả hai event đồng thời. Cần đối soát key và mọi trường được chọn.",
   ["Xem event theo key, timestamp và event ID.","Tạo CTE xếp hạng PARTITION BY order_id.","Giữ rn=1 rồi FULL JOIN Target hiện tại.","Đếm key thiếu/thừa hoặc event ID, timestamp, amount khác."],
   "SELECT order_id,event_id,updated_at,net_amount,ROW_NUMBER() OVER(PARTITION BY order_id ORDER BY updated_at DESC,event_id DESC) AS rn FROM source_order_events ORDER BY order_id,rn;",
   "Một order có hai event cùng timestamp. event_id lớn hơn phải thắng; đây không phải quy tắc MAX(amount).",
   "Trả violation_count: số dòng FULL JOIN phiên bản Source mới nhất với target_current_orders bị thiếu/thừa key hoặc khác event_id, updated_at, net_amount; so an toàn với NULL. Mỗi key sai tính một lần.",
   ["Mới nhất được xác định bằng thứ tự một bộ giá trị, không phải MAX(amount).","Dùng ROW_NUMBER PARTITION BY order_id ORDER BY updated_at DESC,event_id DESC.","Giữ rn=1, FULL JOIN rồi so ba trường bằng IS DISTINCT FROM."],
   "Tie-break rõ ràng tránh snapshot current mơ hồ. INNER JOIN bỏ sót key thiếu; xếp hạng chỉ theo thời gian có thể chọn sai event cùng timestamp."),
 },
 "lab_009_utc_dates": {
  "order":9,"level":"ADVANCED","track":"SQL_ADVANCED","minutes":30,
  "ENG":text("A timestamp, two calendar days","Reconcile day grain in explicit UTC.",
   ["Distinguish instants from local date labels","Check daily counts and exact revenue"],
   "TIMESTAMPTZ represents an instant. The calendar date depends on a chosen timezone: 23:30 UTC is the next date in UTC+07. The contract is UTC day, so use (ordered_at AT TIME ZONE 'UTC')::date explicitly. A bare timestamptz::date depends on the connection timezone. Test midnight and year-end boundaries. Daily row count measures days, not orders; compare order_count and net_revenue per date.",
   ["Display each instant as UTC and Asia/Bangkok calendar dates.","Aggregate Source by explicit UTC date.","FULL JOIN Target dates to find missing and unexpected days.","Count daily rows with distinct order_count or revenue, once per date."],
   "SELECT order_id,ordered_at,(ordered_at AT TIME ZONE 'UTC')::date AS utc_day,(ordered_at AT TIME ZONE 'Asia/Bangkok')::date AS local_day FROM source_time_orders ORDER BY ordered_at;",
   "Rows near midnight/year-end have different UTC and UTC+07 dates; their instant and amount remain unchanged.",
   "Return violation_count: FULL JOIN rows between Source grouped by UTC date and target_utc_daily with a missing date or distinct COUNT(*) / SUM(net_amount). A day counts once even if both totals differ.",
   ["Choose timezone before casting to date.","GROUP BY (ordered_at AT TIME ZONE 'UTC')::date; compute count and SUM.","FULL JOIN by order_date and use NULL-safe comparisons for both measures."],
   "Explicit UTC makes the check independent of session timezone. A local-day load can conserve total revenue while placing orders in the wrong reporting dates."),
  "VIE":text("Một timestamp, hai ngày lịch","Đối soát grain ngày bằng UTC rõ ràng.",
   ["Phân biệt thời điểm và nhãn ngày địa phương","Kiểm tra count và revenue mỗi ngày"],
   "TIMESTAMPTZ biểu diễn một thời điểm. Ngày lịch phụ thuộc timezone: 23:30 UTC là ngày kế tiếp tại UTC+07. Contract là ngày UTC, nên dùng (ordered_at AT TIME ZONE 'UTC')::date. Ép timestamptz::date trực tiếp phụ thuộc timezone của connection. Cần kiểm tra ranh giới nửa đêm và cuối năm. Count dòng ngày đếm ngày, không đếm order; so order_count và net_revenue theo từng ngày.",
   ["Hiển thị mỗi thời điểm dưới dạng ngày UTC và Asia/Bangkok.","Tổng hợp Source theo ngày UTC rõ ràng.","FULL JOIN ngày với Target để tìm ngày thiếu và thừa.","Đếm dòng ngày khác order_count hoặc revenue; mỗi ngày tính một lần."],
   "SELECT order_id,ordered_at,(ordered_at AT TIME ZONE 'UTC')::date AS utc_day,(ordered_at AT TIME ZONE 'Asia/Bangkok')::date AS local_day FROM source_time_orders ORDER BY ordered_at;",
   "Các dòng gần nửa đêm/cuối năm có ngày UTC và UTC+07 khác nhau; thời điểm và amount không đổi.",
   "Trả violation_count: số dòng FULL JOIN Source tổng hợp ngày UTC với target_utc_daily có ngày thiếu/thừa hoặc COUNT(*) / SUM(net_amount) khác. Một ngày tính một lần dù cả hai tổng sai.",
   ["Chọn timezone trước khi ép sang date.","GROUP BY (ordered_at AT TIME ZONE 'UTC')::date; tính COUNT và SUM.","FULL JOIN theo order_date, so cả hai chỉ số an toàn với NULL."],
   "UTC rõ ràng giúp kết quả không phụ thuộc timezone session. Load theo ngày địa phương có thể giữ nguyên tổng revenue nhưng đưa order vào sai ngày báo cáo."),
 },
 "lab_010_incremental": {
  "order":10,"level":"ADVANCED","track":"INCREMENTAL","minutes":50,
  "ENG":text("Incremental loads: replay and late arrivals","Run real batches and verify an idempotent keyed merge.",
   ["Distinguish event time from arrival time","Prove replay safety and correct latest-state upserts"],
   "Three deterministic batches contain new orders, updates, timestamp ties and late arrivals. event_at is business version time; arrived_at controls availability. The latest (event_at,event_id) wins per order among events arrived by lab_context.as_of. A new order may arrive after a newer event-time watermark and must still load. An older late version must not overwrite a newer version. Replay must preserve one current row per key. The trusted simulator writes only your session; learner SQL remains read-only. Sessions start after batches 1,2,replay 2,3. In Sandbox, reset and advance them again.",
   ["Inspect incremental_steps, the fixed as_of clock and event arrival/version times.","In Sandbox reset, run batch 1, batch 2, replay it, then run batch 3.","Observe row counts and which event wins each key; compare before/after replay.","Rank available events, FULL JOIN Target and add duplicated key-group count."],
   "SELECT step_no,batch_no,operation,execution_status,selected_events,target_rows,watermark FROM incremental_steps ORDER BY step_no;",
   "Clean replay keeps row count unchanged. In faulty append mode SUCCESS can coexist with duplicates; an event-time watermark can miss late keys and tied updates.",
   "Return violation_count = mismatched FULL JOIN rows plus duplicated order_id groups. Expected is the latest (event_at,event_id) per key from incremental_events WHERE arrived_at <= lab_context.as_of. A mismatch is a missing/unexpected key or distinct event_id,event_at,net_amount. This is a sum of rule violations, not unique bad orders. Grading rebuilds independent fully processed fixtures regardless of your current simulation step.",
   ["Filter on arrived_at <= as_of before ranking by business version time.","Use ROW_NUMBER per order ordered by event_at DESC,event_id DESC; FULL JOIN rn=1 to Target.","Count NULL-safe key/field mismatches and add the count of GROUP BY order_id HAVING COUNT(*)>1."],
   "Arrival availability and business version ordering solve different problems. Keyed replacement with a greatest-version guard accepts late new keys, prevents old overwrites and makes replay idempotent. A single event-time watermark or append-only load fails these properties. This finite simulation does not implement a production CDC connector, scheduler or deletes."),
  "VIE":text("Incremental: chạy lại và dữ liệu đến muộn","Chạy batch thật và kiểm tra merge theo key có tính idempotent.",
   ["Phân biệt event time và thời gian nhận dữ liệu","Chứng minh replay an toàn và upsert đúng phiên bản"],
   "Ba batch cố định chứa order mới, cập nhật, timestamp bằng nhau và dữ liệu đến muộn. event_at là thời gian phiên bản nghiệp vụ; arrived_at quyết định dữ liệu đã sẵn sàng. Mỗi order chọn (event_at,event_id) lớn nhất trong event đã đến trước lab_context.as_of. Order mới có thể đến sau watermark event time mới hơn mà vẫn phải được load. Phiên bản cũ đến muộn không được đè bản mới. Replay phải giữ một dòng current mỗi key. Simulator chỉ ghi vào session của bạn; SQL người học vẫn chỉ đọc. Session bắt đầu sau batch 1,2,replay 2,3. Trong Sandbox có thể reset và chạy lại từng bước.",
   ["Xem incremental_steps, đồng hồ as_of cố định và thời gian event/arrival.","Trong Sandbox: reset, chạy batch 1, batch 2, replay, rồi chạy batch 3.","Quan sát row count và event thắng mỗi key; so trước/sau replay.","Xếp hạng event đã đến, FULL JOIN Target rồi cộng số nhóm key trùng."],
   "SELECT step_no,batch_no,operation,execution_status,selected_events,target_rows,watermark FROM incremental_steps ORDER BY step_no;",
   "Replay sạch không đổi row count. Append lỗi vẫn SUCCESS nhưng tạo duplicate; watermark event time có thể bỏ sót key đến muộn và cập nhật cùng timestamp.",
   "Trả violation_count = số dòng FULL JOIN sai + số nhóm order_id trùng. Kỳ vọng là (event_at,event_id) mới nhất mỗi key từ incremental_events WHERE arrived_at <= lab_context.as_of. Dòng sai gồm key thiếu/thừa hoặc event_id,event_at,net_amount khác. Đây là tổng vi phạm quy tắc, không phải số order lỗi duy nhất. Grader dựng fixture độc lập đã chạy đủ batch, không phụ thuộc bước mô phỏng đang mở.",
   ["Lọc arrived_at <= as_of trước khi xếp hạng theo thời gian phiên bản.","ROW_NUMBER theo order, ORDER BY event_at DESC,event_id DESC; FULL JOIN rn=1 với Target.","Đếm key/trường khác an toàn với NULL, cộng số nhóm GROUP BY order_id HAVING COUNT(*)>1."],
   "Thời gian nhận và thứ tự phiên bản giải quyết hai vấn đề khác nhau. Merge theo key có điều kiện phiên bản lớn nhất nhận key mới đến muộn, tránh đè bản mới và replay không tạo trùng. Chỉ watermark event time hoặc append sẽ vi phạm. Mô phỏng hữu hạn này chưa triển khai CDC connector, scheduler hay event xóa trong production."),
 },
 "lab_011_freshness": {
  "order":11,"level":"ADVANCED","track":"FRESHNESS","minutes":35,
  "ENG":text("SUCCESS but stale data","Measure freshness against a reproducible clock and SLA.",
   ["Separate load success from data freshness","Handle missing, NULL, future and boundary timestamps"],
   "Each expected dataset has an as_of evaluation instant and sla_minutes. A successful load can contain old events, so check both last_success_at and last_event_at. Age equal to the SLA is valid; only greater age fails. Missing observations, NULL times, future times and non-SUCCESS execution also fail. Count each required dataset once even if multiple rules fail. Use the fixture clock, not NOW(): the same saved session must give the same verdict tomorrow.",
   ["LEFT JOIN observations onto all expected dataset requirements.","Compute both ages relative to each requirement's as_of.","Test SLA equality, missing observations, NULL and future timestamps.","Count datasets violating any documented freshness rule."],
   "SELECT r.dataset_id,r.sla_minutes,r.as_of-o.last_success_at AS load_age,r.as_of-o.last_event_at AS data_age,o.execution_status FROM freshness_requirements r LEFT JOIN freshness_observations o USING(dataset_id) ORDER BY r.dataset_id;",
   "A stale-data scenario still reports SUCCESS. The clean boundary fixture has age exactly equal to the SLA and must pass.",
   "Return violation_count: required datasets missing an observation, not SUCCESS, having NULL/future success or event times, or either age greater than sla_minutes * INTERVAL '1 minute'. Count each dataset once. Dataset IDs are unique; extra observations are outside this contract.",
   ["Start from requirements so absent datasets are not lost.","Use as_of and dataset-specific SLA; distinguish > from >=.","Combine missing/status/NULL/future/age conditions with OR and COUNT(*) over the LEFT JOIN."],
   "A fixed clock makes the test reproducible. Checking execution alone misses stale events; checking event age alone misses failed loads. One dataset can fail multiple conditions but contributes one violation."),
  "VIE":text("SUCCESS nhưng dữ liệu đã cũ","Đo freshness bằng đồng hồ cố định và SLA.",
   ["Tách load thành công và độ mới dữ liệu","Xử lý timestamp thiếu, NULL, tương lai và ranh giới SLA"],
   "Mỗi dataset kỳ vọng có thời điểm đánh giá as_of và sla_minutes. Load thành công vẫn có thể chứa event cũ, nên kiểm tra cả last_success_at và last_event_at. Tuổi bằng SLA hợp lệ; chỉ lớn hơn mới sai. Observation thiếu, timestamp NULL, timestamp tương lai hoặc thực thi khác SUCCESS cũng sai. Mỗi dataset tính một lần dù vi phạm nhiều điều kiện. Dùng đồng hồ fixture, không NOW(): mở lại session ngày mai vẫn phải ra cùng verdict.",
   ["LEFT JOIN observation từ toàn bộ requirement dataset.","Tính cả hai tuổi so với as_of của requirement.","Kiểm tra bằng SLA, observation thiếu, NULL và timestamp tương lai.","Đếm dataset vi phạm bất kỳ quy tắc freshness đã nêu."],
   "SELECT r.dataset_id,r.sla_minutes,r.as_of-o.last_success_at AS load_age,r.as_of-o.last_event_at AS data_age,o.execution_status FROM freshness_requirements r LEFT JOIN freshness_observations o USING(dataset_id) ORDER BY r.dataset_id;",
   "Tình huống dữ liệu cũ vẫn báo SUCCESS. Fixture sạch ở ranh giới có tuổi đúng bằng SLA và phải PASS.",
   "Trả violation_count: số dataset bắt buộc thiếu observation, khác SUCCESS, có thời gian success/event NULL hoặc tương lai, hay một trong hai tuổi lớn hơn sla_minutes * INTERVAL '1 minute'. Mỗi dataset tính một lần. Dataset ID duy nhất; observation thừa nằm ngoài contract.",
   ["Bắt đầu từ requirements để không mất dataset chưa có observation.","Dùng as_of và SLA riêng mỗi dataset; phân biệt > với >=.","OR các điều kiện thiếu/status/NULL/tương lai/tuổi rồi COUNT(*) trên LEFT JOIN."],
   "Đồng hồ cố định giúp tái hiện test. Chỉ status bỏ sót event cũ; chỉ tuổi event bỏ sót load thất bại. Một dataset có thể vi phạm nhiều điều kiện nhưng chỉ cộng một vi phạm."),
 },
 "lab_012_scd_type1": {
  "order":12,"level":"ADVANCED","track":"SCD","minutes":35,
  "ENG":text("SCD Type 1: overwrite current attributes","Validate the latest customer dimension without history.",
   ["Explain Type 1 overwrite semantics","Reconcile the latest source change by customer key"],
   "Type 1 stores one current row per customer and overwrites old attributes. It cannot answer what tier a customer had last month. Choose the greatest (effective_at,event_id) from source changes, resolving simultaneous corrections deterministically. Target should contain that customer, tier, effective time and event ID. The exercise guarantees unique Target customer keys; validate missing keys and fields, including NULL tier.",
   ["Inspect customer changes in version order.","Rank each customer by effective_at and event_id descending.","FULL JOIN the winning changes to target_customers_current.","Count missing/unexpected customers or distinct tier/time/event ID."],
   "SELECT customer_id,event_id,effective_at,tier FROM source_customer_changes ORDER BY customer_id,effective_at,event_id;",
   "A simultaneous correction has a higher event_id. Current Target should contain the corrected tier, not both rows.",
   "Return violation_count: FULL JOIN rows between latest Source changes per customer and Target with missing/unexpected keys or distinct tier,effective_at,event_id. Count each customer once. Latest uses effective_at DESC,event_id DESC.",
   ["Type 1 retains current state, not every historical version.","ROW_NUMBER PARTITION BY customer_id ORDER BY effective_at DESC,event_id DESC.","Keep rn=1; FULL JOIN and compare all three fields with IS DISTINCT FROM."],
   "A Type 1 dimension matches the newest known business change, including deterministic corrections. Counts and valid-looking tiers can still conceal stale attributes. Historical analysis needs Type 2."),
  "VIE":text("SCD Type 1: ghi đè thuộc tính hiện tại","Kiểm tra customer dimension mới nhất, không lưu lịch sử.",
   ["Giải thích cách ghi đè Type 1","Đối soát thay đổi Source mới nhất theo customer key"],
   "Type 1 giữ một dòng current mỗi customer và ghi đè thuộc tính cũ. Nó không trả lời customer có tier nào tháng trước. Chọn (effective_at,event_id) lớn nhất từ source changes, xử lý correction đồng thời có quy tắc. Target phải chứa customer, tier, thời gian hiệu lực và event ID đó. Bài đảm bảo key customer Target duy nhất; kiểm tra key thiếu và các trường, kể cả tier NULL.",
   ["Xem customer changes theo thứ tự phiên bản.","Xếp hạng mỗi customer theo effective_at và event_id giảm dần.","FULL JOIN phiên bản thắng với target_customers_current.","Đếm customer thiếu/thừa hoặc tier/time/event ID khác."],
   "SELECT customer_id,event_id,effective_at,tier FROM source_customer_changes ORDER BY customer_id,effective_at,event_id;",
   "Correction cùng timestamp có event_id cao hơn. Target current phải giữ tier đã sửa, không giữ cả hai dòng.",
   "Trả violation_count: số dòng FULL JOIN Source mới nhất mỗi customer với Target có key thiếu/thừa hoặc khác tier,effective_at,event_id. Mỗi customer tính một lần. Mới nhất dùng effective_at DESC,event_id DESC.",
   ["Type 1 giữ trạng thái hiện tại, không giữ mọi phiên bản lịch sử.","ROW_NUMBER PARTITION BY customer_id ORDER BY effective_at DESC,event_id DESC.","Giữ rn=1; FULL JOIN và so ba trường bằng IS DISTINCT FROM."],
   "Dimension Type 1 khớp thay đổi nghiệp vụ mới nhất, kể cả correction có tie-break. Count đúng và tier trông hợp lệ vẫn có thể che thuộc tính cũ. Phân tích lịch sử cần Type 2."),
 },
 "lab_013_scd_type2": {
  "order":13,"level":"ADVANCED","track":"SCD","minutes":55,
  "ENG":text("SCD Type 2: trustworthy history","Check half-open validity windows and current versions.",
   ["Derive historical windows with LEAD","Investigate overlap, missing history and current flags"],
   "Type 2 retains historical attributes in [valid_from,valid_to) intervals: the start is included, the end is excluded. Adjacent intervals sharing an endpoint do not overlap. NULL valid_to denotes infinity for the final current version. For changes at the same effective_at, the greatest event_id replaces the simultaneous correction; it must not create a zero-length version. Build expected history by resolving those ties then using LEAD(effective_at). Validate both source reconciliation and temporal constraints. The requested sum can count the same root defect more than once.",
   ["Inspect Source changes and resolve same-time corrections.","Use LEAD to derive each expected end time; compare by customer_id,valid_from.","Self-join distinct version_id pairs to find half-open overlaps; inspect current counts and invalid ranges.","Add the five documented check counts and explain overlapping evidence."],
   "SELECT customer_id,version_id,tier,valid_from,valid_to,is_current,LEAD(valid_from) OVER(PARTITION BY customer_id ORDER BY valid_from,version_id) AS next_start FROM target_customer_history ORDER BY customer_id,valid_from,version_id;",
   "Clean adjacent windows touch but never overlap; each customer has one current version. A faulty current flag can leave correct dates while creating two current rows.",
   "Return violation_count as the sum of: FULL JOIN reference mismatch rows keyed by (customer_id,valid_from), comparing tier,valid_to,is_current; overlapping same-customer version pairs counted once with a.version_id<b.version_id and half-open strict inequalities (NULL end=infinity); Target customer groups with current count <>1; rows with valid_to<=valid_from; duplicated (customer_id,valid_from) groups. Reference resolves equal effective_at with highest event_id then uses LEAD. A missing version counts in reconciliation; this diagnostic sum is not unique bad customers.",
   ["Deduplicate simultaneous Source changes by customer/time with descending event_id, then LEAD the effective times.","Compare expected and actual versions with FULL JOIN and IS DISTINCT FROM; NULL final end is valid.","Add reference mismatches, strict interval overlaps, wrong current counts, nonpositive ranges and duplicate start groups."],
   "Half-open intervals allow adjacent history without false overlaps. Reference comparison catches lost history and wrong attributes even when window constraints look valid. Current flags and temporal rules supply independent evidence; their sum intentionally measures rule violations."),
  "VIE":text("SCD Type 2: lịch sử đáng tin cậy","Kiểm tra khoảng hiệu lực nửa mở và phiên bản current.",
   ["Dựng khoảng lịch sử bằng LEAD","Điều tra chồng thời gian, mất lịch sử và cờ current"],
   "Type 2 giữ thuộc tính lịch sử trong khoảng [valid_from,valid_to): gồm đầu, không gồm cuối. Hai khoảng liền nhau có chung mốc không bị chồng. valid_to NULL biểu diễn vô hạn cho phiên bản current cuối. Khi hai thay đổi cùng effective_at, event_id lớn nhất thay correction đồng thời; không tạo phiên bản dài bằng 0. Giải quyết tie rồi dùng LEAD(effective_at) để dựng lịch sử kỳ vọng. Kiểm tra cả đối soát Source và ràng buộc thời gian. Tổng yêu cầu có thể đếm một lỗi gốc ở nhiều quy tắc.",
   ["Xem thay đổi Source và xử lý correction cùng timestamp.","Dùng LEAD tính mốc kết thúc kỳ vọng; so theo customer_id,valid_from.","Self JOIN cặp version_id khác nhau để tìm chồng khoảng nửa mở; kiểm tra current count và khoảng sai.","Cộng năm số đếm quy định và giải thích bằng chứng bị giao nhau."],
   "SELECT customer_id,version_id,tier,valid_from,valid_to,is_current,LEAD(valid_from) OVER(PARTITION BY customer_id ORDER BY valid_from,version_id) AS next_start FROM target_customer_history ORDER BY customer_id,valid_from,version_id;",
   "Khoảng sạch liền nhau chạm mốc nhưng không chồng; mỗi customer có một current. Cờ current lỗi có thể giữ ngày đúng nhưng tạo hai dòng current.",
   "Trả violation_count là tổng: dòng FULL JOIN đối soát kỳ vọng theo (customer_id,valid_from), so tier,valid_to,is_current; cặp phiên bản cùng customer bị chồng tính một lần với a.version_id<b.version_id và bất đẳng thức nghiêm ngặt của khoảng nửa mở (NULL end=vô hạn); nhóm customer Target có current count <>1; dòng valid_to<=valid_from; nhóm (customer_id,valid_from) trùng. Kỳ vọng giải quyết effective_at bằng nhau bằng event_id lớn nhất rồi dùng LEAD. Phiên bản thiếu tính ở đối soát; tổng này không phải số customer lỗi duy nhất.",
   ["Loại correction Source đồng thời theo customer/time, event_id giảm dần rồi LEAD thời gian hiệu lực.","FULL JOIN phiên bản kỳ vọng/thực tế và IS DISTINCT FROM; mốc kết thúc NULL cuối cùng hợp lệ.","Cộng sai đối soát, chồng khoảng nghiêm ngặt, current count sai, khoảng không dương và nhóm mốc đầu trùng."],
   "Khoảng nửa mở cho phép lịch sử liền nhau mà không báo chồng sai. Đối soát Source bắt mất phiên bản và sai thuộc tính dù khoảng nhìn hợp lệ. Cờ current và quy tắc thời gian cung cấp bằng chứng độc lập; tổng cố ý đo số vi phạm quy tắc."),
 },
}

# Column names/types are stable SQL identifiers, independent of presentation language.
SCHEMA = {
 "lab_context":{"grain":"one evaluation clock","columns":{"lab_id":"text","as_of":"timestamptz (UTC)"}},
 "order_lines":{"grain":"order_id / line_id","columns":{"order_id":"bigint","line_id":"bigint","net_amount":"numeric(14,2)"}},
 "order_payments":{"grain":"order_id / payment_id","columns":{"order_id":"bigint","payment_id":"bigint","paid_amount":"numeric(14,2)"}},
 "target_order_totals":{"grain":"order_id","columns":{"order_id":"bigint","net_amount":"numeric(14,2)"}},
 "source_order_events":{"grain":"event_id","columns":{"event_id":"bigint","order_id":"bigint","updated_at":"timestamptz (UTC)","net_amount":"numeric(14,2)"}},
 "source_time_orders":{"grain":"order_id","columns":{"order_id":"bigint","ordered_at":"timestamptz (UTC)","net_amount":"numeric(14,2)"}},
 "target_utc_daily":{"grain":"UTC order_date","columns":{"order_date":"date","order_count":"bigint","net_revenue":"numeric(18,2)"}},
 "incremental_events":{"grain":"event_id","columns":{"event_id":"bigint","order_id":"bigint","event_at":"timestamptz (UTC)","arrived_at":"timestamptz (UTC)","net_amount":"numeric(14,2)","batch_no":"integer"}},
 "incremental_target":{"grain":"intended order_id","columns":{"event_id":"bigint","order_id":"bigint","event_at":"timestamptz (UTC)","net_amount":"numeric(14,2)"}},
 "incremental_steps":{"grain":"step_no","columns":{"step_no":"integer","batch_no":"integer","operation":"text","execution_status":"text","selected_events":"integer","target_rows":"integer","watermark":"timestamptz (UTC)"}},
 "freshness_requirements":{"grain":"dataset_id","columns":{"dataset_id":"text","as_of":"timestamptz (UTC)","sla_minutes":"integer"}},
 "freshness_observations":{"grain":"dataset_id","columns":{"dataset_id":"text","last_success_at":"timestamptz (UTC)","last_event_at":"timestamptz (UTC)","execution_status":"text"}},
 "source_customer_changes":{"grain":"event_id","columns":{"event_id":"bigint","customer_id":"bigint","effective_at":"timestamptz (UTC)","tier":"text"}},
 "target_customer_history":{"grain":"version_id; intended customer_id / valid_from","columns":{"version_id":"bigint","customer_id":"bigint","tier":"text","valid_from":"timestamptz (UTC)","valid_to":"timestamptz (UTC), NULL = infinity","is_current":"boolean"}},
}
SCHEMA["target_current_orders"]={"grain":"order_id","columns":SCHEMA["source_order_events"]["columns"]}
SCHEMA["target_customers_current"]={"grain":"customer_id","columns":SCHEMA["source_customer_changes"]["columns"]}
