"""Beginner API guidance using existing fields and existing private reveal gate."""

LABELS = {
    "ENG": ("What are we checking?", "Why does this matter?", "Small worked example — illustrative", "How to practice", "Challenge explained", "Common mistake", "Solution explained"),
    "VIE": ("Chúng ta đang kiểm tra gì?", "Vì sao điều này quan trọng?", "Ví dụ nhỏ — chỉ để minh họa", "Cách thực hành", "Giải thích thử thách", "Lỗi thường gặp", "Giải thích lời giải"),
}

GUIDANCE = {
    "lab_019_api_contract": {
        "ENG": (
            "An API is an interface through which an application requests data. Here GET /orders reads orders from a local HTTP simulation. HTTP status describes the response outcome; 200 means a successful HTTP response, not correct records. A response contract states required fields and their types: order_id and customer_id are JSON integers, while net_amount is a finite decimal string such as '10.01'. Check each collected record against that contract.",
            "A sales feed returns HTTP 200 but omits a price. A report can load the response successfully and still lose money information. Data QA verifies the fields and types before relying on the feed; a known zero amount is valid data.",
            "Three reference records (order_id, customer_id, net_amount): (10, 7, '10.01'), (20, 8, '0.00'), (30, 7, '7.00'). An HTTP 200 response contains all three, but order 30 lacks net_amount. With required-field/type checks and expected status 200, the outcome is transport SUCCESS, quality FAIL, internal diagnostic count 1. The missing field also fails its type check, but that same record counts only once. The '0.00' record passes.",
            "Start an active SANDBOX with clean or a named defect. The API test plan editor accepts JSON, not SQL or an external URL. Before sending, inspect method, path, pagination options and checks; the starter plan checks only status. Send HTTP & test executes the plan against local fixtures. Inspect final attempts, response bodies/headers and Collected records; compare field presence and types with Reference Source orders. Add appropriate checks, send again and compare evidence. The displayed quality uses your checks, so status-only PASS can miss invalid records. There are no separate batch/reset controls for these API lessons. Submit API test grades the plan on independent cases; hints/reveal use the existing lesson controls. Reveal/completion locks further sends/submissions until a new attempt.",
            "Submit a JSON object with request options and a nested checks object, under the unchanged challenge above. GET /orders is the only method/path; page_size is 1–5, paginate/ingest/idempotent are booleans, max_attempts is 1–3 and timeout_ms is 50–300. checks can specify status, required (field-name array) and types (field-name/type object); allowed fields are order_id, customer_id, net_amount and types are integer, decimal, string. Decimal here means a finite numeric string, not a JSON number. You do not submit a SQL violation_count query: the executor produces that diagnostic. Submission PASS means its counts match independent clean and defective expectations across every case; a local quality PASS alone is insufficient. Malformed plans produce validation errors. Your written answer is saved, not semantically graded.",
            "HTTP 200 and executor SUCCESS are not proof of valid records. JSON 7 differs from '7' and true is not an integer here. Do not count a missing field and its wrong type as two bad records. This lesson checks shape/types, not completeness or exact values of every field.",
            "1. method GET and path /orders select the fixed local fixture endpoint; page_size 2 and paginate true collect successive pages within the ten-page bound.\n2. max_attempts 3 and timeout_ms 150 bound each request; only final attempt status is assessed, so a recovered retry is not a final status defect. ingest false leaves this lesson as response validation.\n3. checks.status requires 200 on each final response. checks.required lists all three fields and rejects absent or NULL values.\n4. checks.types requires integer IDs and decimal-string net_amount. A row failing several field rules contributes one diagnostic, not one per rule.\n5. The illustrative missing net_amount produces count 1 and quality FAIL while transport is SUCCESS. Submission runs the same plan on independent expectations; the reference is JSON, even though the shared reveal panel retains its existing solution label.",
        ),
        "VIE": (
            "API là giao diện để ứng dụng yêu cầu dữ liệu. GET /orders ở đây đọc order từ mô phỏng HTTP local. HTTP status mô tả kết quả response; 200 là response HTTP thành công, chưa chứng minh bản ghi đúng. Hợp đồng response nêu trường bắt buộc và kiểu: order_id, customer_id là số nguyên JSON; net_amount là chuỗi số thập phân hữu hạn như '10.01'. Kiểm tra từng bản ghi thu thập theo hợp đồng đó.",
            "Feed doanh số trả HTTP 200 nhưng bỏ trường giá. Báo cáo có thể nạp response thành công mà vẫn mất thông tin số tiền. Data QA kiểm tra trường và kiểu trước khi tin feed; số tiền 0 đã biết là dữ liệu hợp lệ.",
            "Ba bản ghi tham chiếu (order_id, customer_id, net_amount): (10, 7, '10.01'), (20, 8, '0.00'), (30, 7, '7.00'). Response HTTP 200 có đủ ba bản ghi nhưng order 30 thiếu net_amount. Với checks trường bắt buộc/kiểu và status kỳ vọng 200: truyền tải SUCCESS, chất lượng FAIL, số đếm chẩn đoán nội bộ 1. Trường thiếu cũng sai check kiểu nhưng cùng bản ghi chỉ tính một lần. Bản ghi '0.00' đúng.",
            "Bắt đầu SANDBOX đang ACTIVE, chọn clean hoặc lỗi có tên. API test plan editor nhận JSON, không nhận SQL hay URL ngoài. Trước khi gửi, xem method, path, tùy chọn phân trang và checks; plan ban đầu chỉ kiểm tra status. Gửi HTTP & kiểm tra chạy plan với fixture local. Xem attempt cuối, body/header response và Bản ghi đã thu thập; so trường/kiểu với Order tham chiếu ở Source. Thêm checks phù hợp, gửi lại và so bằng chứng. Chất lượng hiển thị dùng checks của bạn nên PASS chỉ theo status có thể bỏ sót bản ghi sai. Bài API không có điều khiển batch/reset riêng. Nộp kiểm tra API chấm plan trên case độc lập; hint/reveal dùng điều khiển bài hiện có. Reveal/completion khóa gửi/nộp tiếp đến khi bắt đầu lượt mới.",
            "Nộp object JSON gồm tùy chọn request và object checks lồng bên trong theo challenge gốc bên trên. Chỉ có method/path GET /orders; page_size từ 1–5, paginate/ingest/idempotent là boolean, max_attempts từ 1–3, timeout_ms từ 50–300. checks có thể khai báo status, required (mảng tên trường) và types (object tên trường/kiểu); trường cho phép là order_id, customer_id, net_amount, kiểu là integer, decimal, string. Decimal ở đây là chuỗi số hữu hạn, không phải số JSON. Không nộp truy vấn SQL violation_count: executor tạo số chẩn đoán đó. Submission PASS nghĩa là số đếm khớp kỳ vọng sạch/lỗi độc lập ở mọi case; quality PASS tại chỗ chưa đủ. Plan sai định dạng trả lỗi validation. Câu trả lời được lưu, không được chấm tự động về nội dung.",
            "HTTP 200 và SUCCESS của executor chưa chứng minh bản ghi hợp lệ. JSON 7 khác '7'; true không phải integer ở đây. Không tính trường thiếu và kiểu sai thành hai bản ghi lỗi. Bài này so cấu trúc/kiểu, không chứng minh đủ key hay mọi giá trị trường chính xác.",
            "1. method GET và path /orders chọn endpoint fixture local cố định; page_size 2, paginate true thu thập các trang kế tiếp trong giới hạn mười trang.\n2. max_attempts 3, timeout_ms 150 giới hạn từng request; chỉ status của attempt cuối được xét nên retry phục hồi không thành lỗi status cuối. ingest false chỉ kiểm tra response trong bài này.\n3. checks.status yêu cầu 200 ở mỗi response cuối. checks.required liệt kê cả ba trường, bắt trường vắng hoặc NULL.\n4. checks.types yêu cầu ID integer và net_amount chuỗi decimal. Một dòng sai nhiều rule trường chỉ góp một chẩn đoán, không đếm theo rule.\n5. Ví dụ thiếu net_amount cho số đếm 1, quality FAIL dù truyền tải SUCCESS. Submission chạy cùng plan với kỳ vọng độc lập; reference là JSON dù panel reveal chung vẫn giữ nhãn solution hiện có.",
        ),
    },
}


GUIDANCE.update({
    "lab_020_api_pagination": {
        "ENG": (
            "Pagination splits a dataset into smaller response pages. next_page tells the client where to continue; NULL means the last page. Completeness means the collected order_id set matches the independent Reference Source orders. Uniqueness means each collected order_id appears once. Check both: matching total rows or HTTP 200 does not prove all expected keys arrived exactly once.",
            "A daily report reads only the first page of orders and silently omits later sales. Another feed repeats a key between pages. Data QA compares collected keys with the independent reference and counts duplicate key groups instead of trusting the response's total.",
            "Reference keys are [10, 20, 30]. With page_size 2, a correct response has page 1 items [10,20], next_page 2, then page 2 items [30], next_page NULL: diagnostic count 0. An incomplete HTTP 200 response instead returns [10,20], next_page NULL, total 2. complete detects missing key 30: transport SUCCESS, quality FAIL, diagnostic count 1. Separately, collecting [10,20,30,30] gives no missing keys but one duplicate group: count 1. The repeated 30 is one group, not two records counted as violations.",
            "Use the JSON API test plan editor in an active SANDBOX. Before sending, inspect page_size, paginate and checks. Send HTTP & test, then open HTTP response bodies and headers; inspect each page's items, next_page and the final attempt. Compare Collected records with Reference Source orders, not just total. Change page_size within 1–5 or turn paginate off to observe which records are collected, send again, and compare complete/unique results. The local starter checks only status, so a partial set can misleadingly show quality PASS under those checks. There are no separate Next page or Reset buttons: pagination is performed by the plan. Submit API test evaluates independent cases; reveal/completion locks execution until a new attempt.",
            "Submit a JSON request/check object, not SQL. method/path are GET /orders; page_size 1–5 and paginate control fetching; max_attempts 1–3 and timeout_ms 50–300 bound requests. Put expected status and completeness/uniqueness booleans in checks; checks.complete compares missing plus unexpected distinct order_id keys against api_expected, while checks.unique adds one per duplicated response-key group. Status adds one per final response that differs from expectation; recovered intermediate attempts do not count. The executor reports the internal count. Submission PASS requires matching independent counts on every clean/defective case, not simply returning zero in your sandbox. This contract compares keys, not customer/amount values. Your written answer is saved, not semantically graded.",
            "Do not trust total supplied by the same response you are testing, stop after a successful first page, or remove duplicates before checking uniqueness. Equal row counts can conceal different keys. A page is not one violation: missing/unexpected keys and duplicate groups determine the count.",
            "1. GET /orders with page_size 2 and paginate true follows next_page until NULL, with at most ten pages and bounded attempts per page.\n2. checks.status expects 200 for each final page response. Intermediate retries that recover do not add final-status violations.\n3. checks.complete builds distinct collected and reference key sets, adding missing and unexpected keys. The incomplete example lacks 30 and adds 1, even though its total agrees with its own items.\n4. checks.unique counts key groups appearing more than once in all collected records. The separate repeated-30 example adds 1.\n5. ingest false means no Target loading is required here. Add enabled diagnostics for the result; the plan is then evaluated on independent cases at submission. No check validates response total or next_page as a separate field contract.",
        ),
        "VIE": (
            "Pagination là chia tập dữ liệu thành các trang response nhỏ. next_page chỉ trang tiếp theo; NULL là trang cuối. Completeness nghĩa là tập order_id thu thập khớp Order tham chiếu ở Source độc lập. Uniqueness nghĩa là mỗi order_id thu thập chỉ xuất hiện một lần. Cần cả hai: bằng số dòng hoặc HTTP 200 chưa chứng minh mọi key kỳ vọng đã đến đúng một lần.",
            "Báo cáo ngày chỉ đọc trang order đầu và âm thầm bỏ doanh số các trang sau. Feed khác lặp key giữa các trang. Data QA so key thu thập với tham chiếu độc lập và đếm nhóm key trùng thay vì chỉ tin total của response.",
            "Key tham chiếu là [10, 20, 30]. Với page_size 2, response đúng có trang 1 items [10,20], next_page 2, rồi trang 2 items [30], next_page NULL: số đếm chẩn đoán 0. Response HTTP 200 thiếu lại trả [10,20], next_page NULL, total 2. complete bắt key 30 thiếu: truyền tải SUCCESS, chất lượng FAIL, số đếm 1. Riêng trường hợp thu thập [10,20,30,30] không thiếu key nhưng có một nhóm trùng: số đếm 1. Key 30 lặp là một nhóm, không phải hai bản ghi tính thành vi phạm.",
            "Dùng API test plan editor JSON trong SANDBOX đang ACTIVE. Trước khi gửi, xem page_size, paginate và checks. Gửi HTTP & kiểm tra rồi mở Body và header response HTTP; xem items, next_page từng trang và attempt cuối. So Bản ghi đã thu thập với Order tham chiếu ở Source, không chỉ total. Đổi page_size trong 1–5 hoặc tắt paginate để quan sát bản ghi thu được, gửi lại rồi so complete/unique. Plan ban đầu chỉ kiểm tra status nên tập thiếu có thể hiển thị quality PASS theo các checks đó. Không có nút Next page hay Reset riêng: plan thực hiện phân trang. Nộp kiểm tra API chấm case độc lập; reveal/completion khóa thực thi đến lượt mới.",
            "Nộp object JSON request/check, không phải SQL. method/path là GET /orders; page_size 1–5 và paginate điều khiển lấy trang; max_attempts 1–3, timeout_ms 50–300 giới hạn request. Đặt status kỳ vọng và boolean completeness/uniqueness trong checks; checks.complete cộng key order_id phân biệt thiếu/thừa so với api_expected, checks.unique cộng một cho mỗi nhóm response key trùng. Status cộng một cho mỗi response cuối khác kỳ vọng; attempt lỗi trung gian đã phục hồi không tính. Executor hiển thị số đếm nội bộ. Submission PASS cần khớp số đếm độc lập ở mọi case sạch/lỗi, không chỉ trả 0 trong sandbox. Hợp đồng so key, không so giá trị customer/amount. Câu trả lời được lưu, không được chấm tự động về nội dung.",
            "Không tin total do chính response đang kiểm tra cung cấp, dừng sau trang đầu thành công hay loại trùng trước khi kiểm tra uniqueness. Bằng số dòng có thể giấu key khác nhau. Một trang không phải một vi phạm: key thiếu/thừa và nhóm trùng quyết định số đếm.",
            "1. GET /orders với page_size 2, paginate true theo next_page đến NULL, tối đa mười trang và số attempt mỗi trang có giới hạn.\n2. checks.status kỳ vọng 200 cho response cuối mỗi trang. Retry trung gian phục hồi không góp lỗi status cuối.\n3. checks.complete lập tập key phân biệt thu thập/tham chiếu, cộng key thiếu và thừa. Ví dụ thiếu 30 góp 1 dù total khớp items của chính response.\n4. checks.unique đếm nhóm key xuất hiện nhiều hơn một lần trong mọi bản ghi thu thập. Ví dụ riêng lặp 30 góp 1.\n5. ingest false nên bài này không yêu cầu nạp Target. Cộng chẩn đoán được bật để ra kết quả; khi nộp plan được chạy trên case độc lập. Không có check riêng xác minh hợp đồng trường total hay next_page.",
        ),
    },
    "lab_021_api_retry": {
        "ENG": (
            "A retry repeats a request after a temporary failure. HTTP 429 indicates too many requests; 503 indicates temporary unavailability; timeout means no response arrived within the allowed wait. This local exercise retries these outcomes up to max_attempts total attempts per page, including the first send. Check recovery to final status 200 and complete collected keys; temporary failed attempts that later recover are evidence, not final defects.",
            "An order service briefly throttles requests. Never retrying loses orders; retrying forever can stall a reporting job. Data QA checks attempt limits, final outcomes and missing records separately. A program finishing its test is not proof the HTTP operation succeeded.",
            "Reference keys [10,20,30], page_size 2. In this local retry exercise each page can return 429, then 503, then 200. With max_attempts 3 and complete/status checks, two pages require 6 requests and collect all three keys: transport SUCCESS, quality PASS, diagnostic count 0. Set max_attempts 2: page 1 ends at 503, no items are collected and fetching stops. One final status defect plus three missing keys gives count 4 and transport FAILED/quality FAIL. Three timeouts on page 1 likewise give 1 + 3 = 4, not three final-status defects.",
            "In an active SANDBOX, inspect max_attempts and timeout_ms in the JSON editor before Send HTTP & test. Inspect the Page/Attempt/Status/Time/Final trace after sending; open headers for Retry-After and bodies for the error or items. Compare collected keys with Reference Source orders. Try a lower max_attempts then restore it and send again; a new send starts a new fixture invocation, not a continuation of the prior attempt sequence. Check permanent-failure or timeout evidence using available sandbox scenarios. There is no manual Retry or recovery button: the executor performs bounded retries within Send HTTP & test. Submit API test grades independent cases; reveal/completion locks execution until a new attempt. The simulator uses a short fixed retry pause, not a real provider backoff policy.",
            "Submit JSON request options and nested checks, not SQL. GET /orders is fixed; max_attempts is total attempts per page from 1–3, timeout_ms is 50–300, page_size is 1–5 and paginate is boolean. The required behavior is bounded recovery plus status/completeness checks under the original contract. Each final wrong-status response (including timeout's absent status) contributes 1; complete adds missing plus unexpected distinct keys. Earlier attempts that recovered add no final-status defect. Executor SUCCESS can coexist with HTTP execution FAILED. Submission PASS means counts match independent expectations across all cases, not that every defective case becomes quality PASS. Invalid plans are validation errors; execution/infrastructure errors are ERROR rather than invented data counts. Your written answer is saved, not semantically graded.",
            "max_attempts 3 means three sends total, not three retries after the first. Do not count every 429/503 as a final violation or consider recovery complete without checking records. Inspect Retry-After as evidence, but do not claim this simulator obeys it or models production retry timing.",
            "1. The reference uses GET /orders, page_size 2 and paginate true, so all available pages can be collected.\n2. max_attempts 3 allows the local 429 → 503 → 200 sequence on each page; timeout_ms 150 bounds each wait. Retryable outcomes are no response, 429 and 503. At most ten pages and three attempts/page means at most 30 requests.\n3. checks.status assesses only final responses; recovered intermediate attempts are retained in trace, not added to the count.\n4. checks.complete compares collected and independent expected key sets. A permanently failed first page leaves all illustrative three keys missing.\n5. The normal illustrative run gives 0 after 6 requests. Exhaustion/timeouts give one final-status defect plus three missing keys = 4. Submission judges whether the plan measures both clean and defective cases correctly, not whether it forces a 200.",
        ),
        "VIE": (
            "Retry là gửi lại request sau lỗi tạm thời. HTTP 429 báo quá nhiều request; 503 báo dịch vụ tạm không sẵn sàng; timeout là chưa có response trong thời gian chờ cho phép. Bài local này retry các kết quả đó đến tổng max_attempts lần mỗi trang, kể cả lần gửi đầu. Kiểm tra phục hồi đến status cuối 200 và đủ key thu thập; attempt lỗi tạm thời rồi phục hồi là bằng chứng, không phải lỗi cuối.",
            "Dịch vụ order tạm giới hạn request. Không retry làm mất order; retry vô hạn có thể treo job báo cáo. Data QA kiểm tra riêng giới hạn attempt, kết quả cuối và bản ghi thiếu. Chương trình chạy xong test chưa chứng minh thao tác HTTP thành công.",
            "Key tham chiếu [10,20,30], page_size 2. Trong bài retry local, mỗi trang có thể trả 429, rồi 503, rồi 200. max_attempts 3 cùng complete/status checks cần 6 request cho hai trang và thu đủ ba key: truyền tải SUCCESS, quality PASS, số đếm 0. Đặt max_attempts 2: trang 1 kết thúc bằng 503, không thu items và dừng lấy trang. Một lỗi status cuối cộng ba key thiếu cho số đếm 4, truyền tải FAILED/quality FAIL. Ba timeout ở trang 1 cũng cho 1 + 3 = 4, không phải ba lỗi status cuối.",
            "Trong SANDBOX đang ACTIVE, xem max_attempts và timeout_ms trong editor JSON trước khi Gửi HTTP & kiểm tra. Sau gửi, xem bảng Trang/Lần/Status/Thời gian/Cuối; mở header xem Retry-After, body xem lỗi hoặc items. So key thu thập với Order tham chiếu ở Source. Thử max_attempts thấp hơn rồi khôi phục giá trị và gửi lại; mỗi lần gửi tạo lần chạy fixture mới, không nối tiếp chuỗi attempt trước. Xem bằng chứng lỗi không phục hồi hoặc timeout qua scenario sandbox có sẵn. Không có nút Retry hay recovery thủ công: executor retry có giới hạn trong Gửi HTTP & kiểm tra. Nộp kiểm tra API chấm case độc lập; reveal/completion khóa thực thi đến lượt mới. Mô phỏng dùng khoảng nghỉ ngắn cố định, không phải chính sách backoff của provider thật.",
            "Nộp JSON tùy chọn request và checks lồng bên trong, không phải SQL. GET /orders cố định; max_attempts là tổng 1–3 attempt mỗi trang, timeout_ms từ 50–300, page_size từ 1–5, paginate là boolean. Hành vi cần kiểm tra là phục hồi có giới hạn cùng status/completeness theo hợp đồng gốc. Mỗi response cuối sai status (kể cả timeout không có status) góp 1; complete cộng key phân biệt thiếu/thừa. Attempt trước đã phục hồi không góp lỗi status cuối. Executor SUCCESS vẫn có thể đi cùng thực thi HTTP FAILED. Submission PASS nghĩa là số đếm khớp kỳ vọng độc lập mọi case, không phải mọi case lỗi trở thành quality PASS. Plan sai là lỗi validation; lỗi thực thi/hạ tầng là ERROR, không tự tạo số đếm lỗi dữ liệu. Câu trả lời được lưu, không được chấm tự động về nội dung.",
            "max_attempts 3 là tổng ba lần gửi, không phải ba retry sau lần đầu. Không tính mỗi 429/503 thành vi phạm cuối hay coi recovery hoàn tất khi chưa kiểm tra bản ghi. Xem Retry-After như bằng chứng, không khẳng định mô phỏng tuân theo header đó hoặc mô hình hóa thời gian retry production.",
            "1. Reference dùng GET /orders, page_size 2, paginate true để thu các trang có sẵn.\n2. max_attempts 3 cho phép chuỗi local 429 → 503 → 200 mỗi trang; timeout_ms 150 giới hạn từng lần chờ. Kết quả được retry là không có response, 429 và 503. Tối đa mười trang, ba attempt/trang tức tối đa 30 request.\n3. checks.status chỉ xét response cuối; attempt trung gian phục hồi được giữ trong trace, không cộng vào số đếm.\n4. checks.complete so tập key thu thập với kỳ vọng độc lập. Trang đầu lỗi không phục hồi làm thiếu cả ba key minh họa.\n5. Lần chạy minh họa bình thường cho 0 sau 6 request. Hết attempt/timeout cho một lỗi status cuối cộng ba key thiếu = 4. Submission xét plan đo đúng cả case sạch/lỗi, không xét việc ép response thành 200.",
        ),
    },
    "lab_022_api_ingestion": {
        "ENG": (
            "Ingestion means loading collected API records into storage. Here Reference Source orders in api_expected define the independent expectation, collected HTTP records are the response evidence, and PostgreSQL api_target is persisted Target. Replay applies the same collected batch again. Idempotency means repeating that batch keeps one intended row per order_id instead of appending extra copies. Check response keys and actual stored customer_id/exact money separately.",
            "A feed has correct HTTP status but a price is changed during delivery, or a replay duplicates stored orders. Data QA compares the database result with the reference: a valid response shape and a successful load do not prove correct persisted values.",
            "Reference rows (10,7,'10.01'), (20,8,'0.00'), (30,7,'7.00'). A complete HTTP 200 response contains these rows. With ingest true, idempotent true and response/Target checks, two automatic replays leave three Target rows and count 0. With idempotent false, the same response creates six Target rows (each key twice): response complete/unique checks pass, values match, but three duplicated Target-key groups give count 3. Separately, if response and Target both omit 30, complete contributes 1 and Target reconciliation contributes 1: count 2 for one missing key.",
            "Use the JSON editor in an active SANDBOX. Before Send HTTP & test, inspect ingest, idempotent and checks; the starter has ingest false and only status checks. After enabling ingestion and sending, inspect collected records, independent reference and PostgreSQL Target after two replays; compare keys, customer_id and exact net_amount, including zero. Try idempotent false in a sandbox, send, then restore true and send again to compare six-versus-three rows in the illustrative case. There is no separate replay button: each ingesting send applies its collected batch twice. Each new ingesting run starts a fresh Target; this demonstrates replay within one run, not incremental retention across runs. A non-ingesting send does not clear a previously stored Target. Query/submission history preserves evidence; grading uses rollback to retain your actual Target. Reveal/completion locks sends until a new attempt.",
            "Submit JSON with GET /orders, bounded page_size/max_attempts/timeout_ms, boolean paginate/ingest/idempotent, and nested checks. Use the original response completeness/uniqueness plus persisted reconciliation contract: complete compares missing/unexpected response keys; unique counts duplicate response-key groups; reconcile compares Target keys, customer_id and exact decimal amounts, then adds duplicate Target-key groups. One missing key can count at both response and Target layers. Several wrong fields on a reconciled key count once; a duplicate group counts once, not per excess row. The executor creates the diagnostic count; do not submit SQL. Submission PASS requires matching independent case counts, including clean and defective inputs. Written answers are saved, not semantically graded.",
            "Do not mistake Collected records for persisted Target, treat HTTP 200 as correct money, or assume a successful second send proves replay across runs. Idempotent upsert can hide duplicate response keys in Target, so response unique remains necessary. Reconciliation uses one final value per duplicate key plus a separate duplicate-group check; it does not inspect every duplicate member's value independently.",
            "1. GET /orders with paginate true/page_size 2 collects response pages; max_attempts 3 and timeout_ms 150 keep execution bounded.\n2. ingest true writes valid integer IDs and finite decimal-string amounts into real session api_target, clearing Target at the start of this run. The same collected records are applied twice automatically.\n3. idempotent true removes a stored row with the same order_id before inserting its current value, keeping one row per key. Exact PostgreSQL NUMERIC preserves cents.\n4. checks.status, complete and unique check final HTTP status and response key evidence. A duplicate response remains a defect even if Target upsert collapses it.\n5. checks.reconcile reads actual persisted Target, compares missing/unexpected keys and customer_id/net_amount with api_expected, and adds duplicated Target-key groups. The illustrative append run gives 3; the missing-30 case gives 1 response + 1 Target = 2.\n6. Submission reruns independent cases in rolled-back transactions, so grading evidence does not replace your sandbox Target. This local replay is not a production connector or proof of every prior execution.",
        ),
        "VIE": (
            "Ingestion là nạp bản ghi API đã thu thập vào nơi lưu trữ. Order tham chiếu ở Source trong api_expected định nghĩa kỳ vọng độc lập; bản ghi HTTP thu thập là bằng chứng response; PostgreSQL api_target là Target được lưu thật. Replay là áp dụng lại cùng batch đã thu thập. Idempotency nghĩa là lặp batch vẫn giữ một dòng đúng cho mỗi order_id, không append bản sao dư. Kiểm tra riêng key response và customer_id/số tiền chính xác trong database.",
            "Feed có HTTP status đúng nhưng giá bị đổi khi truyền, hoặc replay nhân đôi order đã lưu. Data QA so kết quả database với tham chiếu: cấu trúc response hợp lệ và load thành công chưa chứng minh giá trị được lưu đúng.",
            "Dòng tham chiếu (10,7,'10.01'), (20,8,'0.00'), (30,7,'7.00'). Response HTTP 200 đầy đủ chứa các dòng đó. ingest true, idempotent true cùng checks response/Target: hai replay tự động để lại ba dòng Target và số đếm 0. idempotent false làm cùng response tạo sáu dòng Target (mỗi key hai lần): complete/unique của response đúng, giá trị khớp, nhưng ba nhóm Target key trùng cho số đếm 3. Riêng nếu cả response và Target thiếu 30, complete góp 1, đối soát Target góp 1: số đếm 2 cho một key thiếu.",
            "Dùng editor JSON trong SANDBOX đang ACTIVE. Trước Gửi HTTP & kiểm tra, xem ingest, idempotent và checks; plan ban đầu ingest false và chỉ so status. Bật ingestion, gửi rồi xem bản ghi thu thập, tham chiếu độc lập và Target PostgreSQL sau hai lần replay; so key, customer_id, net_amount chính xác, kể cả 0. Thử idempotent false trong sandbox rồi bật lại true và gửi để so sáu với ba dòng trong ví dụ. Không có nút replay riêng: mỗi lần gửi có ingest áp dụng batch thu thập hai lần. Mỗi lần chạy ingest mới dựng Target mới; chỉ minh họa replay trong một lần chạy, không giữ tăng dần qua các lần chạy. Gửi không ingest không xóa Target đã lưu trước đó. Lịch sử query/submission giữ bằng chứng; grading rollback để giữ Target thực tế của bạn. Reveal/completion khóa gửi đến lượt mới.",
            "Nộp JSON gồm GET /orders, page_size/max_attempts/timeout_ms có giới hạn, boolean paginate/ingest/idempotent và checks lồng bên trong. Theo hợp đồng gốc, kiểm tra completeness/uniqueness response cùng đối soát lưu trữ: complete so key response thiếu/thừa; unique đếm nhóm response key trùng; reconcile so key Target, customer_id, số tiền decimal chính xác rồi cộng nhóm Target key trùng. Một key thiếu có thể được tính ở cả response và Target. Nhiều trường sai trên một key đối soát tính một lần; nhóm trùng tính một lần, không theo dòng dư. Executor tạo số đếm chẩn đoán; không nộp SQL. Submission PASS cần khớp số đếm độc lập cả đầu vào sạch/lỗi. Câu trả lời được lưu, không được chấm tự động về nội dung.",
            "Không nhầm Bản ghi đã thu thập với Target được lưu, coi HTTP 200 là tiền đúng hay cho rằng lần gửi thứ hai thành công chứng minh replay xuyên các lần chạy. Upsert idempotent có thể gộp key response trùng trong Target nên vẫn cần unique response. Reconcile dùng một giá trị cuối mỗi key trùng và check nhóm trùng riêng, không so độc lập giá trị từng thành viên trùng.",
            "1. GET /orders với paginate true/page_size 2 thu các trang response; max_attempts 3, timeout_ms 150 giới hạn thực thi.\n2. ingest true ghi ID integer và amount chuỗi decimal hữu hạn hợp lệ vào api_target thật của session, xóa Target lúc bắt đầu lần chạy này. Cùng bản ghi thu thập được áp dụng hai lần tự động.\n3. idempotent true xóa dòng đã lưu có cùng order_id trước khi ghi giá trị hiện tại, giữ một dòng mỗi key. NUMERIC PostgreSQL chính xác giữ phần cent.\n4. checks.status, complete, unique so status HTTP cuối và bằng chứng key response. Response trùng vẫn là lỗi dù upsert Target gộp bản sao.\n5. checks.reconcile đọc Target lưu thật, so key thiếu/thừa và customer_id/net_amount với api_expected rồi cộng nhóm Target key trùng. Ví dụ append cho 3; thiếu 30 cho 1 response + 1 Target = 2.\n6. Submission chạy lại case độc lập trong transaction rollback nên bằng chứng grading không thay Target sandbox. Replay local không phải connector production hay bằng chứng mọi thực thi trước đều đúng.",
        ),
    },
})


def apply_guidance(catalog):
    for lab_id, translations in GUIDANCE.items():
        for language, parts in translations.items():
            def section(index):
                return LABELS[language][index] + "\n" + parts[index]
            text = catalog[lab_id][language]
            text["theory"] = "\n\n".join(section(i) for i in (0, 1, 2, 3, 5))
            text["requirement"] += "\n\n" + section(4)
            text["explanation"] = section(6)
