"""Beginner guidance for the eight existing Fabric/ADF/OneLake evidence lessons."""

LABELS = {
    "ENG": ("What are we checking?", "Why does this matter?", "Small worked example — illustrative", "How to practice", "Challenge explained", "Common mistake", "Solution explained"),
    "VIE": ("Chúng ta đang kiểm tra gì?", "Vì sao điều này quan trọng?", "Ví dụ nhỏ — chỉ để minh họa", "Cách thực hành", "Giải thích thử thách", "Lỗi thường gặp", "Giải thích lời giải"),
}
SCOPE = {
    "ENG": "SIMULATED / IMPORTED evidence in local PostgreSQL. No live cloud connection, Microsoft service emulation, Spark/Delta execution, shortcut resolution or cloud authorization. ",
    "VIE": "Evidence SIMULATED / IMPORTED trong PostgreSQL local. Không kết nối cloud thật, giả lập dịch vụ Microsoft, chạy Spark/Delta, phân giải shortcut hay đánh giá quyền cloud. ",
}
IMPORT = {
    "ENG": "Import practice: in an ACTIVE SANDBOX open Import JSON/CSV evidence. Download evidence JSON is the existing version 1 template, with provider matching the course (Fabric, ADF or OneLake), resource_id, selected batch_no, timezone-aware as_of and reported runs/activities/steps/snapshots/schema/manifest/references. Missing selected batch or as_of stays UNKNOWN; missing metadata is not inferred. Steps are reported claims, not proof of local execution. JSON replaces observed evidence, never independent expected tables or grading truth.\nCSV is snapshots only, with the exact header dataset,order_id,customer_id,amount,updated_at,event_id,batch_no,run_id; dataset is source, bronze, silver or target. It supplies no selected batch/as-of context, so evidence/quality remains NOT_VERIFIED. File limit 48 KiB, request 64 KiB, 100 rows/dataset, 400 dataset rows total, 101 runs, 100 steps and 8 imports/session; other evidence arrays also have bounds. Export errors rather than dropping rows. After Validate and import, inspect IMPORTED provenance, retained filename/hash and evidence gaps; rerun QA. Reset is required before further simulator actions and retains the import audit trail. Paths/file keys are labels, never opened.",
    "VIE": "Thực hành import: trong ACTIVE SANDBOX mở Import evidence JSON/CSV. Tải evidence JSON là template version 1 hiện có, với provider khớp course (Fabric, ADF hoặc OneLake), resource_id, batch_no đang xét, as_of có múi giờ và run/activity/step/snapshot/schema/manifest/reference được báo. Batch đang xét hoặc as_of thiếu vẫn là UNKNOWN; không suy đoán metadata thiếu. Step là thông tin được báo, không chứng minh thực thi local. JSON thay evidence quan sát, không thay bảng kỳ vọng độc lập hay sự thật để chấm.\nCSV chỉ có snapshot, với header đúng dataset,order_id,customer_id,amount,updated_at,event_id,batch_no,run_id; dataset là source, bronze, silver hoặc target. CSV không cung cấp context batch/as-of đang xét nên evidence/quality vẫn NOT_VERIFIED. Giới hạn file 48 KiB, request 64 KiB, 100 dòng/dataset, tổng 400 dòng dataset, 101 run, 100 step và 8 import/session; các mảng evidence khác cũng có giới hạn. Export báo lỗi thay vì bỏ dòng. Sau Kiểm tra và import, xem provenance IMPORTED, tên file/hash đã lưu và evidence thiếu; chạy lại QA. Cần Đặt lại trước thao tác simulator tiếp theo; lịch sử import vẫn được giữ. Path/file key là nhãn, không được mở.",
}
CHALLENGE = {
    "ENG": "Return exactly one row with one non-negative integer column named violation_count, under the unchanged original contract above. Submission tests independent clean/fault expectations; imported evidence cannot redefine them. SQL execution ERROR is separate from a data-defect count. Your written answer is saved, not semantically graded. ",
    "VIE": "Trả đúng một dòng, một cột số nguyên không âm tên violation_count theo hợp đồng gốc không đổi bên trên. Submission chấm theo kỳ vọng sạch/lỗi độc lập; evidence import không được định nghĩa lại chúng. ERROR thực thi SQL khác số đếm lỗi dữ liệu. Câu trả lời được lưu, không được chấm tự động về nội dung. ",
}

GUIDANCE = {
    "lab_023_fabric_lineage": {
        "ENG": (
            "Microsoft Fabric brings analytics workflows together. This exercise only checks local run/activity evidence and published rows. Lineage means tracing where data came from. run_id identifies a run; activity_id identifies a step; dependency_id names a step that must already have succeeded in the same run. Check known links/states/dataset labels, dependency resolution and Target run links.",
            "A dashboard shows fresh sales but nobody can connect its orders to the load that produced them. Data QA uses run links and dependencies to investigate publication, rather than trusting the final SUCCESS badge.",
            "cloud_runs has R/SUCCESS. Activities: A in R, SUCCESS, source→bronze, no dependency; B in R, SUCCESS, NULL→target, dependency X (absent). Target has orders 10 in R and 20 in missing run Z. B contributes 1 for missing source_dataset and 1 for unresolved dependency; order 20 contributes 1 for its absent run. Expected violation_count = 3. B can violate two rules even though it says SUCCESS.",
            "Start an ACTIVE SANDBOX. Inspect Runs, Activities, dependency_id and Source/Target run_id before the practice query; join dependencies within the same run. Reset simulator reloads the selected scenario, rather than making every fault clean. Publish snapshots rebuilds data from visible Source, creates a local SUCCESS run/step and reassigns activity/Target run IDs; dependency IDs and dataset labels remain as evidence. Compare links and steps before/after, then rerun QA; a new publication need not fix a malformed dependency. Controls require ACTIVE SANDBOX; an import locks publication until Reset. Mutation invalidates the previous quality check.",
            "Add three counts: activities with absent run, UNKNOWN run/activity state or NULL source/target dataset; activities whose non-NULL dependency is absent or not SUCCESS in the same run; Target rows whose run_id is absent. A row counts once within a rule but may count in multiple rules. This check does not detect dependency cycles, independently validate every dataset value, or flag every FAILED activity/run merely for being FAILED. UNKNOWN is missing evidence, not success.",
            "Do not join dependencies by activity_id alone, count all Target rows because one run is unknown, or treat a zero diagnostic as proof every activity succeeded. Traceability and data correctness are different requirements.",
            "1. LEFT JOIN activities to runs USING(run_id) keeps activities even when their run is absent. WHERE selects missing runs, literal UNKNOWN states or NULL source/target labels; COUNT(*) counts that rule's rows.\n2. A second LEFT JOIN matches dependency_id to activity_id AND the same run_id. Non-NULL dependencies fail when missing or IS DISTINCT FROM SUCCESS.\n3. LEFT JOIN Target rows to runs and count only absent run links; this term does not assess the linked run's state.\n4. Add the three scalar counts. The example is 1 + 1 + 1 = 3; one activity contributes twice because two separate requirements fail.",
        ),
        "VIE": (
            "Microsoft Fabric tập hợp các luồng phân tích dữ liệu. Bài này chỉ kiểm tra evidence run/activity local và dòng đã publish. Lineage là truy vết nguồn gốc dữ liệu. run_id nhận diện lần chạy; activity_id nhận diện bước; dependency_id chỉ bước cần thành công trước trong cùng run. Kiểm tra liên kết/state/nhãn dataset đã biết, dependency có đối ứng và liên kết run của Target.",
            "Dashboard có doanh số mới nhưng không nối được order với đợt load tạo ra nó. Data QA dùng liên kết run và dependency để điều tra publication, không chỉ tin badge SUCCESS cuối.",
            "cloud_runs có R/SUCCESS. Activity A trong R, SUCCESS, source→bronze, không dependency; B trong R, SUCCESS, NULL→target, dependency X không tồn tại. Target có order 10 thuộc R và 20 thuộc run Z không có. B góp 1 vì thiếu source_dataset và 1 vì dependency không có; order 20 góp 1 vì thiếu run. Kết quả kỳ vọng violation_count = 3. B có thể sai hai quy tắc dù báo SUCCESS.",
            "Bắt đầu ACTIVE SANDBOX. Xem Runs, Activities, dependency_id và run_id Source/Target trước SQL thực hành; ghép dependency trong cùng run. Đặt lại simulator nạp lại scenario đã chọn, không làm mọi lỗi thành sạch. Publish snapshot dựng lại dữ liệu từ Source đang thấy, tạo run/step SUCCESS local và gán lại run ID cho activity/Target; dependency ID và nhãn dataset vẫn là evidence. So liên kết/steps trước-sau rồi chạy lại QA; publication mới chưa chắc sửa dependency sai. Điều khiển cần ACTIVE SANDBOX; import khóa publication đến khi Đặt lại. Thay đổi làm check chất lượng cũ hết hiệu lực.",
            "Cộng ba số: activity thiếu run, state run/activity UNKNOWN hoặc source/target dataset NULL; activity có dependency không NULL nhưng thiếu hoặc không SUCCESS trong cùng run; dòng Target thiếu run_id đối ứng. Một dòng tính một lần trong một rule nhưng có thể ở nhiều rule. Check không bắt chu trình dependency, không tự xác minh mọi giá trị dataset, không bắt mọi activity/run FAILED chỉ vì FAILED. UNKNOWN là thiếu bằng chứng, không phải thành công.",
            "Không ghép dependency chỉ bằng activity_id, đếm mọi dòng Target vì một run unknown hay coi số đếm 0 là mọi activity thành công. Truy vết và đúng dữ liệu là hai yêu cầu khác nhau.",
            "1. LEFT JOIN activity với run USING(run_id) giữ activity dù run thiếu. WHERE chọn run vắng, state UNKNOWN hoặc nhãn source/target NULL; COUNT(*) đếm dòng của rule đó.\n2. LEFT JOIN thứ hai ghép dependency_id với activity_id VÀ cùng run_id. Dependency không NULL sai khi thiếu hoặc IS DISTINCT FROM SUCCESS.\n3. LEFT JOIN Target với run, chỉ đếm liên kết run vắng; phần này không xét state của run đã liên kết.\n4. Cộng ba số đếm đơn. Ví dụ là 1 + 1 + 1 = 3; một activity góp hai lần vì sai hai yêu cầu riêng.",
        ),
    },
}


GUIDANCE.update({
    "lab_024_fabric_schema": {
        "ENG": (
            "Fabric integrates analytics workflows; this local exercise compares reported schema evidence, not a live Fabric table. A schema describes column names and data types. NUMERIC stores exact decimal amounts; float uses approximate numbers. Drift is a change away from the agreed contract. cloud_expected_schema is independent; cloud_schema is the reported observation. Check field identity, exact type labels and duplicate field groups.",
            "A provider changes an amount field from exact decimal to float. Current local rows can still look correct while the reported interface violates the agreed money contract. Data QA compares the declaration before trusting publication.",
            "Expected target fields: order_id/bigint, customer_id/bigint, amount/numeric(14,2). Reported fields: order_id/bigint, amount/float, debug/text. customer_id is missing (1), amount has wrong type (1), debug is unexpected (1); no field group repeats. Expected violation_count = 3. A column-name count of three on both sides would miss all three defects.",
            "Before actions, query cloud_expected_schema and cloud_schema; inspect Reported schema, manifest and references and run the practice FULL JOIN exploration. Reset simulator reloads the selected scenario. Publish snapshots rebuilds data and records local execution, but does not rewrite reported schema: a type defect can remain despite SUCCESS. Compare declared fields before/after and rerun QA. Imported type names are data, never executable DDL; independent expected schema cannot be supplied by import. Read the provenance and evidence-gap status separately.",
            "Count FULL JOIN rows with missing/unexpected dataset,column_name pairs or a different data_type string; add duplicate reported dataset/column groups. Several bad conditions on one joined row count once; duplicates are groups, not excess rows. Matching copies do not fail type comparison but still fail uniqueness. Type labels are compared exactly, not normalized as aliases. This check does not cast table data or validate its values.",
            "Do not infer provider schema from the local PostgreSQL column types, trust equal column counts, or accept float merely because the current amount is 10.00. Expected declarations and observed declarations are separate evidence.",
            "1. FULL JOIN cloud_expected_schema e and cloud_schema a USING(dataset,column_name) retains missing and unexpected fields.\n2. WHERE selects absent column names or e.data_type IS DISTINCT FROM a.data_type, including NULL differences; COUNT(*) counts failing joined rows.\n3. GROUP BY dataset,column_name with HAVING COUNT(*)>1 finds duplicate reported field groups. The outer COUNT counts groups, not extra copies.\n4. Add both counts. The example returns 3 + 0 = 3. A local NUMERIC table does not override a reported float label.",
        ),
        "VIE": (
            "Fabric tích hợp các luồng phân tích; bài local này so evidence schema được báo, không đọc bảng Fabric thật. Schema mô tả tên cột và kiểu dữ liệu. NUMERIC lưu số thập phân chính xác; float dùng số gần đúng. Drift là thay đổi lệch hợp đồng đã thống nhất. cloud_expected_schema là kỳ vọng độc lập; cloud_schema là quan sát được báo. Kiểm tra danh tính field, nhãn type chính xác và nhóm field trùng.",
            "Provider đổi amount từ decimal chính xác sang float. Dòng local hiện tại vẫn có thể đúng nhưng giao diện được báo đã sai hợp đồng số tiền. Data QA so khai báo trước khi tin publication.",
            "Field target kỳ vọng: order_id/bigint, customer_id/bigint, amount/numeric(14,2). Field được báo: order_id/bigint, amount/float, debug/text. Thiếu customer_id (1), amount sai type (1), debug thừa (1); không có nhóm field lặp. Kết quả kỳ vọng violation_count = 3. Cả hai phía đều ba tên cột vẫn giấu cả ba lỗi.",
            "Trước thao tác, truy vấn cloud_expected_schema và cloud_schema; xem Schema được báo, manifest và reference, chạy FULL JOIN khám phá của bài. Đặt lại simulator nạp lại scenario đã chọn. Publish snapshot dựng lại dữ liệu, ghi thực thi local nhưng không viết lại schema được báo: lỗi type vẫn có thể còn dù SUCCESS. So khai báo trước-sau rồi chạy lại QA. Tên type import là dữ liệu, không phải DDL được chạy; import không được cung cấp schema kỳ vọng độc lập. Xem provenance và trạng thái thiếu bằng chứng riêng.",
            "Đếm dòng FULL JOIN có cặp dataset,column_name thiếu/thừa hoặc chuỗi data_type khác; cộng nhóm dataset/column được báo trùng. Nhiều điều kiện sai trên một dòng ghép tính một lần; duplicate đếm nhóm, không đếm dòng dư. Bản sao khớp không sai type nhưng vẫn sai uniqueness. Nhãn type so chính xác, không chuẩn hóa alias. Check không cast dữ liệu bảng hay kiểm tra giá trị của nó.",
            "Không suy schema provider từ kiểu cột PostgreSQL local, tin bằng số cột hay chấp nhận float chỉ vì amount hiện bằng 10.00. Khai báo kỳ vọng và quan sát là bằng chứng riêng.",
            "1. FULL JOIN cloud_expected_schema e với cloud_schema a USING(dataset,column_name) giữ field thiếu và thừa.\n2. WHERE chọn tên cột vắng hoặc e.data_type IS DISTINCT FROM a.data_type, kể cả khác biệt NULL; COUNT(*) đếm dòng ghép sai.\n3. GROUP BY dataset,column_name, HAVING COUNT(*)>1 tìm nhóm field được báo trùng. COUNT ngoài đếm nhóm, không đếm bản sao dư.\n4. Cộng hai số. Ví dụ trả 3 + 0 = 3. Bảng NUMERIC local không ghi đè nhãn float được báo.",
        ),
    },
    "lab_025_fabric_layers": {
        "ENG": (
            "Fabric supports analytics workflows; Bronze/Silver/Gold are common layer names for input, refined and published data. This local lesson deliberately preserves the same order fields across layers to study reconciliation, not Spark/Delta transformations. Grain means what one row represents: Source has events, outputs require one latest visible row per order_id. Check three consecutive edges and output duplicate groups.",
            "A report retains three orders and the same revenue but replaces one key. Data QA checks identity and values at each handoff to locate where evidence diverges. Totals alone cannot establish correct layer publication.",
            "At batch 1/as_of 2026-02-03T12:00:00Z, Source has orders 10,20,30 with events 1,2,3, customer 7, amounts 10.01,0.00,7.00 and updated_at 2026-02-01T00:00:00Z. Bronze and Silver match. Target has 10,20,40; row 40 copies order 30's other fields. Source→Bronze = 0, Bronze→Silver = 0, Silver→Target = 2 (missing 30, unexpected 40), duplicate groups = 0. Expected violation_count = 2 despite equal counts/totals.",
            "Inspect cloud_context and cloud_source, then Source/Bronze/Silver/Gold snapshots before using the practice count/sum query. Those summaries are exploration only. Reset simulator reloads the selected scenario. Publish snapshots rebuilds all three outputs from currently visible Source with the clean publication policy and records a new local run/step. Compare keys and five checked fields at each edge before/after, not row positions; rerun QA because the old check is invalidated. Imported snapshots are observations, not proof a real layered pipeline executed.",
            "Apply Source batch_no <= context.batch_no and updated_at <= as_of before taking greatest event_id per order. Add failing FULL JOIN rows for Source→Bronze, Bronze→Silver, Silver→Target plus duplicate order-key groups in each output. Compare customer_id, amount, event_id and updated_at, not run_id/batch_no values directly. Counts are rule violations, not distinct bad orders; matching faults propagated between two downstream layers can be invisible on that edge. No transformation beyond this stated contract is inferred.",
            "Do not compare only Source/Target totals, rank by timestamp instead of event_id, or skip intermediate layers. Equal timestamps or older late timestamps do not reverse the implemented event ordering.",
            "1. The Source subquery filters arrival/as-of boundaries, then DISTINCT ON(order_id) with ORDER BY order_id,event_id DESC chooses each latest visible event.\n2. Each FULL JOIN aligns an edge by order_id; WHERE finds missing/unexpected keys or NULL-safe differences in customer_id, amount, event_id, updated_at. Each joined row counts once per edge.\n3. Three GROUP BY/HAVING queries count repeated order-key groups in Bronze, Silver and Target.\n4. Add all six diagnostics. The example gives 0 + 0 + 2 + 0 + 0 + 0 = 2. These checks do not establish real Fabric execution or every historical transition.",
        ),
        "VIE": (
            "Fabric hỗ trợ luồng phân tích; Bronze/Silver/Gold thường gọi lớp đầu vào, đã tinh chỉnh và đã publish. Bài local cố ý giữ cùng trường order giữa các lớp để học đối soát, không chạy biến đổi Spark/Delta. Grain là ý nghĩa một dòng: Source có event, đầu ra cần một dòng mới nhất đã đến cho mỗi order_id. Kiểm tra ba cạnh liên tiếp và nhóm đầu ra trùng.",
            "Báo cáo vẫn ba order và cùng doanh thu nhưng thay một key. Data QA so danh tính/giá trị ở mỗi điểm bàn giao để tìm nơi evidence lệch. Tổng số chưa chứng minh publication giữa lớp đúng.",
            "Batch 1/as_of 2026-02-03T12:00:00Z: Source có order 10,20,30, event 1,2,3, customer 7, amount 10.01,0.00,7.00, updated_at 2026-02-01T00:00:00Z. Bronze và Silver khớp. Target có 10,20,40; dòng 40 sao chép các trường khác của order 30. Source→Bronze = 0, Bronze→Silver = 0, Silver→Target = 2 (thiếu 30, thừa 40), nhóm trùng = 0. Kết quả kỳ vọng violation_count = 2 dù bằng count/tổng tiền.",
            "Xem cloud_context, cloud_source và snapshot Source/Bronze/Silver/Gold trước SQL count/sum thực hành. Tổng hợp đó chỉ để khám phá. Đặt lại simulator nạp lại scenario đã chọn. Publish snapshot dựng lại ba đầu ra từ Source hiện đã thấy theo chính sách publication sạch và ghi run/step local mới. So key và các trường được kiểm tra ở từng cạnh trước-sau, không theo vị trí dòng; chạy lại QA vì check cũ hết hiệu lực. Snapshot import là quan sát, không chứng minh pipeline nhiều lớp thật đã chạy.",
            "Lọc Source batch_no <= context.batch_no, updated_at <= as_of trước khi lấy event_id lớn nhất mỗi order. Cộng dòng FULL JOIN sai ở Source→Bronze, Bronze→Silver, Silver→Target và nhóm order key trùng mỗi đầu ra. So customer_id, amount, event_id, updated_at, không so trực tiếp run_id/batch_no. Tổng đếm vi phạm rule, không phải order lỗi duy nhất; lỗi giống nhau truyền qua hai lớp sau có thể không lộ ở cạnh đó. Không suy ra phép biến đổi ngoài hợp đồng.",
            "Không chỉ so tổng Source/Target, xếp theo timestamp thay event_id hay bỏ lớp giữa. Timestamp bằng nhau hoặc timestamp cũ của event muộn không đảo thứ tự event được implement.",
            "1. Truy vấn Source lọc biên arrival/as-of rồi DISTINCT ON(order_id), ORDER BY order_id,event_id DESC chọn event mới nhất đang thấy.\n2. Mỗi FULL JOIN ghép cạnh theo order_id; WHERE bắt key thiếu/thừa hoặc khác biệt customer_id, amount, event_id, updated_at bằng phép so xử lý NULL. Mỗi dòng ghép tính một lần mỗi cạnh.\n3. Ba truy vấn GROUP BY/HAVING đếm nhóm order key lặp ở Bronze, Silver, Target.\n4. Cộng sáu chẩn đoán. Ví dụ là 0 + 0 + 2 + 0 + 0 + 0 = 2. Check không chứng minh Fabric thật đã chạy hoặc mọi chuyển tiếp quá khứ.",
        ),
    },
    "lab_026_adf_copy": {
        "ENG": (
            "Azure Data Factory moves data and coordinates processing steps. This exercise reads local copy-activity evidence, not an ADF service. A metric is a reported measurement: rows_read/rows_written describe counts, not matching keys. Check actual latest visible Source/Target records, duplicated Target groups and activities publishing to target_dataset='target'.",
            "A nightly copy reports three rows read/written and SUCCESS while swapping one order key. Data QA reconciles the actual data independently and verifies whether activity metrics describe that snapshot.",
            "Source latest visible orders are 10,20,30 (customer 7, exact amounts 10.01,0.00,7.00, events 1,2,3). Target has 10,20,40, with 40 copying 30's other fields. One target activity is SUCCESS with rows_read=3, rows_written=3. Missing 30 + unexpected 40 = 2; duplicate groups 0, activity defects 0, activity gap 0. Expected violation_count = 2. Correct metrics cannot cancel wrong keys.",
            "Before actions, inspect cloud_context, visible Source, Target and the practice activity metrics query. Look at target_dataset, state and NULL measurements. Reset simulator restores the selected scenario. Publish snapshots rebuilds data using visible Source and updates activities to SUCCESS/current counts, adding a new run/step. Compare metrics and keyed data before/after, then rerun QA. A count-only query may PASS under your own checks without satisfying submission's complete independent contract.",
            "Add latest-visible Source/Target FULL JOIN differences, duplicated Target-key groups, one per target activity with any state/metric mismatch, and one if no target activity exists. rows_read must equal latest-visible Source count; rows_written must equal actual Target count. NULL is missing, not zero. Two wrong metrics/status in one activity add only 1. Non-target activities are outside this metric term; these totals do not prove every copy step or provider operation actually ran.",
            "Do not use rows_read=rows_written as proof of completeness, replace NULL with 0, or compare raw Source event count with the latest-order metric. A swapped key contributes missing plus unexpected, even when both counts match.",
            "1. Filter Source by selected batch/as_of, then DISTINCT ON chooses highest event_id per order. FULL JOIN Target counts missing/unexpected keys and checked-field differences.\n2. GROUP BY order_id/HAVING COUNT(*)>1 counts duplicated Target-key groups.\n3. Count cloud_activities targeting 'target' whose status IS DISTINCT FROM SUCCESS, rows_read differs from latest Source count or rows_written differs from Target count. OR means one count per activity.\n4. CASE/EXISTS adds one if no target activity exists. Add all terms: illustrative 2 + 0 + 0 + 0 = 2. UNKNOWN metrics do not become success.",
        ),
        "VIE": (
            "Azure Data Factory di chuyển dữ liệu và điều phối bước xử lý. Bài này đọc evidence copy activity local, không dùng dịch vụ ADF. Metric là phép đo được báo: rows_read/rows_written mô tả số lượng, chưa chứng minh key khớp. So Source/Target mới nhất đang thấy, nhóm Target trùng và activity có target_dataset='target'.",
            "Copy ban đêm báo ba dòng đọc/ghi và SUCCESS nhưng thay một order key. Data QA đối soát dữ liệu thật độc lập và kiểm tra metric activity có mô tả đúng snapshot đó không.",
            "Source mới nhất đang thấy có order 10,20,30 (customer 7, amount chính xác 10.01,0.00,7.00, event 1,2,3). Target có 10,20,40, dòng 40 sao chép trường khác của 30. Một activity đích SUCCESS, rows_read=3, rows_written=3. Thiếu 30 + thừa 40 = 2; nhóm trùng 0, lỗi activity 0, thiếu activity 0. Kết quả kỳ vọng violation_count = 2. Metric đúng không bù được key sai.",
            "Trước thao tác, xem cloud_context, Source đang thấy, Target và SQL metric activity thực hành. Xem target_dataset, state, phép đo NULL. Đặt lại simulator khôi phục scenario đã chọn. Publish snapshot dựng lại dữ liệu từ Source đang thấy, cập nhật activity SUCCESS/count hiện tại và thêm run/step mới. So metric/dữ liệu theo key trước-sau rồi chạy lại QA. Query chỉ đếm số dòng có thể PASS theo check của bạn nhưng chưa đạt hợp đồng độc lập đầy đủ khi nộp.",
            "Cộng dòng FULL JOIN Source/Target mới nhất sai, nhóm Target key trùng, một cho mỗi activity đích có bất kỳ state/metric sai và một nếu không có activity đích. rows_read cần bằng count Source mới nhất; rows_written bằng count Target thật. NULL là thiếu, không phải 0. Hai metric/status sai trên một activity chỉ góp 1. Activity không đến target ngoài phần metric này; tổng không chứng minh từng bước copy hay thao tác provider thực sự đã chạy.",
            "Không coi rows_read=rows_written là đủ dữ liệu, thay NULL bằng 0 hay so count event Source thô với metric order mới nhất. Key bị thay góp thiếu và thừa dù count hai phía khớp.",
            "1. Lọc Source theo batch/as_of đang xét rồi DISTINCT ON chọn event_id lớn nhất mỗi order. FULL JOIN Target đếm key thiếu/thừa và trường khác biệt.\n2. GROUP BY order_id/HAVING COUNT(*)>1 đếm nhóm Target key trùng.\n3. Đếm cloud_activities đến 'target' có status IS DISTINCT FROM SUCCESS, rows_read khác count Source mới nhất hoặc rows_written khác count Target. OR làm mỗi activity tính một lần.\n4. CASE/EXISTS cộng một nếu không có activity đích. Cộng các phần: ví dụ 2 + 0 + 0 + 0 = 2. Metric UNKNOWN không trở thành thành công.",
        ),
    },
})


GUIDANCE.update({
    "lab_027_adf_watermark": {
        "ENG": (
            "ADF coordinates data movement; a watermark is a saved processing boundary used to decide what to load next. This local exercise separates arrival batches from event timestamps. A late event can have an older updated_at but higher event_id. Visibility needs both arrived batch and the fixed UTC as_of boundary; latest means greatest eligible event_id, not greatest timestamp. Replay republishes visible data; idempotency means repeating it keeps the intended one-row-per-key output.",
            "A corrected sale arrives after a watermark has advanced, but carries yesterday's update time. A timestamp-only policy skips it. Data QA checks late arrival, the exact UTC boundary and duplicates after replay rather than trusting copy SUCCESS.",
            "Context batch 2, as_of 2026-02-03T12:00:00Z. Source events: order10/event1/batch1/Feb2/net10.00; order10/event2/batch2/Feb1/net12.00 (late older time); order20/event3/batch2/exact as_of/net0.00; order30/event4/batch2/as_of+1 second/net7.00. All customers are 7. Target retains order10/event1 and correct order20/event3. Expected order10 is event2; order20 is eligible at the exact boundary; order30 is future and excluded. Expected violation_count = 1 for the stale order10 row, with no duplicate group.",
            "Inspect context, Source events and Target before actions; the practice query shows event/batch/time, not a full check. Reset simulator clears publication/steps to batch 0 for this lesson, reloads its selected fixture and preserves import audit records. Next batch advances up to batch 3 then republishes eligible events; Replay batch republishes without advancing. Compare current batch, event_id, exact amounts, UTC boundary and key groups before/after each action; inspect run/step evidence and rerun QA. Clean replay retains one row per key; the chosen faulty policy may still skip late/boundary events or duplicate publication. After import, Reset is required to use simulator controls. A final snapshot cannot prove every earlier action was correct.",
            "Filter batch_no <= context.batch_no AND updated_at <= as_of before selecting greatest event_id per order. Add failing FULL JOIN Source/Target rows and duplicated Target order-key groups. Missing/unexpected keys and NULL-safe customer_id, amount, event_id, updated_at differences count once per joined row; repeated identical latest rows can have zero mismatch but one duplicate group. The query does not compare run_id/batch_no values directly or prove stored watermark correctness/history. If context is unknown, do not infer it from snapshot rows.",
            "Do not filter on event timestamp alone, use < at the inclusive as_of boundary, or rank future events before filtering. A bigger event_id is only eligible after arrival and before/equal to as_of. Replay SUCCESS is not proof of idempotency.",
            "1. Source WHERE applies both inclusive batch and UTC time boundaries. DISTINCT ON(order_id), ORDER BY order_id,event_id DESC chooses the greatest visible event.\n2. FULL JOIN Target by order_id retains missing/unexpected keys and compares the four checked fields with IS DISTINCT FROM. Multiple field defects on one joined row count once.\n3. GROUP BY order_id with HAVING COUNT(*)>1 finds duplicate Target-key groups; the outer count measures groups.\n4. Add mismatch rows and groups. The illustrative late update is eligible despite its older timestamp: 1 + 0 = 1. The future event is not an expected missing key.",
        ),
        "VIE": (
            "ADF điều phối di chuyển dữ liệu; watermark là ranh giới xử lý đã lưu để quyết định lần nạp tiếp. Bài local tách batch đến khỏi timestamp event. Event muộn có thể updated_at cũ hơn nhưng event_id lớn hơn. Visibility cần cả batch đã đến và biên as_of UTC cố định; mới nhất là event_id lớn nhất hợp lệ, không phải timestamp lớn nhất. Replay publish lại dữ liệu đang thấy; idempotency là lặp vẫn giữ đầu ra đúng một dòng mỗi key.",
            "Bản sửa giao dịch đến sau khi watermark đã tiến nhưng mang thời gian cập nhật hôm qua. Chính sách chỉ theo timestamp bỏ mất nó. Data QA so late arrival, đúng biên UTC và duplicate sau replay, không chỉ tin copy SUCCESS.",
            "Context batch 2, as_of 2026-02-03T12:00:00Z. Source: order10/event1/batch1/Feb2/net10.00; order10/event2/batch2/Feb1/net12.00 (muộn, thời gian cũ); order20/event3/batch2/đúng as_of/net0.00; order30/event4/batch2/as_of+1 giây/net7.00. Mọi customer là 7. Target giữ order10/event1 và order20/event3 đúng. Order10 kỳ vọng là event2; order20 hợp lệ đúng biên; order30 ở tương lai nên bị loại. Kết quả kỳ vọng violation_count = 1 vì dòng order10 cũ, không có nhóm trùng.",
            "Xem context, event Source, Target trước thao tác; SQL thực hành hiển thị event/batch/time, chưa là check đầy đủ. Đặt lại simulator xóa publication/steps về batch 0 cho bài này, nạp lại fixture đã chọn và giữ lịch sử import. Batch tiếp tăng đến tối đa batch 3 rồi publish event hợp lệ; Replay batch publish lại mà không tăng batch. So batch hiện tại, event_id, tiền chính xác, biên UTC và nhóm key trước-sau mỗi thao tác; xem run/step rồi chạy lại QA. Replay sạch giữ một dòng mỗi key; policy lỗi đã chọn vẫn có thể bỏ event muộn/đúng biên hoặc publish trùng. Sau import cần Đặt lại để dùng simulator. Snapshot cuối không chứng minh mọi thao tác trước đều đúng.",
            "Lọc batch_no <= context.batch_no VÀ updated_at <= as_of trước khi chọn event_id lớn nhất mỗi order. Cộng dòng FULL JOIN Source/Target sai và nhóm Target order key trùng. Key thiếu/thừa và khác biệt customer_id, amount, event_id, updated_at xử lý NULL tính một lần mỗi dòng ghép; bản sao giống phiên bản mới nhất có thể không mismatch nhưng góp một nhóm trùng. Query không so trực tiếp run_id/batch_no hay chứng minh watermark đã lưu/lịch sử đúng. Context unknown thì không suy từ dòng snapshot.",
            "Không chỉ lọc timestamp event, dùng < ở biên as_of bao gồm đúng mốc hay xếp event tương lai trước khi lọc. Event_id lớn hơn chỉ hợp lệ sau khi đến và trước/bằng as_of. Replay SUCCESS chưa chứng minh idempotency.",
            "1. WHERE Source áp dụng hai biên batch và giờ UTC bao gồm đúng mốc. DISTINCT ON(order_id), ORDER BY order_id,event_id DESC chọn event lớn nhất đang thấy.\n2. FULL JOIN Target theo order_id giữ key thiếu/thừa, so bốn trường bằng IS DISTINCT FROM. Nhiều trường sai trên một dòng ghép tính một lần.\n3. GROUP BY order_id, HAVING COUNT(*)>1 tìm nhóm Target key trùng; COUNT ngoài đếm nhóm.\n4. Cộng mismatch và nhóm. Update muộn trong ví dụ hợp lệ dù timestamp cũ: 1 + 0 = 1. Event tương lai không phải key kỳ vọng bị thiếu.",
        ),
    },
    "lab_028_adf_recovery": {
        "ENG": (
            "ADF coordinates dependent steps; recovery means publishing again after interruption. Here local activities, current Target and cloud_steps supply separate evidence. A checkpoint is the step's recorded batch; it must match cloud_context.batch_no. Check data reconciliation, all current non-SUCCESS activities, and the greatest step_no's state/checkpoint. This does not execute real ADF dependencies.",
            "A failed upstream step is followed by a seemingly successful publication with a missing order. Data QA checks current activity evidence and actual Target, not only the latest job badge. Older failed run records can remain as history without making the latest publication incorrect by themselves.",
            "At context batch 1 with known UTC as_of, Source latest orders 10,20,30 have amounts 10.01,0.00,7.00 and Target contains only correct 10,20. Two current activities: A FAILED, B SUCCESS. Latest step 2 is FAILED with batch_no 0. Missing order30 adds 1; activity A adds 1; latest step adds 1 even though both state and checkpoint fail. Expected violation_count = 3. A separate older FAILED cloud_runs record adds nothing by itself.",
            "Before recovery inspect Target, all Activities and cloud_steps via the practice query. Reset simulator reloads the selected scenario and its initial step; it does not always produce an empty or clean workspace. Recover publication rebuilds outputs using clean visible-Source publication, marks current activities SUCCESS, links a new local run and records the current batch checkpoint. Compare data, activity states and greatest step_no before/after, rerun QA, then recover again to inspect repeated output and new step. Existing older run records remain; current activity evidence is reassigned, not an immutable history of every activity transition. Imports report step claims only. Simulator stops at 100 steps until Reset.",
            "Add Source/Target joined differences, Target duplicate groups, one per current activity IS DISTINCT FROM SUCCESS, and one if the latest step is absent/non-SUCCESS or its batch differs from context. Latest-step problems together add 1, not one per field. All activity rows in cloud_activities are checked; the SQL does not filter them to the latest run. Historical failed run rows alone are not counted. Missing step is a real evidence-gap term here; this differs from the older ETL recovery contract. A final snapshot/checkpoint does not prove all earlier dependencies executed correctly.",
            "Do not count every old FAILED run, assume SUCCESS checkpoint means complete data, or discard current failed activities just because a newer step succeeded. Data, activity and checkpoint diagnostics can all apply to the same publication.",
            "1. Latest-visible Source is reconciled to Target by order_id and the four checked fields; FULL JOIN counts missing/unexpected or mismatched rows.\n2. GROUP BY/HAVING adds duplicated Target-key groups.\n3. Count every cloud_activities row whose execution_status IS DISTINCT FROM SUCCESS, including NULL/UNKNOWN.\n4. The final scalar subquery reads ORDER BY step_no DESC LIMIT 1, requiring SUCCESS AND a batch matching context. CASE accepts only IS TRUE; absent/NULL/failed/wrong checkpoint adds 1.\n5. Sum all terms. Example: 1 missing row + 0 duplicate groups + 1 activity + 1 latest-step rule = 3. No term checks cloud_runs history directly.",
        ),
        "VIE": (
            "ADF điều phối bước phụ thuộc; recovery là publish lại sau gián đoạn. Activity local, Target hiện tại và cloud_steps là bằng chứng riêng. Checkpoint là batch được step ghi nhận, cần khớp cloud_context.batch_no. Kiểm tra đối soát dữ liệu, mọi activity hiện không SUCCESS, state/checkpoint của step_no lớn nhất. Không chạy dependency ADF thật.",
            "Bước upstream lỗi rồi có publication tưởng thành công nhưng thiếu order. Data QA xem evidence activity hiện tại và Target thật, không chỉ badge job cuối. Run FAILED cũ có thể giữ như lịch sử mà tự nó không làm publication mới sai.",
            "Context batch 1, as_of UTC đã biết: Source mới nhất có order 10,20,30, amount 10.01,0.00,7.00; Target chỉ có 10,20 đúng. Hai activity hiện tại: A FAILED, B SUCCESS. Step 2 mới nhất FAILED, batch_no 0. Thiếu order30 góp 1; activity A góp 1; step mới nhất góp 1 dù state/checkpoint đều sai. Kết quả kỳ vọng violation_count = 3. Một dòng cloud_runs FAILED cũ riêng không tự góp lỗi.",
            "Trước khôi phục xem Target, mọi Activities và cloud_steps bằng SQL thực hành. Đặt lại simulator nạp lại scenario/step ban đầu, không luôn tạo workspace rỗng hay sạch. Khôi phục publication dựng lại đầu ra theo publication Source hợp lệ sạch, đánh activity hiện tại SUCCESS, nối run local mới và ghi checkpoint batch hiện tại. So dữ liệu/state activity/step_no lớn nhất trước-sau, chạy lại QA rồi khôi phục lần nữa để xem đầu ra lặp và step mới. Run cũ giữ lại; evidence activity hiện được gán lại, không phải lịch sử bất biến từng chuyển trạng thái activity. Import chỉ báo thông tin step. Simulator dừng ở 100 step đến khi Đặt lại.",
            "Cộng dòng ghép Source/Target sai, nhóm Target trùng, một cho mỗi activity hiện IS DISTINCT FROM SUCCESS và một nếu step cuối thiếu/không SUCCESS hoặc batch khác context. Các lỗi step cuối cùng góp 1, không theo trường. Mọi dòng cloud_activities được xét; SQL không giới hạn chúng theo run mới nhất. Run FAILED lịch sử riêng không bị đếm. Thiếu step là phần thiếu evidence thật ở bài này, khác contract recovery ETL cũ. Snapshot/checkpoint cuối không chứng minh mọi dependency trước đã thực thi đúng.",
            "Không đếm mọi run FAILED cũ, coi checkpoint SUCCESS là đủ dữ liệu hay bỏ activity hiện lỗi vì step mới thành công. Chẩn đoán dữ liệu/activity/checkpoint có thể cùng áp dụng một publication.",
            "1. Source mới nhất đang thấy được đối soát Target theo order_id/bốn trường; FULL JOIN đếm dòng thiếu/thừa hoặc sai giá trị.\n2. GROUP BY/HAVING cộng nhóm Target key trùng.\n3. Đếm mọi dòng cloud_activities có execution_status IS DISTINCT FROM SUCCESS, kể cả NULL/UNKNOWN.\n4. Truy vấn đơn cuối đọc ORDER BY step_no DESC LIMIT 1, yêu cầu SUCCESS VÀ batch khớp context. CASE chỉ nhận IS TRUE; thiếu/NULL/lỗi/sai checkpoint góp 1.\n5. Cộng mọi phần. Ví dụ 1 dòng thiếu + 0 nhóm trùng + 1 activity + 1 rule step cuối = 3. Không phần nào xét trực tiếp lịch sử cloud_runs.",
        ),
    },
    "lab_029_onelake_partitions": {
        "ENG": (
            "OneLake is Fabric's shared logical data lake. Here only a local manifest is examined, not actual lake files. A partition groups data, often by UTC day; a manifest lists file labels and represented row counts. cloud_expected_partitions independently states required partitions/counts. Check aggregate coverage and repeated file_key groups, not file existence through a live listing.",
            "A daily file is listed twice while another day's partition never appears. A report can look complete by file count yet omit a day. Data QA compares represented rows and partition keys against independent requirements.",
            "Expected partitions: P1 has 3 rows, P2 has 2. Manifest rows: (P1,F1,1), (P1,F1,1), (P1,F2,1). P1 sums to 3 and matches; P2 is missing (1); F1 forms one duplicate group (1). Expected violation_count = 2. There are three listed file rows but only two file labels, and this score does not count each duplicate copy.",
            "Inspect cloud_expected_partitions and cloud_manifest before the practice grouping query; open Reported schema, manifest and references. Compare partition_key, file_key, row_count, snapshot_at and provenance. Reset simulator reloads the selected scenario. Publish snapshots refreshes order publication/run evidence but does not rebuild manifest rows, so a manifest defect can remain despite execution SUCCESS. After JSON import inspect the replaced manifest and evidence gaps; CSV supplies order snapshots only and cannot supply manifest/context. Query partition totals and duplicate groups again after relevant changes.",
            "Group manifest by partition_key and SUM(row_count); count missing/unexpected or mismatching partition groups once, then add duplicated file_key groups across the manifest. A file repeated can fail both sum and uniqueness, or only uniqueness if the sum still matches. SQL does not inspect file contents, resolve labels, or check snapshot_at/run_id. Existing limitation: SUM ignores individual NULL values; an all-NULL group fails known totals, but a partly unknown group can sum to the expected total and score 0 on that term. Evidence status still flags NULL row counts/snapshot times as NOT_VERIFIED; do not turn that into a PASS claim.",
            "Do not confuse number of files with represented rows, count duplicate members instead of groups, or use a matching partial SUM to claim unknown file counts are known. Missing evidence and SQL diagnostic results are separate.",
            "1. GROUP BY partition_key builds one manifest aggregate per partition, with SUM(row_count).\n2. FULL JOIN aggregates to cloud_expected_partitions retains missing and unexpected partitions; WHERE uses IS DISTINCT FROM to find unequal totals, including a NULL aggregate.\n3. GROUP BY file_key/HAVING COUNT(*)>1 identifies duplicated file-label groups; the outer COUNT counts groups.\n4. Add partition differences and duplicates. The example is 1 missing P2 + 1 repeated F1 group = 2. SUM's NULL behavior is why a zero diagnostic alone does not establish complete evidence.",
        ),
        "VIE": (
            "OneLake là data lake logic dùng chung của Fabric. Bài này chỉ xem manifest local, không đọc file lake thật. Partition nhóm dữ liệu, thường theo ngày UTC; manifest liệt kê nhãn file và số dòng được đại diện. cloud_expected_partitions định nghĩa độc lập partition/count cần có. Kiểm tra tổng bao phủ và nhóm file_key lặp, không xác minh file tồn tại qua listing thật.",
            "Một file ngày bị liệt kê hai lần trong khi partition ngày khác không xuất hiện. Báo cáo nhìn như đủ theo số file nhưng thiếu ngày. Data QA so số dòng đại diện và partition key với yêu cầu độc lập.",
            "Partition kỳ vọng: P1 có 3 dòng, P2 có 2. Manifest: (P1,F1,1), (P1,F1,1), (P1,F2,1). P1 tổng 3 khớp; thiếu P2 (1); F1 tạo một nhóm trùng (1). Kết quả kỳ vọng violation_count = 2. Có ba dòng file được liệt kê nhưng chỉ hai nhãn file; điểm không đếm từng bản sao trùng.",
            "Xem cloud_expected_partitions và cloud_manifest trước SQL nhóm thực hành; mở Schema được báo, manifest và reference. So partition_key, file_key, row_count, snapshot_at và provenance. Đặt lại simulator nạp lại scenario đã chọn. Publish snapshot cập nhật publication order/run nhưng không dựng lại manifest, nên lỗi manifest vẫn còn dù thực thi SUCCESS. Sau JSON import xem manifest bị thay và evidence thiếu; CSV chỉ có snapshot order, không cung cấp manifest/context. Truy vấn lại tổng partition và nhóm trùng sau thay đổi liên quan.",
            "Nhóm manifest theo partition_key, SUM(row_count); đếm nhóm partition thiếu/thừa/sai tổng một lần rồi cộng nhóm file_key trùng toàn manifest. File lặp có thể sai cả tổng và uniqueness, hoặc chỉ uniqueness nếu tổng vẫn khớp. SQL không đọc nội dung file, phân giải nhãn hay kiểm tra snapshot_at/run_id. Giới hạn hiện có: SUM bỏ qua từng NULL; nhóm toàn NULL sai tổng đã biết, nhưng nhóm thiếu một phần có thể cộng đúng tổng và phần đó trả 0. Evidence status vẫn đánh row_count/snapshot time NULL là NOT_VERIFIED; không biến thành kết luận PASS.",
            "Không nhầm số file với số dòng đại diện, đếm thành viên trùng thay nhóm hay dùng SUM phần đã biết khớp để khẳng định count file thiếu đã biết. Thiếu evidence và kết quả chẩn đoán SQL là hai điều riêng.",
            "1. GROUP BY partition_key tạo một tổng manifest mỗi partition bằng SUM(row_count).\n2. FULL JOIN tổng với cloud_expected_partitions giữ partition thiếu/thừa; WHERE dùng IS DISTINCT FROM tìm tổng khác, kể cả tổng NULL.\n3. GROUP BY file_key/HAVING COUNT(*)>1 tìm nhóm nhãn file lặp; COUNT ngoài đếm nhóm.\n4. Cộng khác biệt partition và duplicate. Ví dụ 1 P2 thiếu + 1 nhóm F1 lặp = 2. Cách SUM xử lý NULL là lý do số đếm 0 chưa chứng minh evidence đầy đủ.",
        ),
    },
    "lab_030_onelake_freshness": {
        "ENG": (
            "OneLake supports shared analytical data; this local exercise checks referenced-dataset observations, not real shortcuts. A reference identifies a dataset/source link. Freshness is its age at a fixed UTC as_of clock; SLA minutes is the maximum permitted age. Match required and observed dataset_id/reference_id pairs, then check missing time, future time or age strictly beyond the allowed interval.",
            "A successful report uses stale product reference data. Data QA checks the observation timestamp and expected reference identity instead of assuming the latest pipeline run refreshed every input.",
            "as_of is 2026-02-03T12:00:00Z. Required references A,B,C,D each allow 60 minutes. Observed: A at 11:00:00 (exact boundary, passes), B at 10:59:59.999999 (one microsecond stale), C with NULL time, D missing, plus unexpected X at 11:00. B,C,D,X each count once. Expected violation_count = 4. A future timestamp also fails; it is not extra-fresh evidence.",
            "Before actions inspect cloud_context, cloud_required_references and cloud_references; the practice query shows observation age but does not include absent required references. Open Reported schema, manifest and references and check provenance. Reset simulator restores the selected scenario. Publish snapshots records new order publication but does not refresh observed_at reference times, so stale evidence remains stale at the same fixed as_of. After JSON import check selected UTC as_of and observed reference IDs/times, then rerun QA. CSV cannot provide references or selected clock; NOT_VERIFIED must remain distinct from correctness. No control resolves an actual shortcut.",
            "Count FULL JOIN reference rows with missing/unexpected identity, NULL observed_at, observed_at>as_of or age>SLA. One joined row counts once even if several conditions hold. Exactly SLA minutes passes; one microsecond older fails. Use fixed context, not NOW(). No duplicate-group term exists here; duplicate matching observations can multiply joined rows. The check does not validate linked run status, real shortcut targets, file contents or authorization. Unknown clock/required evidence cannot be invented to establish freshness.",
            "Do not use >= at the inclusive freshness threshold, treat a future time as fresh, or INNER JOIN away missing observations. A recent pipeline run is different evidence from a recent reference observation.",
            "1. FULL JOIN cloud_required_references e and cloud_references a USING(dataset_id,reference_id) preserves missing/unexpected pairs.\n2. CROSS JOIN the single cloud_context c supplies the fixed as_of boundary to every pair.\n3. WHERE selects absent identities, NULL observed_at, future time or c.as_of-a.observed_at greater than e.sla_minutes * INTERVAL '1 minute'. The strict > lets exactly 60 minutes pass.\n4. COUNT(*) counts selected joined rows once. Illustrative B,C,D,X give 4 while A passes. A NULL clock is an evidence gap, not a reason to assert all observations are fresh.",
        ),
        "VIE": (
            "OneLake hỗ trợ dùng chung dữ liệu phân tích; bài local kiểm tra observation dataset tham chiếu, không dùng shortcut thật. Reference nhận diện liên kết dataset/nguồn. Freshness là tuổi observation tại đồng hồ as_of UTC cố định; SLA minutes là tuổi tối đa cho phép. Ghép cặp dataset_id/reference_id bắt buộc/đã quan sát rồi xét thời gian thiếu, tương lai hoặc tuổi vượt giới hạn.",
            "Báo cáo thành công dùng dữ liệu sản phẩm tham chiếu đã cũ. Data QA xem timestamp observation và danh tính reference kỳ vọng, không cho rằng run pipeline mới nhất đã refresh mọi đầu vào.",
            "as_of là 2026-02-03T12:00:00Z. Reference A,B,C,D bắt buộc đều cho phép 60 phút. Quan sát A lúc 11:00:00 (đúng biên, đạt), B lúc 10:59:59.999999 (cũ hơn một microsecond), C thời gian NULL, D thiếu, thêm X không được yêu cầu lúc 11:00. B,C,D,X tính một lần mỗi dòng. Kết quả kỳ vọng violation_count = 4. Timestamp tương lai cũng sai, không phải evidence mới hơn tốt hơn.",
            "Trước thao tác xem cloud_context, cloud_required_references, cloud_references; SQL thực hành cho tuổi observation nhưng không có reference bắt buộc bị thiếu. Mở Schema được báo, manifest và reference, xem provenance. Đặt lại simulator khôi phục scenario đã chọn. Publish snapshot ghi publication order mới nhưng không refresh observed_at của reference nên evidence cũ vẫn cũ ở cùng as_of cố định. Sau JSON import xem as_of UTC đang xét và ID/time reference quan sát rồi chạy lại QA. CSV không cung cấp reference hay đồng hồ đang xét; NOT_VERIFIED cần khác dữ liệu đúng. Không có điều khiển phân giải shortcut thật.",
            "Đếm dòng FULL JOIN reference thiếu/thừa danh tính, observed_at NULL, observed_at>as_of hoặc tuổi>SLA. Một dòng ghép tính một lần dù nhiều điều kiện sai. Đúng SLA phút đạt; cũ hơn một microsecond sai. Dùng context cố định, không NOW(). Không có phần đếm nhóm duplicate; observation trùng khớp có thể nhân dòng ghép. Check không xác minh state run liên kết, đích shortcut thật, nội dung file hay quyền. Không tự tạo đồng hồ/evidence bắt buộc chưa biết để kết luận freshness.",
            "Không dùng >= ở ngưỡng freshness bao gồm đúng mốc, coi giờ tương lai là mới hay INNER JOIN làm mất observation thiếu. Run pipeline gần đây khác observation reference gần đây.",
            "1. FULL JOIN cloud_required_references e với cloud_references a USING(dataset_id,reference_id) giữ cặp thiếu/thừa.\n2. CROSS JOIN một dòng cloud_context c đưa biên as_of cố định vào mỗi cặp.\n3. WHERE chọn danh tính vắng, observed_at NULL, giờ tương lai hoặc c.as_of-a.observed_at lớn hơn e.sla_minutes * INTERVAL '1 minute'. Dấu > nghiêm ngặt cho đúng 60 phút đạt.\n4. COUNT(*) đếm mỗi dòng ghép được chọn một lần. B,C,D,X minh họa cho 4, A đạt. Đồng hồ NULL là thiếu evidence, không phải lý do khẳng định mọi observation mới.",
        ),
    },
})


def apply_guidance(catalog):
    for lab_id, translations in GUIDANCE.items():
        for language, parts in translations.items():
            bodies = list(parts)
            bodies[0] = SCOPE[language] + "\n" + bodies[0]
            bodies[3] += "\n" + IMPORT[language]
            bodies[4] = CHALLENGE[language] + bodies[4]
            bodies[6] = SCOPE[language] + "\n" + bodies[6]
            def section(index):
                return LABELS[language][index] + "\n" + bodies[index]
            text = catalog[lab_id][language]
            text["theory"] = "\n\n".join(section(i) for i in (0, 1, 2, 3, 5))
            text["requirement"] += "\n\n" + section(4)
            text["explanation"] = section(6)
