"""Beginner ETL guidance in existing fields; reference explanations stay private."""

LABELS = {
    "ENG": ("What are we checking?", "Why does this matter?", "Small worked example — illustrative", "How to practice", "Challenge explained", "Common mistake", "Solution explained"),
    "VIE": ("Chúng ta đang kiểm tra gì?", "Vì sao điều này quan trọng?", "Ví dụ nhỏ — chỉ để minh họa", "Cách thực hành", "Giải thích thử thách", "Lỗi thường gặp", "Giải thích lời giải"),
}


GUIDANCE = {
    "lab_015_etl_transform": {
        "ENG": (
            "ETL means Extract, Transform, Load: read input, change it into the required form, then store output. Here Source is the input table etl_source and Target is the published table etl_target. A transformation converts amount text to exact numbers and subtracts discount from gross. Check each order_id and its net_amount, including legitimate zero amounts.",
            "A shop sends prices as text. Rounding 10.01 to 10.00 loses a cent; replacing a zero with NULL loses a known value. Data QA reconciles the published money against the input, even when execution reports SUCCESS.",
            "Three Source rows (order_id, gross_text, discount_text): (10, '10.01', '0.00'), (20, '5.00', '5.00'), (30, '8.00', '1.00'). Expected net_amount: 10.01, 0.00, 7.00. Target rows: (10, 10.00), (20, 0.00), (30, NULL). Orders 10 and 30 fail; order 20 passes. Expected violation_count = 2. A one-cent difference is still a difference.",
            "Start an active SANDBOX; choose clean or a named defect. Before changing anything, run the practice SQL and inspect gross_text, discount_text and net_amount by order_id. Also inspect etl_context and etl_steps with separate SELECT queries. Reset clears Target, rejects and steps, sets batch_no to 0 and leaves Source/reference rows intact: this is not a completed load. Run ETL sets batch 1 and rebuilds outputs from Source, keeping any earlier step records. Compare the values and latest step before/after, then rerun your SQL check. These controls are disabled in CHALLENGE and after reveal/completion; no action should be inferred from a query SUCCESS badge.",
            "Keep the original contract above: one row, one non-negative integer column named violation_count. Count order_id FULL JOIN rows where either key is missing or net_amount differs from exact gross minus discount, including NULL. One joined row counts once even if several conditions hold; duplicate matches can multiply rows. These fixtures supply parseable amount strings; malformed casts would be SQL execution ERROR, not a data-defect count. Your written answer is saved, not semantically graded.",
            "Do not cast money to floating point, round to whole units, or treat 0.00 as missing. A normal <> comparison can skip NULL. An INNER JOIN would hide missing/unexpected orders.",
            "1. FULL JOIN etl_source s and etl_target t USING(order_id) aligns keys and keeps unmatched rows from either side.\n2. Cast gross_text and discount_text to numeric, PostgreSQL's exact decimal type, before subtracting; the example expects 10.01, 0.00 and 7.00.\n3. WHERE keeps missing Source/Target keys or amounts IS DISTINCT FROM the expectation. This comparison also detects NULL versus a known number.\n4. COUNT(*) counts the failing joined rows; AS violation_count gives the required column name. The example returns 2, not the sum of the monetary differences.",
        ),
        "VIE": (
            "ETL là Extract, Transform, Load: đọc dữ liệu đầu vào, biến đổi theo yêu cầu rồi lưu kết quả. Source ở đây là bảng đầu vào etl_source; Target là bảng kết quả etl_target. Transformation là phép biến đổi: đổi chuỗi số tiền thành số chính xác rồi lấy gross trừ discount. Kiểm tra từng order_id và net_amount, kể cả số tiền 0 hợp lệ.",
            "Cửa hàng gửi giá dưới dạng chuỗi. Làm tròn 10.01 thành 10.00 làm mất một cent; đổi 0 thành NULL làm mất giá trị đã biết. Data QA đối soát số tiền được ghi với đầu vào, dù thực thi báo SUCCESS.",
            "Ba dòng Source (order_id, gross_text, discount_text): (10, '10.01', '0.00'), (20, '5.00', '5.00'), (30, '8.00', '1.00'). net_amount kỳ vọng: 10.01, 0.00, 7.00. Target: (10, 10.00), (20, 0.00), (30, NULL). Order 10 và 30 sai; order 20 đúng. Kết quả kỳ vọng violation_count = 2. Lệch một cent vẫn là lệch.",
            "Bắt đầu SANDBOX đang ACTIVE, chọn clean hoặc lỗi có tên. Trước khi thay đổi, chạy SQL thực hành, xem gross_text, discount_text và net_amount theo order_id. Xem thêm etl_context và etl_steps bằng các SELECT riêng. Đặt lại xóa Target, rejects và steps, đưa batch_no về 0, giữ Source/bảng tham chiếu: chưa phải load hoàn tất. Chạy ETL đặt batch 1 và dựng lại đầu ra từ Source, giữ các step trước đó nếu có. So giá trị và step mới nhất trước/sau rồi chạy lại SQL kiểm tra. Điều khiển bị khóa trong CHALLENGE và sau reveal/completion; badge SUCCESS của truy vấn không chứng minh thao tác ETL đã xảy ra.",
            "Giữ hợp đồng gốc bên trên: một dòng, một cột số nguyên không âm tên violation_count. Đếm dòng FULL JOIN theo order_id có key thiếu ở một phía hoặc net_amount khác gross trừ discount chính xác, kể cả NULL. Một dòng ghép tính một lần dù nhiều điều kiện sai; key trùng có thể nhân số dòng ghép. Fixture bài này cung cấp chuỗi đổi được thành số; cast chuỗi sai gây ERROR thực thi SQL, không phải số đếm lỗi dữ liệu. Câu trả lời được lưu, không được chấm tự động về nội dung.",
            "Không đổi tiền sang số thực floating point, làm tròn đến số nguyên hay coi 0.00 là thiếu. So sánh <> thông thường có thể bỏ qua NULL. INNER JOIN làm mất bằng chứng order thiếu/thừa.",
            "1. FULL JOIN etl_source s với etl_target t USING(order_id) ghép theo key và giữ dòng không có đối ứng ở cả hai phía.\n2. Đổi gross_text và discount_text sang numeric, kiểu số thập phân chính xác của PostgreSQL, rồi trừ; ví dụ kỳ vọng 10.01, 0.00 và 7.00.\n3. WHERE giữ key Source/Target thiếu hoặc amount IS DISTINCT FROM kỳ vọng. Phép so này bắt được NULL so với số đã biết.\n4. COUNT(*) đếm dòng ghép sai; AS violation_count đặt tên cột theo yêu cầu. Ví dụ trả 2, không phải tổng chênh lệch số tiền.",
        ),
    },
}


GUIDANCE.update({
    "lab_014_etl_mapping": {
        "ENG": (
            "ETL means Extract, Transform, Load: read input, reshape it, then store output. Source is etl_source; Target is etl_target. Mapping means translating one identifier into another using a reference table: customer_code becomes etl_customers.customer_id. A key identifies a record; here order_id matches the same order across tables. Check missing/unexpected orders and incorrect customer mapping.",
            "An order feed uses customer codes, but a warehouse report needs numeric customer IDs. A load can finish with SUCCESS and the correct row count while assigning sales to the wrong customer. Data QA checks the lookup result for each order, not just the total rows.",
            "Reference etl_customers: ('A', 7), ('B', 8). Source (order_id, customer_code): (10, 'A'), (20, 'B'), (30, 'A'). Expected customer_id values: 7, 8, 7. Target (order_id, customer_id): (10, 8), (20, 8), (40, 7). Order 10 has wrong mapping, 30 is missing, 40 is unexpected. Expected violation_count = 3, although Source and Target each have three rows.",
            "Choose an active SANDBOX and clean or a named defect. Before pressing controls, run the practice SQL to compare expected_customer with actual_customer, and separately inspect etl_customers, etl_target and etl_steps. The practice LEFT JOIN does not show unexpected Target-only keys; query Target too. Reset clears Target/rejects/steps and sets batch 0, retaining Source/reference data. Run ETL sets batch 1 and rebuilds outputs from Source, preserving any prior step records. Compare mappings and latest Target counts before/after, then rerun the QA query. Controls are unavailable in CHALLENGE and after reveal/completion. Execution SUCCESS says the operation finished, not that the mapping is correct.",
            "Return one row with one non-negative integer column violation_count, under the unchanged contract above. Count FULL JOIN rows that lack a key on either side or have a customer_id different from the Source lookup. Multiple wrong conditions on one joined row count once; duplicate matches may multiply rows. The lookup uses only Source codes present in etl_customers; this check does not independently flag unknown Source codes or compare money. Your written answer is saved, not semantically graded.",
            "Equal counts do not mean equal keys. Do not match by row position or assume customer_code and customer_id are the same value. An INNER JOIN to Target would hide missing and unexpected orders.",
            "1. The expected CTE (a named query result introduced by WITH) JOINs etl_source to etl_customers USING(customer_code), deriving the expected customer_id for each known code.\n2. FULL JOIN expected e with etl_target t USING(order_id) retains matched, missing and unexpected orders.\n3. WHERE selects absent keys or e.customer_id IS DISTINCT FROM t.customer_id, including NULL differences.\n4. COUNT(*) counts selected joined rows once. In the example the wrong mapping, missing key and unexpected key contribute 1 each, returning 3. The reference lookup is an input to this check, not something the check validates itself.",
        ),
        "VIE": (
            "ETL là Extract, Transform, Load: đọc đầu vào, biến đổi rồi lưu đầu ra. Source là etl_source; Target là etl_target. Mapping, hay ánh xạ, là đổi mã nhận diện bằng bảng tham chiếu: customer_code thành etl_customers.customer_id. Key nhận diện bản ghi; order_id dùng để ghép cùng một order giữa các bảng. Kiểm tra order thiếu/thừa và ánh xạ customer sai.",
            "Dữ liệu order dùng mã customer, nhưng báo cáo kho dữ liệu cần ID dạng số. Load có thể báo SUCCESS và đủ số dòng nhưng gán doanh số cho sai customer. Data QA kiểm tra kết quả tra cứu của từng order, không chỉ tổng số dòng.",
            "etl_customers tham chiếu: ('A', 7), ('B', 8). Source (order_id, customer_code): (10, 'A'), (20, 'B'), (30, 'A'). customer_id kỳ vọng: 7, 8, 7. Target (order_id, customer_id): (10, 8), (20, 8), (40, 7). Order 10 ánh xạ sai, 30 thiếu, 40 thừa. Kết quả kỳ vọng violation_count = 3, dù Source và Target đều có ba dòng.",
            "Chọn SANDBOX đang ACTIVE và clean hoặc lỗi có tên. Trước khi bấm điều khiển, chạy SQL thực hành để so expected_customer với actual_customer; xem riêng etl_customers, etl_target và etl_steps. LEFT JOIN thực hành không hiển thị key chỉ có ở Target; cần xem Target nữa. Đặt lại xóa Target/rejects/steps, đưa batch về 0, giữ Source/bảng tham chiếu. Chạy ETL đặt batch 1 và dựng lại đầu ra từ Source, giữ các step trước nếu có. So ánh xạ và số dòng Target mới nhất trước/sau rồi chạy lại truy vấn QA. Điều khiển không dùng được trong CHALLENGE hoặc sau reveal/completion. SUCCESS chỉ nói thao tác hoàn tất, chưa chứng minh mapping đúng.",
            "Trả một dòng, một cột số nguyên không âm violation_count theo hợp đồng gốc bên trên. Đếm dòng FULL JOIN thiếu key ở một phía hoặc customer_id khác kết quả tra cứu Source. Nhiều điều kiện sai trên một dòng ghép vẫn tính một lần; key trùng có thể nhân số dòng ghép. Tra cứu chỉ lấy mã Source có trong etl_customers; check này không tự bắt mã Source chưa biết và không so số tiền. Câu trả lời được lưu, không được chấm tự động về nội dung.",
            "Bằng số dòng không có nghĩa bằng key. Không ghép theo vị trí dòng hay coi customer_code và customer_id là cùng giá trị. INNER JOIN với Target sẽ giấu order thiếu/thừa.",
            "1. CTE expected là kết quả truy vấn có tên, khai báo bằng WITH. JOIN etl_source với etl_customers USING(customer_code) suy ra customer_id kỳ vọng cho mỗi mã đã biết.\n2. FULL JOIN expected e với etl_target t USING(order_id) giữ order khớp, thiếu và thừa.\n3. WHERE chọn key vắng hoặc e.customer_id IS DISTINCT FROM t.customer_id, kể cả khác biệt NULL.\n4. COUNT(*) đếm mỗi dòng ghép được chọn một lần. Trong ví dụ, mapping sai, key thiếu và key thừa góp 1 mỗi loại, trả 3. Bảng tham chiếu là đầu vào của check, không được chính check này xác minh.",
        ),
    },
    "lab_016_etl_quarantine": {
        "ENG": (
            "Check that valid input keys reach etl_target and invalid keys remain visible in etl_rejects. Source is the input; Target is accepted output. A reject is a record withheld from publication; quarantine keeps its key and reason for investigation instead of silently deleting it. Both gross_text and discount_text must be unsigned digit strings with an optional dot and one or two decimal digits, such as '0', '12.3' or '12.34'.",
            "A supplier sends an amount as '1,23'. Publishing it as zero would invent money; silently discarding it would hide a missing order. Data QA verifies accepted keys and rejected evidence separately, even if the ETL execution says SUCCESS.",
            "Source (order_id, gross_text, discount_text): (10, '10.00', '0.00'), (20, 'oops', '0.00'), (30, '1,23', '0.00'). Only 10 is valid. Target contains only 10. Rejects contain (20, 'INVALID_AMOUNT') twice and no row for 30. Accepted differences = 0; rejected differences = 1 for missing 30 (both correct copies of 20 match); duplicate reject groups = 1 for 20. Expected violation_count = 2, not the number of rejected Source rows.",
            "In an active SANDBOX, inspect gross_text and discount_text with the practice query before attempting any numeric cast. Separately query etl_target, etl_rejects and etl_steps; compare where each key went and the reason. Reset clears outputs and step history, sets batch 0 and retains input/reference data. Run ETL sets batch 1 and rebuilds accepted/rejected outputs, retaining earlier steps if any. Compare keys, INVALID_AMOUNT reasons and duplicate groups before/after, then rerun the QA check. Controls are disabled in CHALLENGE and after reveal/completion. A rejected_rows total alone cannot prove every invalid key was recorded.",
            "Return one row and one non-negative integer column violation_count. Add valid-key/Target FULL JOIN differences, invalid-key/Reject FULL JOIN differences or wrong reasons, and duplicate reject-key groups, as in the unchanged contract. One failing joined row counts once; one duplicate group counts once, whatever its size. A wrong reason on two copies can count twice plus their duplicate group. This checks routing/reasons, not accepted money or customer mapping. The fixtures have non-NULL amount strings: NULL makes the predicate unknown and enters neither valid nor invalid set. Your written answer is saved, not semantically graded.",
            "Filter malformed text before casting it: a cast failure is SQL execution ERROR, not a successful defect count. Do not count all rejects as violations: correctly quarantined rows are expected evidence. Duplicate groups are not excess rows.",
            "1. valid filters Source with the amount regex for both fields; invalid uses NOT of the same combined rule. No malformed amount is cast.\n2. accepted FULL JOINs valid keys to Target and selects keys missing on either side, including invalid keys wrongly published.\n3. rejected FULL JOINs invalid keys to etl_rejects; missing/unexpected keys or reason IS DISTINCT FROM 'INVALID_AMOUNT' fail.\n4. duplicates GROUP BY order_id with HAVING COUNT(*) > 1 finds repeated reject-key groups.\n5. Add the three COUNT(*) results. The example is 0 + 1 + 1 = 2. Accepted/rejected differences count joined rows; duplicates count groups, so this sum is not a count of distinct bad orders.",
        ),
        "VIE": (
            "Kiểm tra key đầu vào hợp lệ đến etl_target và key lỗi vẫn có bằng chứng trong etl_rejects. Source là đầu vào; Target là đầu ra được nhận. Reject là bản ghi chưa được đưa vào kết quả; quarantine giữ key và lý do để điều tra thay vì âm thầm xóa. Cả gross_text và discount_text phải là chuỗi chữ số không dấu, có thể thêm dấu chấm và một hoặc hai chữ số thập phân, như '0', '12.3', '12.34'.",
            "Nhà cung cấp gửi amount '1,23'. Ghi thành 0 là tự tạo số tiền; bỏ âm thầm sẽ giấu order bị mất. Data QA kiểm tra riêng key được nhận và bằng chứng reject, dù ETL báo SUCCESS.",
            "Source (order_id, gross_text, discount_text): (10, '10.00', '0.00'), (20, 'oops', '0.00'), (30, '1,23', '0.00'). Chỉ 10 hợp lệ. Target chỉ có 10. Rejects có (20, 'INVALID_AMOUNT') hai lần và không có 30. Khác biệt accepted = 0; khác biệt rejected = 1 vì thiếu 30 (hai bản sao đúng của 20 đều ghép khớp); nhóm reject trùng = 1 cho 20. Kết quả kỳ vọng violation_count = 2, không phải số dòng Source bị reject.",
            "Trong SANDBOX đang ACTIVE, dùng truy vấn thực hành xem gross_text và discount_text trước khi cast thành số. Truy vấn riêng etl_target, etl_rejects và etl_steps; so đích đến và lý do của từng key. Đặt lại xóa đầu ra và lịch sử step, đặt batch 0, giữ đầu vào/bảng tham chiếu. Chạy ETL đặt batch 1, dựng lại đầu ra accepted/rejected và giữ step trước nếu có. So key, lý do INVALID_AMOUNT và nhóm trùng trước/sau rồi chạy lại check QA. Điều khiển bị khóa trong CHALLENGE và sau reveal/completion. Tổng rejected_rows chưa chứng minh mọi key lỗi đều được ghi lại.",
            "Trả một dòng, một cột số nguyên không âm violation_count. Cộng khác biệt FULL JOIN key hợp lệ/Target, khác biệt FULL JOIN key lỗi/Reject hoặc reason sai, và nhóm reject key trùng theo hợp đồng gốc. Mỗi dòng ghép sai tính một lần; mỗi nhóm trùng tính một lần dù lớn bao nhiêu. Hai bản sao có reason sai có thể góp hai lỗi cộng một nhóm trùng. Check này kiểm tra đích đến/lý do, không so tiền hay mapping customer. Fixture có chuỗi amount không NULL: NULL làm điều kiện không xác định và không vào tập valid hay invalid. Câu trả lời được lưu, không được chấm tự động về nội dung.",
            "Lọc chuỗi sai trước khi cast: cast lỗi là ERROR thực thi SQL, không phải số đếm lỗi chạy thành công. Không coi mọi reject là vi phạm: quarantine đúng là bằng chứng kỳ vọng. Nhóm trùng khác số dòng dư.",
            "1. valid lọc Source bằng regex amount cho cả hai trường; invalid dùng NOT của cùng điều kiện kết hợp. Không cast chuỗi amount lỗi.\n2. accepted FULL JOIN key hợp lệ với Target, chọn key thiếu ở một phía, kể cả key lỗi bị nhận sai.\n3. rejected FULL JOIN key lỗi với etl_rejects; key thiếu/thừa hoặc reason IS DISTINCT FROM 'INVALID_AMOUNT' là vi phạm.\n4. duplicates GROUP BY order_id và HAVING COUNT(*) > 1 tìm nhóm reject key lặp.\n5. Cộng ba COUNT(*). Ví dụ là 0 + 1 + 1 = 2. Khác biệt accepted/rejected đếm dòng ghép; duplicates đếm nhóm, nên tổng không phải số order sai duy nhất.",
        ),
    },
    "lab_017_etl_replay": {
        "ENG": (
            "A batch is a numbered group of arriving data. Incremental loading processes newly available events rather than replacing everything. Here arrived_batch determines visibility and event_id orders versions of one order_id. Target should keep one latest visible version per key. Replay repeats processing at the current batch; idempotency means repeating the same input leaves the intended Target unchanged.",
            "A delivery is retried after a network interruption. Appending again can duplicate orders; ignoring an already-seen order can lose its update. Data QA compares latest visible Source versions with Target and inspects step history to see what actually ran. Execution SUCCESS does not prove replay was safe.",
            "Current batch_no = 2. Source (order_id, event_id, arrived_batch, gross_text, discount_text): (10, 1, 1, '10.00', '0.00'), (10, 2, 2, '12.00', '0.00'), (20, 3, 3, '7.00', '0.00'). Only the first two events are visible; expected Target is order 10/event 2/net 12.00. Target instead has order 10/event 1/net 10.00 twice. Each joined stale row fails (2), and key 10 forms one duplicate group (1). Expected violation_count = 3. Order 20 is not yet missing because batch 3 has not arrived.",
            "Use an active SANDBOX. Before controls, query etl_context, etl_source, etl_target and etl_steps separately; the practice query shows steps only. Reset clears Target/rejects/steps, retains Source and sets batch 0. Next batch raises batch_no by one up to 3 and loads all currently visible events, not only the newly arrived batch. Inspect new/latest keys and step checkpoint, then rerun QA. Replay batch reloads the current visible events without advancing the batch; compare Target keys, event_id and money before/after and check the new REPLAY step. A clean policy keeps the same Target; an append or skipped-update policy can still be wrong. Repeat through batch 3, then replay. Controls require ACTIVE SANDBOX and stop after 100 steps until Reset; the UI shows the latest 20 steps, while SQL can inspect etl_steps. A final snapshot alone cannot prove every earlier step was correct.",
            "Return one row and one non-negative integer column violation_count. Filter Source by arrived_batch <= current batch_no, choose highest event_id per order_id, then add failing FULL JOIN rows to duplicate Target-key groups. Missing/unexpected keys, event_id differences or exact net_amount differences fail; several differences on one joined row count once. Two stale copies can count twice plus one duplicate group. This check does not compare customer_id or prove historical executions. Fixtures use distinct event_id values for deterministic ordering. Your written answer is saved, not semantically graded.",
            "Do not rank all Source before applying batch visibility, use row order as version order, or skip updates merely because a key exists. Counting only Target duplicates misses stale singleton rows; counting only mismatches misses identical latest copies.",
            "1. ranked CROSS JOINs the single etl_context row to Source so each event can be filtered by arrived_batch <= batch_no.\n2. ROW_NUMBER is a window function numbering rows within each order_id, ordered by event_id DESC. expected keeps rn=1, the latest visible event.\n3. mismatches FULL JOINs expected with Target by order_id and selects missing/unexpected keys or NULL-safe event_id/net_amount differences. Money uses exact numeric subtraction.\n4. duplicates GROUP BY order_id with HAVING COUNT(*) > 1 finds repeated Target-key groups.\n5. Add mismatch rows and duplicate groups. The illustrative stale copies give 2 + 1 = 3. Correct latest copies would have zero mismatch rows but still one duplicate group.",
        ),
        "VIE": (
            "Batch là nhóm dữ liệu đến có số thứ tự. Incremental loading là nạp tăng dần các event đã đến thay vì thay toàn bộ dữ liệu. arrived_batch quyết định event được xét; event_id sắp phiên bản của cùng order_id. Target cần giữ một phiên bản mới nhất đã đến cho mỗi key. Replay là xử lý lại tại batch hiện tại; idempotency nghĩa là xử lý lại cùng đầu vào vẫn giữ Target đúng như trước.",
            "Một đợt dữ liệu được gửi lại sau gián đoạn mạng. Append thêm lần nữa có thể nhân đôi order; bỏ key đã thấy có thể mất cập nhật. Data QA so phiên bản Source mới nhất đã đến với Target và xem lịch sử step để biết thao tác thực sự đã chạy. SUCCESS chưa chứng minh replay an toàn.",
            "batch_no hiện tại = 2. Source (order_id, event_id, arrived_batch, gross_text, discount_text): (10, 1, 1, '10.00', '0.00'), (10, 2, 2, '12.00', '0.00'), (20, 3, 3, '7.00', '0.00'). Chỉ hai event đầu được xét; Target kỳ vọng là order 10/event 2/net 12.00. Target lại có order 10/event 1/net 10.00 hai lần. Mỗi dòng cũ ghép sai góp 1 (tổng 2), và key 10 tạo một nhóm trùng (1). Kết quả kỳ vọng violation_count = 3. Order 20 chưa bị thiếu vì batch 3 chưa đến.",
            "Dùng SANDBOX đang ACTIVE. Trước điều khiển, truy vấn riêng etl_context, etl_source, etl_target và etl_steps; SQL thực hành chỉ hiển thị steps. Đặt lại xóa Target/rejects/steps, giữ Source và đặt batch 0. Batch tiếp tăng batch_no một đơn vị đến tối đa 3, nạp mọi event hiện đã đến chứ không chỉ batch mới. Xem key mới/phiên bản mới nhất và checkpoint rồi chạy lại QA. Replay batch xử lý lại event hiện đã đến, không tăng batch; so key, event_id, tiền của Target trước/sau và xem step REPLAY mới. Chính sách sạch giữ Target như cũ; chính sách append hoặc bỏ cập nhật vẫn có thể sai. Tiếp tục đến batch 3 rồi replay. Điều khiển cần ACTIVE SANDBOX, dừng sau 100 step đến khi Đặt lại; UI hiển thị 20 step gần nhất, SQL có thể xem etl_steps. Snapshot cuối không tự chứng minh từng step trước đều đúng.",
            "Trả một dòng, một cột số nguyên không âm violation_count. Lọc Source theo arrived_batch <= batch_no hiện tại, chọn event_id lớn nhất mỗi order_id rồi cộng dòng FULL JOIN sai với nhóm Target key trùng. Key thiếu/thừa, event_id khác hoặc net_amount chính xác khác là vi phạm; nhiều khác biệt trên một dòng ghép tính một lần. Hai bản sao cũ có thể góp hai lỗi cộng một nhóm trùng. Check không so customer_id hay chứng minh thực thi quá khứ. Fixture có event_id khác nhau để sắp thứ tự xác định. Câu trả lời được lưu, không được chấm tự động về nội dung.",
            "Không xếp hạng toàn bộ Source trước khi lọc batch, dùng vị trí dòng làm thứ tự phiên bản hay bỏ cập nhật chỉ vì key đã có. Chỉ đếm duplicate bỏ sót dòng cũ duy nhất; chỉ đếm mismatch bỏ sót các bản sao giống hệt phiên bản mới nhất.",
            "1. ranked CROSS JOIN Source với một dòng etl_context để lọc event theo arrived_batch <= batch_no.\n2. ROW_NUMBER là hàm cửa sổ đánh số dòng trong mỗi order_id theo event_id DESC. expected giữ rn=1, event mới nhất đã đến.\n3. mismatches FULL JOIN expected với Target theo order_id, chọn key thiếu/thừa hoặc event_id/net_amount khác bằng phép so xử lý NULL. Tiền dùng phép trừ numeric chính xác.\n4. duplicates GROUP BY order_id và HAVING COUNT(*) > 1 tìm nhóm Target key lặp.\n5. Cộng dòng mismatch và nhóm trùng. Hai bản sao cũ trong ví dụ trả 2 + 1 = 3. Bản sao đúng của phiên bản mới nhất có thể không mismatch nhưng vẫn góp một nhóm trùng.",
        ),
    },
    "lab_018_etl_recovery": {
        "ENG": (
            "Recovery resumes loading after an interruption. Source is the input etl_source; Target is published etl_target. etl_steps stores execution evidence; checkpoint is the recorded batch marker, required to be 1 here. Check exact order-key/amount reconciliation and the latest step's execution_status/checkpoint together. Data correctness and execution status are separate.",
            "A warehouse job fails before publishing orders, or reports SUCCESS after publishing only part of them. Data QA checks both the rows and the latest execution evidence. An older FAILED step should not invalidate a later successful recovery, but a green execution badge alone cannot prove all orders arrived.",
            "Source (order_id, gross_text, discount_text): (10, '10.01', '0.01'), (20, '5.00', '1.00'), (30, '0.00', '0.00'). Expected Target amounts: 10.00, 4.00, 0.00. Target has only correct orders 10 and 20. Latest etl_steps row: step_no 2, execution_status FAILED, checkpoint 0. Missing order 30 contributes 1; the latest step contributes 1 even though both status and checkpoint fail. Expected violation_count = 2. If that step were SUCCESS/checkpoint 1, the missing order would still give 1.",
            "In an active SANDBOX, inspect etl_steps in step_no order with the practice query; separately query Source and Target before recovery. Reset clears outputs and steps, sets batch 0 and retains Source/reference data: no step means no observed execution, not a PASS claim. Recover load sets batch 1, applies the current loading policy and appends a RECOVER step. Inspect the highest step_no, checkpoint, exact money and missing keys, then rerun QA. Repeat Recover load and compare Target to investigate idempotency (same intended output on repeat), while keeping both step records. In the partial-publication scenario recovery still omits a row despite SUCCESS. Controls are disabled in CHALLENGE and after reveal/completion; after 100 steps Reset is required. The latest snapshot and step cannot establish that every earlier operation was correct.",
            "Return one row and one non-negative integer column violation_count. Add Source/Target FULL JOIN rows with missing keys or wrong exact amounts to the count of latest-step rows whose execution_status is not SUCCESS or checkpoint is not 1. With the normal unique step_no fixture, that step adds at most 1; two wrong fields do not add 2. Only the highest step_no matters. Existing limitation: if etl_steps is empty, the step term contributes 0, so the query does not separately detect missing execution evidence. Do not interpret this as proof a load ran. Your written answer is saved, not semantically graded.",
            "Do not count every historical FAILED step after recovery, equate checkpoint 1 with complete data, or trust only total rows. A SUCCESS step can coexist with a missing order. NULL status/checkpoint also fail on an existing latest step.",
            "1. The nested transformation SELECT FULL JOINs Source and Target by order_id. Its WHERE selects missing keys or net_amount IS DISTINCT FROM gross_text::numeric minus discount_text::numeric; COUNT(*) measures joined data differences.\n2. The second SELECT restricts etl_steps to step_no = MAX(step_no), the latest evidence, and counts a row if status differs from SUCCESS or checkpoint differs from 1. IS DISTINCT FROM also handles NULL. With no steps MAX is NULL and no row qualifies: this is the existing missing-evidence limitation.\n3. Add both scalar counts (each SELECT returns one number) and name the result violation_count. The example gives 1 missing order + 1 latest-step defect = 2. A later SUCCESS/checkpoint 1 removes the step defect, but data must still reconcile independently.",
        ),
        "VIE": (
            "Recovery là khôi phục việc nạp dữ liệu sau gián đoạn. Source là đầu vào etl_source; Target là kết quả etl_target. etl_steps lưu bằng chứng thực thi; checkpoint là mốc batch được ghi nhận, bài này yêu cầu bằng 1. Kiểm tra đối soát key/số tiền chính xác cùng execution_status/checkpoint của step mới nhất. Dữ liệu đúng và thực thi thành công là hai trạng thái riêng.",
            "Job kho dữ liệu lỗi trước khi ghi order, hoặc báo SUCCESS dù chỉ ghi một phần. Data QA kiểm tra cả dòng dữ liệu lẫn bằng chứng thực thi mới nhất. Step FAILED cũ không nên làm recovery thành công mới bị fail, nhưng badge thực thi xanh chưa chứng minh mọi order đã đến.",
            "Source (order_id, gross_text, discount_text): (10, '10.01', '0.01'), (20, '5.00', '1.00'), (30, '0.00', '0.00'). Amount Target kỳ vọng: 10.00, 4.00, 0.00. Target chỉ có order 10 và 20 đúng. Dòng etl_steps mới nhất: step_no 2, execution_status FAILED, checkpoint 0. Thiếu order 30 góp 1; step mới nhất góp 1 dù status và checkpoint đều sai. Kết quả kỳ vọng violation_count = 2. Nếu step đó là SUCCESS/checkpoint 1, order thiếu vẫn cho kết quả 1.",
            "Trong SANDBOX đang ACTIVE, dùng SQL thực hành xem etl_steps theo step_no; truy vấn riêng Source và Target trước khôi phục. Đặt lại xóa đầu ra/steps, đặt batch 0, giữ Source/bảng tham chiếu: không có step nghĩa là chưa quan sát thực thi, không phải kết luận PASS. Khôi phục load đặt batch 1, áp dụng chính sách nạp hiện tại và thêm step RECOVER. Xem step_no lớn nhất, checkpoint, số tiền chính xác và key thiếu rồi chạy lại QA. Lặp Khôi phục load và so Target để khảo sát idempotency (lặp vẫn giữ đầu ra đúng như cũ), đồng thời giữ cả hai step. Trong scenario publish thiếu, recovery vẫn bỏ một dòng dù báo SUCCESS. Điều khiển bị khóa trong CHALLENGE và sau reveal/completion; đủ 100 step cần Đặt lại. Snapshot và step mới nhất không chứng minh mọi thao tác trước đều đúng.",
            "Trả một dòng, một cột số nguyên không âm violation_count. Cộng dòng FULL JOIN Source/Target thiếu key hoặc sai số tiền chính xác với số dòng step mới nhất có execution_status không SUCCESS hoặc checkpoint không bằng 1. Với fixture step_no duy nhất thông thường, step đó góp tối đa 1; hai trường sai không góp 2. Chỉ xét step_no lớn nhất. Giới hạn hiện có: etl_steps rỗng thì phần step góp 0, nên truy vấn không tự bắt việc thiếu bằng chứng thực thi. Không hiểu đó là chứng minh load đã chạy. Câu trả lời được lưu, không được chấm tự động về nội dung.",
            "Không đếm mọi step FAILED trong lịch sử sau recovery, coi checkpoint 1 là đủ dữ liệu hay chỉ tin tổng số dòng. Step SUCCESS vẫn có thể đi cùng order thiếu. Status/checkpoint NULL trên step mới nhất đang có cũng là lỗi.",
            "1. SELECT biến đổi bên trong FULL JOIN Source với Target theo order_id. WHERE chọn key thiếu hoặc net_amount IS DISTINCT FROM gross_text::numeric trừ discount_text::numeric; COUNT(*) đếm dòng ghép khác biệt dữ liệu.\n2. SELECT thứ hai giới hạn etl_steps bằng step_no = MAX(step_no), bằng chứng mới nhất, và đếm dòng nếu status khác SUCCESS hoặc checkpoint khác 1. IS DISTINCT FROM xử lý cả NULL. Không có step thì MAX là NULL, không dòng nào thỏa: đây là giới hạn thiếu bằng chứng hiện có.\n3. Cộng hai số đếm đơn (mỗi SELECT trả một số) và đặt tên violation_count. Ví dụ là 1 order thiếu + 1 lỗi step mới nhất = 2. Step SUCCESS/checkpoint 1 mới hơn loại lỗi step, nhưng vẫn phải đối soát dữ liệu độc lập.",
        ),
    },
})


def apply_guidance(catalog):
    for lab_id, translations in GUIDANCE.items():
        for language, parts in translations.items():
            def section(index):
                return LABELS[language][index] + "\n" + parts[index]
            text = catalog[lab_id][language]
            text["theory"] = "\n\n".join(section(i) for i in (0, 1, 2, 3, 5))
            text["requirement"] += "\n\n" + section(4)
            text["explanation"] = section(6)
