"""Beginner explanations of existing foundation evidence contracts, not new rules."""
from backend.app.learning.cloud_guidance import LABELS

SCOPE = {
    'ENG': 'SIMULATED / IMPORTED evidence in local PostgreSQL only. No live cloud connection, Spark/Delta execution or transaction log, time travel, Synapse engine, real file listing or Azure authorization. PostgreSQL SQL here is not a portable provider implementation. Execution SUCCESS does not prove data correctness; incomplete evidence keeps quality NOT_VERIFIED.',
    'VIE': 'Chỉ có evidence SIMULATED / IMPORTED trong PostgreSQL local. Không kết nối cloud thật, chạy Spark/Delta hay transaction log, time travel, engine Synapse, listing file thật hoặc cấp quyền Azure. SQL PostgreSQL ở đây không phải implementation dùng trực tiếp cho mọi provider. Execution SUCCESS không chứng minh dữ liệu đúng; evidence thiếu giữ quality NOT_VERIFIED.',
}
IMPORT = {
    'ENG': 'Import practice: open Import foundation JSON evidence in an ACTIVE SANDBOX and Download evidence JSON for this lesson. JSON only, not the Fabric/ADF/OneLake CSV format. The version 1 envelope requires version=1, kind=foundations, the exact lab_id, contract_id (standard/shifted/zero), matching provider (Databricks/Synapse/Azure), resource_id, as_of, batch_no, runs, steps and datasets. Every listed observed table and every row field is required; keep the typed template names. Independent expected tables are excluded. contract_id selects a built-in contract; imported claims cannot write grading truth. Timestamps need a timezone and normalize to UTC; use decimal strings for exact money and ISO dates for sale_date. Required context fields may contain supported NULL values: unknown context stays unknown, not inferred from rows. Imported checkpoints are claims, not proof of local execution.\nAfter Validate and import, inspect IMPORTED provenance, contract, selected context, filename/hash, referenced runs and evidence gaps; rerun QA. Simulator actions are locked until Reset; Reset reloads the selected scenario and retains import audit. Limits: 48 KiB file, 64 KiB request, 100 rows/dataset, 400 total observed rows, 101 runs, 100 steps and 8 imports/session. Oversized export fails; no referenced evidence is silently dropped. SQL exploration reflects your query; submission checks independent clean/fault fixtures. Local mutation revisions invalidate previous checks, not provider timestamps.',
    'VIE': 'Thực hành import: mở Import evidence JSON nền tảng trong ACTIVE SANDBOX rồi Tải evidence JSON đúng bài. Chỉ JSON, không dùng format CSV Fabric/ADF/OneLake. Envelope version 1 bắt buộc version=1, kind=foundations, lab_id đúng bài, contract_id (standard/shifted/zero), provider khớp (Databricks/Synapse/Azure), resource_id, as_of, batch_no, runs, steps và datasets. Phải có mọi bảng quan sát được liệt kê và mọi field của mỗi dòng; giữ tên trong template typed. Không có bảng kỳ vọng độc lập trong import. contract_id chọn contract dựng sẵn; thông tin import không viết sự thật để chấm. Timestamp cần múi giờ và chuẩn hóa UTC; dùng chuỗi thập phân cho tiền chính xác, ngày ISO cho sale_date. Field context bắt buộc có thể chứa NULL được hỗ trợ: context chưa biết vẫn chưa biết, không suy từ dòng. Checkpoint import là thông tin được báo, không chứng minh thực thi local.\nSau Kiểm tra và import, xem provenance IMPORTED, contract, context đang xét, tên file/hash, run được tham chiếu và evidence thiếu; chạy lại QA. Thao tác simulator khóa tới khi Đặt lại; Đặt lại nạp lại scenario đã chọn và giữ lịch sử import. Giới hạn: file 48 KiB, request 64 KiB, 100 dòng/dataset, tổng 400 dòng quan sát, 101 run, 100 step và 8 import/session. Export quá giới hạn báo lỗi; không âm thầm bỏ evidence được tham chiếu. Khám phá SQL phản ánh query của bạn; submission kiểm tra fixture sạch/lỗi độc lập. Revision mutation local làm check cũ hết hiệu lực, không dùng timestamp provider.',
}
CHALLENGE = {
    'ENG': 'Return exactly one row with one non-negative integer column named violation_count. Count failing joined rows plus duplicate key groups, not just count differences or excess duplicate copies. A joined row with several wrong fields counts once; matching duplicates add only the group term, while mismatching duplicates can also multiply the reconciliation term. SQL errors are ERROR, not defects. Execution SUCCESS does not establish correctness; incomplete evidence remains NOT_VERIFIED. Written answers are saved, not semantically graded. ',
    'VIE': 'Trả đúng một dòng, một cột số nguyên không âm tên violation_count. Đếm dòng JOIN sai cộng nhóm key trùng, không chỉ chênh số dòng hay số bản sao dư. Một dòng JOIN sai nhiều field tính một; duplicate khớp chỉ cộng phần nhóm, duplicate sai còn có thể nhân phần đối soát. Lỗi SQL là ERROR, không phải lỗi dữ liệu. Execution SUCCESS không xác nhận đúng dữ liệu; evidence thiếu vẫn NOT_VERIFIED. Câu trả lời viết được lưu, không chấm ngữ nghĩa. ',
}
GUIDANCE = {
    'lab_031_databricks_classification': {
        'ENG': (
            'Databricks supports data processing and analytics; this exercise checks local routing evidence. Classification means assigning a category: ACCEPTED can be published, REJECTED violates a known input rule, QUARANTINED is retained for investigation. The exercise policy tests customer_id<=0 first, then amount IS NULL, otherwise accepts, including zero. This is not a Databricks default. db_source is input evidence; db_contract independently states one expected classification and exact amount per record_id; db_publication records every destination, including rejects.',
            'An order feed accepts valid sales but quietly drops records needing review. Counting accepted rows alone misses that loss. Data QA accounts for rejected and quarantined records as well as accepted ones.',
            'Illustrative contract: record 10 ACCEPTED/10.01, 20 REJECTED/5.00, 30 QUARANTINED/NULL, 40 ACCEPTED/0.00. Publication: 10 ACCEPTED/10.01 twice, 20 REJECTED/5.00, 30 ACCEPTED/NULL; 40 absent. Two matching copies of 10 add no mismatch but form one duplicate group (1); 20 is a correct reject (0); 30 is wrongly classified (1); 40 is missing (1). Expected violation_count = 3. NULL amounts compare safely; zero is a valid amount.',
            'Start a clean SANDBOX, inspect db_source, db_contract and db_publication under Observed evidence and independent expectations; run the guided SELECT to see source-to-publication categories. Open a named fault attempt and compare keys and destinations. Run local publication rebuilds db_publication from db_source using the stated precedence, including rejects/quarantine; compare before/after and rerun QA. Reset simulator reloads the chosen scenario, not always clean, and does not mean every failure was repaired. Controls require ACTIVE SANDBOX. Imported observed tables are db_source and db_publication, not db_contract.',
            'FULL JOIN db_contract to db_publication by record_id. Count absent keys or classification/amount differences once per joined row, then add repeated record_id groups. Correct rejects/quarantine are expected outcomes, not defects. This checks declared publication against the independent contract, not every source rule or run history; run_id is not a compared business value.',
            'Do not filter out REJECTED/QUARANTINED rows before reconciliation or count three copies of one key as three duplicate groups. Repeated matching copies yield one group; missing keys still matter when totals look plausible.',
            '1. FULL JOIN db_contract e to db_publication a USING(record_id) keeps expected-only and observed-only keys.\n2. WHERE checks absent IDs or classification/amount IS DISTINCT FROM: unlike <> this detects NULL differences. COUNT(*) counts selected joined rows.\n3. GROUP BY record_id HAVING COUNT(*)>1 identifies repeated publication keys. An outer COUNT(*) counts groups, not extra rows.\n4. Add both scalar counts: the example gives 2 failing joined rows + 1 duplicate group = 3. No filter discards a correctly rejected or quarantined record.',
        ),
        'VIE': (
            'Databricks hỗ trợ xử lý và phân tích dữ liệu; bài này kiểm tra evidence routing local. Classification là gán loại: ACCEPTED được publish, REJECTED vi phạm rule input đã biết, QUARANTINED được giữ để điều tra. Policy bài xét customer_id<=0 trước, rồi amount IS NULL, còn lại nhận, kể cả 0. Đây không phải mặc định Databricks. db_source là evidence input; db_contract định nghĩa độc lập một loại kỳ vọng và amount chính xác mỗi record_id; db_publication ghi mọi đích, kể cả reject.',
            'Feed order nhận sale hợp lệ nhưng âm thầm bỏ dòng cần xem lại. Chỉ đếm accepted không thấy mất mát đó. Data QA đối soát cả rejected, quarantined và accepted.',
            'Contract minh họa: record 10 ACCEPTED/10.01, 20 REJECTED/5.00, 30 QUARANTINED/NULL, 40 ACCEPTED/0.00. Publication: 10 ACCEPTED/10.01 hai lần, 20 REJECTED/5.00, 30 ACCEPTED/NULL; không có 40. Hai bản 10 khớp không gây mismatch nhưng tạo một nhóm trùng (1); 20 reject đúng (0); 30 sai loại (1); 40 thiếu (1). Kết quả kỳ vọng violation_count = 3. So NULL an toàn; amount 0 hợp lệ.',
            'Mở SANDBOX sạch, xem db_source, db_contract, db_publication trong Evidence quan sát và kỳ vọng độc lập; chạy SELECT hướng dẫn để thấy loại source/publication. Mở attempt lỗi cụ thể và so key/đích. Chạy publication local dựng lại db_publication từ db_source theo thứ tự policy đã nêu, kể cả reject/quarantine; so trước-sau rồi chạy lại QA. Đặt lại simulator nạp scenario đã chọn, không luôn sạch và không có nghĩa mọi lỗi đã sửa. Điều khiển cần ACTIVE SANDBOX. Bảng quan sát import là db_source, db_publication, không có db_contract.',
            'FULL JOIN db_contract với db_publication theo record_id. Đếm key vắng hoặc khác classification/amount một lần mỗi dòng JOIN rồi cộng nhóm record_id lặp. Reject/quarantine đúng là kết quả kỳ vọng, không phải lỗi. Check so publication với contract độc lập, không xét mọi rule source hay lịch sử run; run_id không phải giá trị nghiệp vụ được so.',
            'Không loại REJECTED/QUARANTINED trước đối soát hay tính ba bản cùng key là ba nhóm trùng. Bản sao khớp lặp cho một nhóm; key thiếu vẫn quan trọng dù tổng có vẻ đúng.',
            '1. FULL JOIN db_contract e với db_publication a USING(record_id) giữ key chỉ có ở kỳ vọng hoặc quan sát.\n2. WHERE xét ID vắng hoặc classification/amount IS DISTINCT FROM: khác <>, toán tử này phát hiện khác biệt NULL. COUNT(*) đếm dòng JOIN được chọn.\n3. GROUP BY record_id HAVING COUNT(*)>1 tìm key publication lặp. COUNT(*) ngoài đếm nhóm, không đếm dòng dư.\n4. Cộng hai số: ví dụ có 2 dòng JOIN sai + 1 nhóm trùng = 3. Không lọc bỏ record reject/quarantine đúng.',
        ),
    },
}


GUIDANCE.update({
    'lab_032_databricks_versions': {
        'ENG': (
            'Databricks can process changing datasets; here explicit version means an ordered business revision, not arrival time. db_before and db_incoming show old and incoming orders; db_expected_after independently defines the required final state. The local update accepts only incoming.version > after.version and inserts absent keys. Equal or smaller versions do not overwrite; untouched keys must survive. This is not an ADF timestamp watermark or a Spark/Delta transaction demonstration.',
            'A delayed version 2 arrives after version 3 and replaces its price. The pipeline reports SUCCESS, yet the business value regresses. Data QA checks which version survives and that replay creates no extra order.',
            'Illustrative before: order 10 v3/10.01, 20 v5/20.02, 30 v1/0.00. Incoming: 10 v2/9.01, 20 v6/21.02, 40 v1/30.03. All updated_at values are 2026-03-01T12:00:00Z. Expected after: 10 v3/10.01, 20 v6/21.02, 30 v1/0.00, 40 v1/30.03. Observed after: 10 v2/9.01; 20 v6/21.02 twice; 40 v1/30.03; 30 absent. Stale 10 (1), missing 30 (1), duplicate group 20 (1) give violation_count = 3. Two wrong fields on 10 still count once.',
            'Inspect db_before, db_incoming, db_expected_after and db_after before actions; the guided UNION ALL labels each observed snapshot. Run local publication and Replay version update both apply the same greater-version guard to current db_after, not a fresh rebuild from db_before. Compare versions/keys and step output counts before/after, then rerun QA. Replay can retain an existing duplicate; a lost newer value cannot always be reconstructed from stale incoming data. Reset simulator restores the selected scenario, including its faults. No Next batch control or timestamp progression. Imported tables are db_before, db_incoming and db_after.',
            'Reconcile db_expected_after with db_after by order_id, comparing version, exact amount and updated_at; add repeated order_id groups. Equal-version differing payloads are not arbitrated by a timestamp in this operator. The grader uses independent final expectations, not imported before/incoming data as truth. This final-state check does not validate every intermediate transition, resolve tied incoming revisions or prove Delta atomicity. run_id is not compared.',
            'Do not choose the latest timestamp when all timestamps tie, use >= to overwrite equal versions, or treat a successful replay as proof duplicates were removed. Check untouched keys as well as incoming ones.',
            '1. FULL JOIN db_expected_after e to db_after a USING(order_id) retains missing and extra orders.\n2. WHERE tests absent IDs and version/amount/updated_at IS DISTINCT FROM; each failing joined row counts once even if several values differ.\n3. GROUP BY order_id HAVING COUNT(*)>1 finds repeated final keys; the outer COUNT counts groups.\n4. Add the counts: 2 failing rows + 1 duplicate group = 3. The reference SELECT verifies the final contract; it does not perform updates or select by watermark.',
        ),
        'VIE': (
            'Databricks có thể xử lý dataset thay đổi; ở đây version là revision nghiệp vụ có thứ tự, không phải giờ tới. db_before và db_incoming cho thấy order cũ và mới tới; db_expected_after định nghĩa độc lập final state cần có. Update local chỉ nhận incoming.version > after.version và thêm key vắng. Version bằng hoặc nhỏ hơn không ghi đè; key không đổi phải còn. Đây không phải watermark timestamp ADF hay minh họa transaction Spark/Delta.',
            'Version 2 đến trễ sau version 3 rồi thay giá mới. Pipeline báo SUCCESS nhưng giá trị nghiệp vụ lùi lại. Data QA kiểm tra version được giữ và replay không tạo thêm order.',
            'Before minh họa: order 10 v3/10.01, 20 v5/20.02, 30 v1/0.00. Incoming: 10 v2/9.01, 20 v6/21.02, 40 v1/30.03. Mọi updated_at là 2026-03-01T12:00:00Z. After kỳ vọng: 10 v3/10.01, 20 v6/21.02, 30 v1/0.00, 40 v1/30.03. After quan sát: 10 v2/9.01; 20 v6/21.02 hai lần; 40 v1/30.03; thiếu 30. Order 10 cũ (1), thiếu 30 (1), nhóm 20 trùng (1) cho violation_count = 3. Order 10 sai hai field vẫn tính một.',
            'Xem db_before, db_incoming, db_expected_after, db_after trước thao tác; UNION ALL hướng dẫn gắn nhãn từng snapshot quan sát. Chạy publication local và Replay cập nhật version cùng áp dụng guard version lớn hơn trên db_after hiện tại, không dựng mới từ db_before. So version/key và số dòng output trong step trước-sau rồi chạy lại QA. Replay có thể giữ duplicate đã có; giá trị mới bị mất không luôn phục hồi được từ incoming cũ. Đặt lại simulator khôi phục scenario đã chọn, kể cả lỗi của nó. Không có Batch tiếp hay tiến timestamp. Bảng import là db_before, db_incoming, db_after.',
            'Đối soát db_expected_after với db_after theo order_id, so version, amount chính xác, updated_at; cộng nhóm order_id lặp. Payload khác nhưng cùng version không được operator phân xử bằng timestamp. Grader dùng kỳ vọng cuối độc lập, không lấy before/incoming import làm sự thật. Check final state không xác minh mọi chuyển tiếp, giải quyết incoming revision đồng hạng hay chứng minh atomicity Delta. Không so run_id.',
            'Không chọn timestamp mới nhất khi mọi timestamp bằng nhau, dùng >= để ghi đè version bằng hay coi replay thành công là đã xóa duplicate. Kiểm tra cả key không đổi, không chỉ key incoming.',
            '1. FULL JOIN db_expected_after e với db_after a USING(order_id) giữ order thiếu và thừa.\n2. WHERE xét ID vắng và version/amount/updated_at IS DISTINCT FROM; mỗi dòng JOIN sai tính một dù nhiều field khác.\n3. GROUP BY order_id HAVING COUNT(*)>1 tìm key cuối lặp; COUNT ngoài đếm nhóm.\n4. Cộng: 2 dòng sai + 1 nhóm trùng = 3. SELECT lời giải kiểm tra contract cuối; không chạy update hay chọn theo watermark.',
        ),
    },
    'lab_033_synapse_publication': {
        'ENG': (
            'Synapse combines warehouse analytics and data integration; here PostgreSQL simulates publication. Staging is incoming business data. A fact is one business event, with grain (the meaning of one row) sale_id. A dimension supplies descriptive customer information. sy_staging uses business customer_code; sy_dimension maps it to customer_key stored in sy_fact. sy_expected_fact independently defines the required key, amount and sale_date per sale.',
            'A warehouse loads the right sales amounts but links one sale to another customer. Revenue totals look right, yet customer reporting is wrong. Data QA reconciles identities as well as money.',
            'Illustrative expected facts on 2026-03-01: sale 10/customer 101/10.01, 20/101/20.02, 30/102/0.00. Observed: 10/999/10.01, 20/101/20.02, 40/102/0.00 on the same date. Wrong customer for 10 (1), missing 30 (1), unexpected 40 (1); no duplicate sale groups. Expected violation_count = 3. Both sides have three rows and total 30.03, which does not prove matching keys.',
            'Inspect sy_staging customer_code, sy_dimension code/key multiplicity, sy_fact and independent sy_expected_fact. The guided LEFT JOIN exposes source-to-dimension and published keys. Run local publication rebuilds sy_fact using an INNER JOIN on customer_code: no dimension match omits a sale; repeated matches multiply it. Compare before/after and rerun QA; rerunning a bad lookup does not fix it. Reset simulator reloads the selected scenario. Import observed sy_staging, sy_dimension and sy_fact; sy_expected_fact is built-in truth.',
            'FULL JOIN expected and actual by sale_id; count missing/extra keys or differing customer_key/amount/sale_date once per joined row, then duplicate sale_id groups. A wrong dimension mapping is a fact defect even with a correct total. This check reconciles final facts, not every dimension attribute, historical dimension interval or intermediate load; run_id is not compared.',
            'Do not JOIN expected and actual by customer_key instead of sale_id or trust equal counts. An INNER JOIN reconciliation hides missing sales; joining a repeated dimension can create duplicates.',
            '1. FULL JOIN sy_expected_fact e and sy_fact a USING(sale_id) preserves sales present on only one side.\n2. WHERE finds absent sale IDs or customer_key/amount/sale_date IS DISTINCT FROM; COUNT(*) counts failing joined rows.\n3. GROUP BY sale_id HAVING COUNT(*)>1 detects repeated fact events; count groups separately.\n4. Add them: wrong mapping + missing + unexpected = 3, with zero duplicate groups. The reference check does not reuse a potentially faulty dimension JOIN as its expected truth.',
        ),
        'VIE': (
            'Synapse kết hợp phân tích warehouse và tích hợp dữ liệu; ở đây PostgreSQL mô phỏng publication. Staging là dữ liệu nghiệp vụ mới tới. Fact là một sự kiện nghiệp vụ, grain (ý nghĩa một dòng) là sale_id. Dimension cung cấp thông tin mô tả customer. sy_staging dùng customer_code nghiệp vụ; sy_dimension ánh xạ sang customer_key lưu trong sy_fact. sy_expected_fact định nghĩa độc lập key, amount, sale_date cần có mỗi sale.',
            'Warehouse load đúng amount nhưng nối một sale với customer khác. Tổng revenue đúng nhưng báo cáo theo customer sai. Data QA đối soát danh tính cùng với tiền.',
            'Fact kỳ vọng minh họa ngày 2026-03-01: sale 10/customer 101/10.01, 20/101/20.02, 30/102/0.00. Quan sát: 10/999/10.01, 20/101/20.02, 40/102/0.00 cùng ngày. Sale 10 sai customer (1), thiếu 30 (1), thừa 40 (1); không có nhóm sale trùng. Kết quả kỳ vọng violation_count = 3. Hai bên đều ba dòng và tổng 30.03, chưa chứng minh key khớp.',
            'Xem customer_code sy_staging, số match code/key sy_dimension, sy_fact, sy_expected_fact độc lập. LEFT JOIN hướng dẫn hiển thị key source/dimension và key đã publish. Chạy publication local dựng lại sy_fact bằng INNER JOIN customer_code: không match dimension thì mất sale; match lặp thì nhân dòng. So trước-sau và chạy lại QA; lookup sai chạy lại không tự sửa. Đặt lại simulator nạp scenario đã chọn. Import sy_staging, sy_dimension, sy_fact quan sát; sy_expected_fact là sự thật dựng sẵn.',
            'FULL JOIN kỳ vọng và thực tế theo sale_id; đếm key thiếu/thừa hoặc khác customer_key/amount/sale_date một lần mỗi dòng JOIN rồi cộng nhóm sale_id trùng. Mapping dimension sai là lỗi fact dù tổng đúng. Check đối soát fact cuối, không xét mọi thuộc tính dimension, khoảng lịch sử dimension hay load trung gian; không so run_id.',
            'Không JOIN kỳ vọng/thực tế bằng customer_key thay sale_id hoặc tin count bằng nhau. Đối soát bằng INNER JOIN giấu sale thiếu; JOIN dimension lặp có thể tạo duplicate.',
            '1. FULL JOIN sy_expected_fact e với sy_fact a USING(sale_id) giữ sale chỉ có một bên.\n2. WHERE tìm sale ID vắng hoặc customer_key/amount/sale_date IS DISTINCT FROM; COUNT(*) đếm dòng JOIN sai.\n3. GROUP BY sale_id HAVING COUNT(*)>1 phát hiện sự kiện fact lặp; đếm nhóm riêng.\n4. Cộng: sai mapping + thiếu + thừa = 3, không nhóm trùng. Check lời giải không lấy lại JOIN dimension có thể sai làm kỳ vọng.',
        ),
    },
    'lab_034_synapse_grain': {
        'ENG': (
            'Synapse supports analytical reporting; this is a local report reconciliation. Reporting grain is one row per (sale_date,region), not one row per sale. Aggregation combines several facts into sale_count and an exact NUMERIC total. JOIN fanout means one fact matches several dimension rows and gets counted several times before GROUP BY. sy_expected_report is authored independently of that observed join.',
            'Two valid sales are doubled when a customer has two matching dimension rows. A successful report job produces inflated revenue. Data QA checks both group identity and count/total against independent business expectations.',
            'Illustrative facts on 2026-03-01: sale 10/customer_key 101/10.01, 20/101/10.01, 30/102/0.00. Dimension has two 101/North rows and one 102/South row. Expected report: North count 2 total 20.02; South count 1 total 0.00. The observed JOIN report has North count 4 total 40.04; South is correct. North differs in two fields but is one failing joined report row; no duplicate report grain. Expected violation_count = 1. SUM(DISTINCT amount) would yield 10.01 for North and wrongly discard a real equal-price sale.',
            'Inspect sy_fact, sy_dimension customer_key multiplicity, sy_expected_report and sy_report. Run each practice SELECT separately; the editor accepts one statement, and its supplied example inspects dimension counts. Run local publication rebuilds sy_report by joining facts to dimension on customer_key and grouping date/region. A duplicated dimension still produces fanout on rerun; compare report evidence before/after, then rerun QA. Reset restores the selected scenario. Imported observations are sy_staging, sy_dimension, sy_fact and sy_report; expected report remains independent.',
            'FULL JOIN on BOTH sale_date and region; count missing/extra groups or differing sale_count/total once per joined report row, then duplicate (sale_date,region) groups. Do not count each inflated sale as a separate report violation. A changed region can create both a missing and an unexpected group. Valid zero totals remain required. The query checks report values, not the cause of fanout or every fact row.',
            'Do not group or reconcile by region alone, recompute truth through the same faulty JOIN, use floating-point totals, or fix fanout with SUM(DISTINCT amount). Duplicate report groups differ from duplicated dimension matches.',
            '1. FULL JOIN sy_expected_report e and sy_report a USING(sale_date,region) keeps the complete reporting grain and unmatched groups.\n2. WHERE checks absent sale_date keys or sale_count/total IS DISTINCT FROM. COUNT(*) counts failing joined report rows, with NULL-safe comparisons.\n3. GROUP BY sale_date,region HAVING COUNT(*)>1 identifies repeated output groups, independently of dimension duplication.\n4. Add the terms: North contributes 1 despite both count and total being wrong; duplicate report groups contribute 0. Exact decimal arithmetic preserves 20.02 and 40.04.',
        ),
        'VIE': (
            'Synapse hỗ trợ báo cáo phân tích; đây là đối soát report local. Grain báo cáo là một dòng mỗi (sale_date,region), không phải mỗi sale. Aggregate gom nhiều fact thành sale_count và total NUMERIC chính xác. JOIN fanout nghĩa là một fact match nhiều dòng dimension và bị đếm nhiều lần trước GROUP BY. sy_expected_report được viết độc lập với JOIN quan sát đó.',
            'Hai sale hợp lệ bị nhân đôi vì customer có hai dòng dimension match. Job báo cáo thành công nhưng revenue phình lên. Data QA kiểm tra danh tính nhóm và count/total theo kỳ vọng nghiệp vụ độc lập.',
            'Fact minh họa ngày 2026-03-01: sale 10/customer_key 101/10.01, 20/101/10.01, 30/102/0.00. Dimension có hai dòng 101/North, một dòng 102/South. Report kỳ vọng: North count 2 total 20.02; South count 1 total 0.00. Report JOIN quan sát có North count 4 total 40.04; South đúng. North sai hai field nhưng là một dòng report JOIN sai; không có grain report trùng. Kết quả kỳ vọng violation_count = 1. SUM(DISTINCT amount) cho North 10.01 và loại nhầm một sale thật cùng giá.',
            'Xem sy_fact, số match customer_key sy_dimension, sy_expected_report và sy_report. Chạy từng SELECT thực hành riêng; editor nhận một statement, ví dụ được cung cấp xem count dimension. Chạy publication local dựng lại sy_report bằng JOIN fact/dimension theo customer_key, GROUP BY ngày/vùng. Dimension trùng vẫn gây fanout khi chạy lại; so evidence report trước-sau rồi chạy lại QA. Đặt lại nạp scenario đã chọn. Import sy_staging, sy_dimension, sy_fact, sy_report quan sát; report kỳ vọng vẫn độc lập.',
            'FULL JOIN theo CẢ sale_date và region; đếm nhóm thiếu/thừa hoặc khác sale_count/total một lần mỗi dòng report JOIN rồi cộng nhóm (sale_date,region) trùng. Không đếm mỗi sale bị nhân thành một lỗi report riêng. Region thay đổi có thể gây cả nhóm thiếu và nhóm thừa. Tổng 0 hợp lệ vẫn bắt buộc có. Query kiểm tra giá trị report, không xác định nguyên nhân fanout hay mọi fact.',
            'Không group/đối soát chỉ theo region, tính lại sự thật qua cùng JOIN sai, dùng tổng float hay sửa fanout bằng SUM(DISTINCT amount). Nhóm report trùng khác match dimension trùng.',
            '1. FULL JOIN sy_expected_report e với sy_report a USING(sale_date,region) giữ đủ grain báo cáo và nhóm không match.\n2. WHERE xét key sale_date vắng hoặc sale_count/total IS DISTINCT FROM. COUNT(*) đếm dòng report JOIN sai, so NULL an toàn.\n3. GROUP BY sale_date,region HAVING COUNT(*)>1 tìm nhóm output lặp, độc lập với dimension trùng.\n4. Cộng: North góp 1 dù cả count lẫn total sai; nhóm report trùng góp 0. Số thập phân chính xác giữ 20.02 và 40.04.',
        ),
    },
    'lab_035_azure_manifest': {
        'ENG': (
            'Azure storage can hold data-lake files; here a manifest is a list of expected deliveries, not a live listing. az_expected_files defines file_id and exact path, route (destination category) and byte_count. az_files records observations with observed_at/run_id. The grain is one file identity, unlike OneLake partition row totals. Paths are labels only, not proof a file exists or permission to open it.',
            'A delivery has the expected number of files but one belongs in another folder, one is duplicated and another is missing. Data QA checks file identities and routing instead of approving a plausible file count.',
            'Illustrative expected: F1 /orders/a.csv orders 100 bytes; F2 /orders/b.csv orders 200; F3 /orders/c.csv orders 0. Observed: F1 /wrong/a.csv customers 100; F2 correct twice; F4 /orders/d.csv orders 50; F3 absent. F1 wrong path and route counts once (1), missing F3 (1), unexpected F4 (1), repeated F2 group (1). Expected violation_count = 4. A required zero-byte file is not automatically missing.',
            'Inspect az_expected_files and az_files in Observed evidence and independent expectations; compare full path, route, byte_count, capture time and run links. Capture observations records a new local run/step but retains existing az_files; it neither lists real storage nor repairs routing or refreshes row capture timestamps. Compare rows and steps before/after, then rerun QA. Reset simulator reloads the chosen scenario; imported evidence is locked until Reset. Import only az_files observations, never az_expected_files. Reported schema/manifest/reference panels are not populated foundation file tables; use the observed datasets panel.',
            'FULL JOIN by file_id; count absent keys or differing path/route/byte_count once per joined row plus duplicate file_id groups. Exact path labels are compared as text, not normalized or opened. observed_at and run_id are not fields in this diagnostic, although missing/future capture and missing run context can keep evidence NOT_VERIFIED. Zero cannot prove physical existence, contents, permissions or a complete real lake listing.',
            'Do not substitute file counts for identity checks, count two wrong fields twice, or use path as a unique key when the contract key is file_id. Capture SUCCESS is not a repaired manifest.',
            '1. FULL JOIN az_expected_files e and az_files a USING(file_id) exposes absent and extra identities.\n2. WHERE checks missing IDs or path/route/byte_count IS DISTINCT FROM; COUNT(*) counts a failing joined file row once.\n3. GROUP BY file_id HAVING COUNT(*)>1 finds repeated observed identities, with an outer COUNT of groups.\n4. Add: 3 failing file rows + 1 duplicate group = 4. No filesystem call or authorization decision occurs in this SQL.',
        ),
        'VIE': (
            'Azure storage có thể lưu file data lake; ở đây manifest là danh sách chuyến giao kỳ vọng, không phải listing thật. az_expected_files định nghĩa file_id, path chính xác, route (loại đích) và byte_count. az_files ghi observation có observed_at/run_id. Grain là một danh tính file, khác tổng dòng partition OneLake. Path chỉ là nhãn, không chứng minh file tồn tại hay cho phép mở file.',
            'Chuyến giao có đúng số file nhưng một file vào sai folder, một file lặp và file khác thiếu. Data QA kiểm tra danh tính/routing thay vì duyệt theo file count có vẻ đúng.',
            'Kỳ vọng minh họa: F1 /orders/a.csv orders 100 byte; F2 /orders/b.csv orders 200; F3 /orders/c.csv orders 0. Quan sát: F1 /wrong/a.csv customers 100; F2 đúng hai lần; F4 /orders/d.csv orders 50; thiếu F3. F1 sai path và route tính một (1), thiếu F3 (1), thừa F4 (1), nhóm F2 lặp (1). Kết quả kỳ vọng violation_count = 4. File 0 byte bắt buộc không tự coi là thiếu.',
            'Xem az_expected_files và az_files trong Evidence quan sát và kỳ vọng độc lập; so đầy đủ path, route, byte_count, capture time, liên kết run. Capture observation ghi run/step local mới nhưng giữ az_files hiện có; không liệt kê storage thật, sửa routing hay làm mới timestamp capture từng dòng. So dòng và step trước-sau rồi chạy lại QA. Đặt lại simulator nạp scenario đã chọn; evidence import khóa thao tác đến khi Đặt lại. Chỉ import az_files, không az_expected_files. Panel schema/manifest/reference không chứa bảng file foundation; dùng panel dataset quan sát.',
            'FULL JOIN theo file_id; đếm key vắng hoặc khác path/route/byte_count một lần mỗi dòng JOIN cộng nhóm file_id trùng. So nhãn path đúng dạng text, không chuẩn hóa hay mở. observed_at, run_id không nằm trong diagnostic này, nhưng capture thiếu/tương lai và context run thiếu có thể giữ evidence NOT_VERIFIED. Số 0 không chứng minh tồn tại vật lý, nội dung, quyền hay listing lake thật đầy đủ.',
            'Không dùng file count thay check danh tính, đếm hai field sai thành hai lỗi hay dùng path làm key duy nhất khi contract dùng file_id. Capture SUCCESS không có nghĩa manifest đã sửa.',
            '1. FULL JOIN az_expected_files e với az_files a USING(file_id) hiển thị danh tính thiếu/thừa.\n2. WHERE xét ID vắng hoặc path/route/byte_count IS DISTINCT FROM; COUNT(*) đếm một dòng file JOIN sai một lần.\n3. GROUP BY file_id HAVING COUNT(*)>1 tìm danh tính quan sát lặp; COUNT ngoài đếm nhóm.\n4. Cộng: 3 dòng file sai + 1 nhóm trùng = 4. SQL không gọi filesystem hay quyết định cấp quyền.',
        ),
    },
    'lab_036_azure_access': {
        'ENG': (
            'Azure uses authorization to control resource access; this lesson only investigates recorded observations. Identity is who attempted access; scope is the resource label; operation is the attempted action. az_required_access independently defines the required observation_id/identity_id/scope/operation. az_access records outcome and capture time. DENIED is an observed access error; absent or unknown observations are incomplete evidence, not proof of bad data.',
            'A data check cannot inspect a feed because access was denied. Reporting a data defect would confuse an access problem with unseen data. Data QA records the denial and missing evidence, then identifies what needs investigation.',
            'Illustrative required observations A/B/C/D each have identity user-A/B/C/D, scope /orders, operation READ. At as_of 2026-03-01T12:00:00Z, observed A matches and is ALLOWED at exactly as_of (0); B matches but DENIED (1); C ALLOWED but identity NULL (1); D absent (1); extra X/user-X/READ is ALLOWED (1). Expected violation_count = 4. This is an evidence-investigation count, not four data defects. Several failing predicates on C would still count once.',
            'Inspect az_required_access, az_access and cloud_context as_of with the guided FULL JOIN. Compare required identities/scopes/operations, outcomes, UTC times and missing observations. Capture observations retains rows and records a local run/step; it never grants access or fabricates ALLOWED. A DENIED row makes execution FAILED/access ACCESS_ERROR; incomplete identity/scope/time or missing observations make access INCOMPLETE if there is no denial. Evidence gaps keep quality NOT_VERIFIED. Reset reloads the selected scenario, not a permissions fix. Import only az_access observations; expected access remains built-in.',
            'Count failing FULL JOIN rows: absent/extra observation IDs, differing identity/scope/operation, outcome not ALLOWED, NULL observed_at/as_of or observed_at>as_of; add repeated observation_id groups. Exactly as_of passes; no freshness age threshold exists here. DENIED outranks incomplete in the access badge. ALLOWED alone does not establish correct data or future authorization. A complete zero diagnostic can give PASS for access_evidence only; the same label is not a data-quality verdict.',
            'Do not filter to ALLOWED and hide denials, invent identities for NULL, assume a recent timestamp grants access, or call a DENIED observation a data defect. Imported outcome is a claim, not enforced authorization.',
            '1. FULL JOIN az_required_access e with az_access a USING(observation_id) keeps missing and unexpected observations.\n2. CROSS JOIN the single cloud_context row supplies the fixed as_of boundary.\n3. WHERE uses OR to select absent IDs, NULL-safe differing identity/scope/operation, outcome IS DISTINCT FROM ALLOWED, missing capture/context or future capture. COUNT(*) counts each selected joined row once.\n4. GROUP BY observation_id HAVING COUNT(*)>1 counts duplicate groups separately; add both counts. A passes at the inclusive boundary; B,C,D,X contribute 4. This SELECT evaluates reported evidence, not cloud permissions or data contents.',
        ),
        'VIE': (
            'Azure dùng cấp quyền để kiểm soát truy cập resource; bài này chỉ điều tra observation được ghi. Identity là ai thử truy cập; scope là nhãn resource; operation là thao tác đã thử. az_required_access định nghĩa độc lập observation_id/identity_id/scope/operation cần có. az_access ghi outcome và capture time. DENIED là lỗi truy cập quan sát; observation vắng/chưa biết là evidence thiếu, không chứng minh dữ liệu xấu.',
            'Check dữ liệu không đọc được feed vì truy cập bị từ chối. Báo lỗi dữ liệu sẽ nhầm vấn đề access với dữ liệu chưa thấy. Data QA ghi denial và evidence thiếu rồi xác định điều cần điều tra.',
            'Observation A/B/C/D kỳ vọng minh họa lần lượt có identity user-A/B/C/D, scope /orders, operation READ. Với as_of 2026-03-01T12:00:00Z, A khớp, ALLOWED đúng as_of (0); B khớp nhưng DENIED (1); C ALLOWED nhưng identity NULL (1); D vắng (1); X/user-X/READ thừa, ALLOWED (1). Kết quả kỳ vọng violation_count = 4. Đây là số điều tra evidence, không phải bốn lỗi dữ liệu. C sai nhiều điều kiện vẫn tính một.',
            'Xem az_required_access, az_access, cloud_context as_of bằng FULL JOIN hướng dẫn. So identity/scope/operation kỳ vọng, outcome, giờ UTC, observation thiếu. Capture observation giữ dòng, ghi run/step local; không cấp quyền hay tự tạo ALLOWED. Dòng DENIED làm execution FAILED/access ACCESS_ERROR; identity/scope/time thiếu hoặc observation vắng làm access INCOMPLETE nếu không có denial. Evidence thiếu giữ quality NOT_VERIFIED. Đặt lại nạp scenario đã chọn, không sửa quyền. Chỉ import az_access; access kỳ vọng vẫn dựng sẵn.',
            'Đếm dòng FULL JOIN sai: ID observation thiếu/thừa, khác identity/scope/operation, outcome không ALLOWED, observed_at/as_of NULL hoặc observed_at>as_of; cộng nhóm observation_id lặp. Đúng as_of đạt; ở đây không có ngưỡng tuổi freshness. DENIED ưu tiên hơn incomplete trong badge access. ALLOWED riêng không xác nhận dữ liệu đúng hay quyền tương lai. Diagnostic 0 đủ evidence có thể cho PASS chỉ trong phạm vi access_evidence; nhãn đó không phải kết luận chất lượng dữ liệu.',
            'Không lọc chỉ ALLOWED làm mất denial, tự gán identity cho NULL, coi timestamp gần đây là được cấp quyền hay gọi observation DENIED là lỗi dữ liệu. Outcome import là thông tin được báo, không phải cấp quyền được thực thi.',
            '1. FULL JOIN az_required_access e với az_access a USING(observation_id) giữ observation thiếu/thừa.\n2. CROSS JOIN một dòng cloud_context cung cấp biên as_of cố định.\n3. WHERE dùng OR chọn ID vắng, identity/scope/operation khác an toàn với NULL, outcome IS DISTINCT FROM ALLOWED, capture/context thiếu hoặc capture tương lai. COUNT(*) đếm mỗi dòng JOIN được chọn một lần.\n4. GROUP BY observation_id HAVING COUNT(*)>1 đếm nhóm trùng riêng rồi cộng hai số. A đạt đúng biên bao gồm; B,C,D,X góp 4. SELECT đánh giá evidence được báo, không xét quyền cloud hay nội dung dữ liệu.',
        ),
    },
})


def apply_guidance(catalog):
    for lab_id, translations in GUIDANCE.items():
        for language, parts in translations.items():
            bodies = list(parts)
            bodies[0] = SCOPE[language] + '\n' + bodies[0]
            bodies[3] += '\n' + IMPORT[language]
            bodies[4] = CHALLENGE[language] + bodies[4]
            bodies[6] = SCOPE[language] + '\n' + bodies[6]
            def section(index):
                return LABELS[language][index] + '\n' + bodies[index]
            text = catalog[lab_id][language]
            text['theory'] = '\n\n'.join(section(i) for i in (0,1,2,3,5))
            text['requirement'] += '\n\n' + section(4)
            text['explanation'] = section(6)
