"""Six separately authored ENG/VIE learning paths, executed by PostgreSQL."""
from backend.app.learning import foundations as f

# Introduction, purpose and the exact learner metric are written per lesson.
TEXT = [
    ('Account for accepted, rejected and quarantined records','Đối soát dòng accepted, rejected và quarantined',
     'An accepted record can enter the published dataset. A rejected record violates a known rule; quarantine retains a record needing investigation. The exercise contract gives each record exactly one destination: customer_id <= 0 is REJECTED; otherwise NULL amount is QUARANTINED; otherwise ACCEPTED, including zero amounts. This precedence is an exercise policy, not a Databricks default. db_contract is an independently authored expected decision and exact amount per record_id. db_source and db_publication are observed evidence. Reconcile contract to publication by record_id, counting missing/unexpected rows or wrong classification/amount once per joined row; add duplicated record_id groups. A correct reject is not lost data. Purpose: prove every input is accounted for rather than accepting an accepted-row count alone.',
     'Dòng accepted được vào dataset publish. Dòng rejected vi phạm quy tắc đã biết; quarantine giữ dòng cần điều tra. Contract bài tập quy định đúng một đích mỗi dòng: customer_id <= 0 là REJECTED; nếu không, amount NULL là QUARANTINED; còn lại ACCEPTED, kể cả amount 0. Thứ tự này là policy bài tập, không phải mặc định Databricks. db_contract định nghĩa độc lập quyết định và amount chính xác theo record_id. db_source và db_publication là evidence quan sát được. Đối soát contract với publication theo record_id, mỗi dòng JOIN thiếu/thừa/sai classification hoặc amount tính một; cộng nhóm record_id trùng. Reject đúng không phải mất dữ liệu. Mục đích: chứng minh mọi input có đích thay vì chỉ xem count accepted.',
     'SELECT s.record_id,s.customer_id,s.amount,p.classification FROM db_source s LEFT JOIN db_publication p USING(record_id) ORDER BY s.record_id;',
     ['Inspect zero amount, invalid customer and NULL amount separately.','FULL JOIN the independent db_contract to publication and compare NULL safely.','Add duplicate record_id groups; do not count expected rejections as defects.'],
     ['Xem riêng amount 0, customer không hợp lệ và amount NULL.','FULL JOIN db_contract độc lập với publication; so sánh NULL an toàn.','Cộng nhóm record_id trùng; không tính reject đúng là lỗi.']),
    ('Reconcile version-aware before/after updates','Đối soát cập nhật before/after theo version',
     'A version is an explicit ordered revision of an order, not its arrival time. db_before holds three orders; db_incoming includes a stale version, a newer version and a new key. The policy accepts only a strictly greater version, preserves untouched orders and never deletes without a deletion contract. Equal-version replay must keep one row per order. All timestamps are the same fixed UTC boundary: choosing by timestamp cannot solve this exercise. db_expected_after independently specifies the required final key/version/amount/updated_at. Reconcile it to db_after; count missing/unexpected or differing joined rows plus duplicated order_id groups. Purpose: detect stale overwrite, duplicate replay and unintended deletion. This is final-state version reconciliation, distinct from ADF arrival batches and timestamp watermarks. RUN/REPLAY applies the actual local version guard; it cannot recover an already lost newer value without Reset.',
     'Version là revision có thứ tự rõ ràng của order, không phải thời điểm tới. db_before có ba order; db_incoming có version cũ, version mới và key mới. Policy chỉ nhận version lớn hơn, giữ order không đổi và không xóa khi chưa có contract xóa. Replay cùng version phải giữ một dòng mỗi order. Mọi timestamp ở cùng biên UTC cố định: chọn theo timestamp không giải được bài. db_expected_after định nghĩa độc lập key/version/amount/updated_at cuối. Đối soát với db_after; đếm dòng JOIN thiếu/thừa/khác cộng nhóm order_id trùng. Mục đích: phát hiện ghi đè cũ, replay trùng và xóa ngoài ý muốn. Đây là đối soát final state theo version, khác batch arrival và watermark timestamp của ADF. RUN/REPLAY áp dụng version guard local thật; không phục hồi giá trị mới đã mất nếu chưa Reset.',
     "SELECT 'before' AS snapshot,order_id,version,amount,updated_at FROM db_before UNION ALL SELECT 'incoming',order_id,version,amount,updated_at FROM db_incoming UNION ALL SELECT 'after',order_id,version,amount,updated_at FROM db_after;",
     ['Compare explicit versions, not timestamps or row positions.','Use the complete independent final contract so untouched orders remain required.','Count duplicate key groups even when all duplicate values match.'],
     ['So version rõ ràng, không dựa timestamp hay vị trí dòng.','Dùng contract cuối đầy đủ để order không đổi vẫn bắt buộc tồn tại.','Đếm nhóm key trùng ngay cả khi giá trị các dòng giống nhau.']),
    ('Validate staging-to-fact publication and dimension lookup','Kiểm tra staging-to-fact và lookup dimension',
     'A fact records a business event; a dimension supplies its descriptive identity. Staging uses customer_code while the fact stores customer_key. The expected mapping and exact amount/date for each sale_id are independently specified in sy_expected_fact. Observe sy_staging, sy_dimension and sy_fact, then FULL JOIN expected fact to actual fact by sale_id. Count missing/unexpected keys or wrong customer_key/amount/sale_date once per joined row; add duplicate sale_id groups. Purpose: detect a publication that has plausible counts but maps a sale to the wrong customer. RUN actually joins staging to the local dimension. Matching totals alone do not establish correct dimension mapping.',
     'Fact ghi một sự kiện nghiệp vụ; dimension cung cấp danh tính mô tả. Staging dùng customer_code còn fact lưu customer_key. sy_expected_fact định nghĩa độc lập mapping, amount chính xác và ngày theo sale_id. Quan sát sy_staging, sy_dimension, sy_fact rồi FULL JOIN fact kỳ vọng với fact thực tế theo sale_id. Đếm key thiếu/thừa hoặc sai customer_key/amount/sale_date một lần mỗi dòng JOIN; cộng nhóm sale_id trùng. Mục đích: phát hiện publication có count hợp lý nhưng ánh xạ sale sai customer. RUN JOIN staging với dimension local thật. Tổng tiền khớp chưa chứng minh mapping dimension đúng.',
     'SELECT s.sale_id,s.customer_code,d.customer_key,f.customer_key AS published_key FROM sy_staging s LEFT JOIN sy_dimension d USING(customer_code) LEFT JOIN sy_fact f USING(sale_id);',
     ['Identify the fact grain sale_id and the code-to-key lookup.','Compare all expected fact fields using IS DISTINCT FROM.','Use both join directions to expose equal-count key substitution.'],
     ['Xác định grain fact sale_id và lookup code sang key.','So mọi field fact kỳ vọng bằng IS DISTINCT FROM.','Dùng cả hai chiều JOIN để phát hiện thay key giữ count.']),
    ('Prove reporting grain and exact aggregates','Chứng minh grain báo cáo và aggregate chính xác',
     'Reporting grain is one row per (sale_date, region). Joining a fact to repeated dimension rows can multiply a sale before aggregation; this is JOIN fanout. sy_expected_report independently defines sale_count and exact total for each day/region, rather than reusing the observed dimension join. Inspect dimension multiplicity and sy_report. FULL JOIN the expected and actual report on both grain columns; count missing/unexpected or differing sale_count/total once per joined row plus duplicated day/region groups. Purpose: prove business totals, including a valid zero-total group. RUN actually aggregates the fact/dimension join; if dimension rows are duplicated, rerunning still produces incorrect totals. Do not fix fanout by SUM(DISTINCT amount): different sales can have equal amounts.',
     'Grain báo cáo là một dòng mỗi (sale_date, region). JOIN fact với dimension lặp có thể nhân sale trước aggregate: đó là JOIN fanout. sy_expected_report định nghĩa độc lập sale_count và total chính xác mỗi ngày/vùng, không dùng lại JOIN dimension quan sát được. Xem multiplicity dimension và sy_report. FULL JOIN báo cáo kỳ vọng và thực tế theo cả hai cột grain; đếm dòng thiếu/thừa/sai sale_count hoặc total một lần cộng nhóm ngày/vùng trùng. Mục đích: chứng minh tổng nghiệp vụ, kể cả nhóm tổng 0 hợp lệ. RUN aggregate JOIN fact/dimension thật; dimension trùng thì chạy lại vẫn sai tổng. Không sửa fanout bằng SUM(DISTINCT amount): sale khác nhau có thể có cùng amount.',
     'SELECT customer_key,COUNT(*) AS dimension_rows FROM sy_dimension GROUP BY customer_key; SELECT * FROM sy_report;',
     ['Run each SELECT separately; the SQL workspace accepts one statement.','Check the complete day/region grain and use independent totals.','Retain zero groups and detect duplicated grain groups separately.'],
     ['Chạy từng SELECT riêng; workspace SQL nhận một statement.','Kiểm tra đủ grain ngày/vùng và dùng tổng độc lập.','Giữ nhóm tổng 0; phát hiện nhóm grain trùng riêng.']),
    ('Reconcile lake manifest paths and routing','Đối soát manifest path và routing của lake',
     'A manifest declares the files expected for a delivery. az_expected_files defines file_id, exact path label, route and byte_count; az_files is the observed listing evidence with capture time and run_id. Paths are labels only: this app never reads local or cloud files from them. FULL JOIN by file_id; count missing/unexpected or wrong path/route/byte_count once per joined row plus duplicated file_id groups. Purpose: detect missing delivery, an extra file, repeated publication and wrong destination even when file counts match. RUN records the existing local evidence; it does not repair files or fetch a real Azure listing. This is per-file path/routing reconciliation, not the OneLake partition-level row-count exercise.',
     'Manifest khai báo file kỳ vọng cho một chuyến giao. az_expected_files định nghĩa file_id, nhãn path chính xác, route và byte_count; az_files là evidence listing quan sát được có thời điểm capture và run_id. Path chỉ là nhãn: app không đọc file local/cloud từ chúng. FULL JOIN theo file_id; đếm file thiếu/thừa/sai path/route/byte_count một lần mỗi dòng JOIN cộng nhóm file_id trùng. Mục đích: phát hiện giao thiếu, file thừa, publish lặp và sai đích dù file count khớp. RUN ghi lại evidence local đang có; không sửa file hoặc lấy listing Azure thật. Đây là đối soát path/routing từng file, khác bài tổng row count theo partition OneLake.',
     'SELECT file_id,path,route,byte_count,observed_at,run_id FROM az_files ORDER BY file_id;',
     ['Use file_id as the contract key and compare the complete path and route.','FULL JOIN both directions, not just observed file counts.','Add duplicate file_id groups and retain provenance.'],
     ['Dùng file_id làm key contract và so đủ path/route.','FULL JOIN hai chiều, không chỉ xem file count quan sát.','Cộng nhóm file_id trùng và giữ provenance.']),
    ('Investigate access evidence without inferring data defects','Điều tra evidence truy cập, không suy ra lỗi dữ liệu',
     'Access evidence records an observation; it does not calculate a permission decision. az_required_access independently lists observation_id, identity_id, scope and operation. FULL JOIN to az_access by observation_id. Count missing/unexpected observations, mismatched/unknown identity/scope/operation, outcome other than ALLOWED, NULL capture time or capture after context.as_of once per joined row; add duplicated observation_id groups. This violation_count is an evidence-investigation metric, not a data-defect count. DENIED is an observed access execution error; unknown identity/scope or missing/future observations are incomplete evidence. Neither proves bad data, and ALLOWED alone does not prove data correctness or future authorization. A zero metric only validates this bounded evidence contract. Purpose: identify what is known and what must be investigated. RUN retains observations and never grants permissions.',
     'Evidence truy cập ghi một observation; không tính quyết định cấp quyền. az_required_access định nghĩa độc lập observation_id, identity_id, scope, operation. FULL JOIN với az_access theo observation_id. Đếm observation thiếu/thừa, identity/scope/operation sai hoặc chưa biết, outcome khác ALLOWED, capture NULL hoặc sau context.as_of một lần mỗi dòng JOIN; cộng nhóm observation_id trùng. violation_count là chỉ số điều tra evidence, không phải số lỗi dữ liệu. DENIED là lỗi thực thi truy cập quan sát được; identity/scope chưa biết hoặc observation thiếu/tương lai là bằng chứng chưa đủ. Không trường hợp nào chứng minh dữ liệu sai; ALLOWED riêng cũng không chứng minh dữ liệu đúng hoặc quyền tương lai. Chỉ số 0 chỉ xác minh contract evidence có giới hạn này. Mục đích: xác định điều đã biết và điều cần điều tra. RUN giữ observation, không cấp quyền.',
     'SELECT e.observation_id,e.identity_id AS required_identity,a.identity_id,a.scope,a.outcome,a.observed_at,c.as_of FROM az_required_access e FULL JOIN az_access a USING(observation_id) CROSS JOIN cloud_context c;',
     ['Do not translate DENIED into a data-quality defect.','Preserve unknown identity/scope and absent observations; never fabricate ALLOWED.','Compare capture with fixed UTC as_of; a provider clock is not a local mutation revision.'],
     ['Không chuyển DENIED thành lỗi chất lượng dữ liệu.','Giữ identity/scope chưa biết và observation thiếu; không tự tạo ALLOWED.','So capture với as_of UTC cố định; đồng hồ provider không phải revision mutation local.']),
]

CATALOG={}
for index,(key,text) in enumerate(zip(f.IDS,TEXT,strict=True),31):
    title,vtitle,body,vbody,practice,hints,vhints=text
    # Guided exploration remains one read-only SELECT, never the final answer.
    practice=practice.split(';')[0]+';'
    course='databricks-testing' if index<=32 else 'synapse-testing' if index<=34 else 'azure-testing'
    track='DATABRICKS_FOUNDATIONS' if index<=32 else 'SYNAPSE_FOUNDATIONS' if index<=34 else 'AZURE_FOUNDATIONS'
    CATALOG[key]={'order':index,'course_id':course,'level':'INTERMEDIATE','track':track,'minutes':35,'scenarios':['clean',*f.SCENARIOS[key]]}
    for lang,heading,theory,clues in (('ENG',title,body,hints),('VIE',vtitle,vbody,vhints)):
        eng=lang=='ENG'
        limits=('Local PostgreSQL SIMULATED/IMPORTED evidence only. No Spark execution, Delta transaction log, time travel, distributed Synapse engine or Azure authorization evaluation. PostgreSQL DISTINCT ON/IS DISTINCT FROM are not portable provider SQL. ' if eng else
                'Chỉ có evidence PostgreSQL local SIMULATED/IMPORTED. Không thực thi Spark, transaction log Delta, time travel, engine Synapse phân tán hay đánh giá cấp quyền Azure. DISTINCT ON/IS DISTINCT FROM của PostgreSQL không phải SQL dùng trực tiếp cho mọi provider. ')
        CATALOG[key][lang]={
            'title':heading,'summary':heading,'objectives':[heading,'Justify conclusions using independent keys, exact values and observable evidence.' if eng else 'Giải thích kết luận theo key độc lập, giá trị chính xác và evidence quan sát được.'],
            'theory':limits+theory,
            'steps':(['Start a clean SANDBOX and identify the grain and independent expected table.','Run the guided SELECT; inspect the matching observed tables in the evidence workspace.','Start the named fault and compare missing, unexpected, mismatched and duplicate keys.','Write the defined violation_count check; use RUN/REPLAY or Reset and rerun after mutation.','Export/import the typed JSON in another SANDBOX; inspect context and provenance.','Start CHALLENGE, read its requirement before the answer field, submit SQL and a written explanation, then resume saved history.'] if eng else
                     ['Mở SANDBOX sạch, xác định grain và bảng kỳ vọng độc lập.','Chạy SELECT hướng dẫn; xem bảng quan sát tương ứng trong workspace evidence.','Mở lỗi cụ thể, so key thiếu, thừa, sai và trùng.','Viết kiểm tra violation_count theo định nghĩa; dùng RUN/REPLAY hoặc Reset rồi kiểm tra lại.','Export/import JSON typed sang SANDBOX khác; xem context và provenance.','Mở CHALLENGE, đọc yêu cầu trước ô trả lời, nộp SQL cùng giải thích rồi tiếp tục lịch sử đã lưu.']),
            'practice_sql':practice,'practice_expected':'Exploration exposes evidence; it is not the complete acceptance check.' if eng else 'Khám phá hiển thị evidence; chưa phải kiểm tra chấp nhận đầy đủ.',
            'requirement':('Return one non-negative integer column named violation_count. ' if eng else 'Trả một cột số nguyên không âm tên violation_count. ')+theory,
            'hints':clues,'explanation':limits+theory+(' Written answers are saved, not semantically graded.' if eng else ' Câu trả lời viết được lưu, không chấm ngữ nghĩa.'),
        }
from backend.app.learning.foundations_contracts import columns
GRAINS={'db_source':'record_id','db_contract':'record_id','db_publication':'record_id (duplicates observable)',
        'db_before':'order_id','db_incoming':'order_id, version','db_expected_after':'order_id','db_after':'order_id (duplicates observable)',
        'sy_staging':'sale_id','sy_dimension':'customer_code/customer_key (multiplicity observable)',
        'sy_expected_fact':'sale_id','sy_fact':'sale_id','sy_expected_report':'sale_date, region','sy_report':'sale_date, region',
        'az_expected_files':'file_id','az_files':'file_id','az_required_access':'observation_id','az_access':'observation_id'}
SCHEMA={name:{'grain':GRAINS[name],'columns':{n:'numeric(14,2)' if t=='numeric' else t for n,t in columns(name)}}
        for name in GRAINS}
