"""Beginner guidance in existing theory/requirement/explanation string fields.

Examples are illustrative, not session fixtures. Reference SQL stays private.
"""
LABELS = {
    "ENG": ("What are we checking?", "Why does this matter?", "Small worked example — illustrative", "Common mistake", "Challenge explained", "Solution explained"),
    "VIE": ("Chúng ta đang kiểm tra gì?", "Vì sao điều này quan trọng?", "Ví dụ nhỏ — chỉ để minh họa", "Lỗi thường gặp", "Giải thích thử thách", "Giải thích lời giải"),
}


def sections(language, parts):
    labels = LABELS[language]
    return "\n\n".join(labels[index] + "\n" + body for index, body in parts)


GUIDANCE = {
    "lab_004_duplicates": {
        "ENG": (
            "Check that target_orders has one row per order_id. A key identifies an order; the grain is what one row represents. Here the intended grain is one order, so repeated order_id values break the rule even when other columns differ.",
            "A payment report publishes order 10 three times after a retry. A dashboard can count the same sale repeatedly. Data QA identifies which order keys repeat before trusting the report.",
            "target_orders has five rows with order_id values [10, 10, 10, 20, 30]. Key 10 forms one duplicate group; 20 and 30 occur once. Expected violation_count = 1, not 2 extra rows and not 3 rows belonging to duplicates.",
            "Counting COUNT(*) minus COUNT(DISTINCT order_id) measures excess rows. For this example it gives 2, which is the wrong metric. Comparing all columns with DISTINCT can miss a repeated key whose amount differs.",
            "Return exactly one row and one non-negative integer column named violation_count. Count order_id groups occurring more than once in target_orders. A group of three or ten rows still contributes 1. Zero means no repeated key; it does not prove completeness or correct amounts. Your written answer is saved, not semantically graded.",
            "1. The inner SELECT reads target_orders. GROUP BY order_id gathers all rows for each order key.\n2. COUNT(*) measures the size of each group. HAVING COUNT(*) > 1 keeps only repeated keys; HAVING filters groups after aggregation, while WHERE would filter individual input rows.\n3. The subquery is named duplicate_keys so the outer SELECT can treat its result as a small table.\n4. The outer COUNT(*) counts duplicate groups, not their member rows. AS violation_count gives the required column name. The five-row illustration therefore returns 1.",
        ),
        "VIE": (
            "Kiểm tra target_orders có đúng một dòng cho mỗi order_id. Key là giá trị nhận diện một order; grain là ý nghĩa của một dòng dữ liệu. Bài này có grain một order, nên order_id lặp lại là vi phạm dù các cột khác có giá trị khác nhau.",
            "Sau một lần chạy lại, báo cáo thanh toán ghi order 10 ba lần. Dashboard có thể tính cùng một giao dịch nhiều lần. Data QA tìm các key bị lặp trước khi tin vào báo cáo.",
            "target_orders có năm dòng với order_id [10, 10, 10, 20, 30]. Key 10 tạo một nhóm trùng; 20 và 30 chỉ xuất hiện một lần. Kết quả kỳ vọng violation_count = 1, không phải 2 dòng dư hay 3 dòng thuộc nhóm trùng.",
            "COUNT(*) trừ COUNT(DISTINCT order_id) đo số dòng dư. Ví dụ này trả 2, khác chỉ số bài yêu cầu. DISTINCT trên toàn bộ cột có thể bỏ sót key lặp nếu amount khác nhau.",
            "Trả đúng một dòng, một cột số nguyên không âm tên violation_count. Đếm nhóm order_id xuất hiện nhiều hơn một lần trong target_orders. Nhóm có ba hay mười dòng vẫn đóng góp 1. Kết quả 0 chỉ nói không có key lặp; chưa chứng minh đủ key hay đúng số tiền. Câu trả lời được lưu, không được chấm theo ý nghĩa.",
            "1. SELECT bên trong đọc target_orders. GROUP BY order_id gom các dòng theo key order.\n2. COUNT(*) đếm số dòng mỗi nhóm. HAVING COUNT(*) > 1 giữ nhóm có key lặp; HAVING lọc sau khi tổng hợp, còn WHERE lọc từng dòng đầu vào.\n3. Truy vấn con được đặt tên duplicate_keys để SELECT bên ngoài xem kết quả như một bảng nhỏ.\n4. COUNT(*) bên ngoài đếm số nhóm trùng, không đếm các dòng trong nhóm. AS violation_count đặt tên cột theo yêu cầu. Ví dụ năm dòng trả về 1.",
        ),
    },
}


GUIDANCE.update({
    "lab_002_sql_basics": {
        "ENG": (
            "Find target_orders rows whose customer_id is zero or negative. A table holds rows (records) and columns (fields). SELECT reads data; a business rule says which values are acceptable. Here every order needs a positive customer_id.",
            "A checkout export uses customer_id = 0 when a customer lookup fails. The order exists, but analysts cannot associate it with a real customer. Data QA counts these invalid identifiers before publishing customer reports.",
            "Three target_orders rows: (order_id, customer_id) = (10, 7), (20, 0), (30, -2). Orders 20 and 30 violate the rule. Expected violation_count = 2; order 10 contributes 0.",
            "customer_id < 0 misses zero. Counting all rows answers the dataset-size question. NULL means unknown, not zero: customer_id <= 0 does not select NULL, and this lesson's fixtures test zero/negative values.",
            "Return one row with one non-negative integer column named violation_count: the number of target_orders rows with customer_id <= 0. Count rows, not distinct customers. This is a narrow value check, not a check that customers exist in another table. A written explanation is saved, not semantically graded.",
            "1. FROM target_orders chooses the observed table; Source is not needed for this rule.\n2. WHERE customer_id <= 0 keeps only rows with zero or negative customer identifiers. WHERE filters individual rows before counting.\n3. COUNT(*) counts the remaining rows, including two orders sharing the same invalid identifier.\n4. AS violation_count names the sole output column. No matching rows returns 0, not an empty result.",
        ),
        "VIE": (
            "Tìm dòng target_orders có customer_id bằng 0 hoặc âm. Bảng gồm các dòng (bản ghi) và cột (trường dữ liệu). SELECT đọc dữ liệu; quy tắc nghiệp vụ xác định giá trị nào hợp lệ. Bài này yêu cầu customer_id của order phải dương.",
            "File xuất từ checkout dùng customer_id = 0 khi không tìm được khách hàng. Order vẫn tồn tại nhưng không thể gắn với khách hàng thật. Data QA đếm ID không hợp lệ trước khi công bố báo cáo khách hàng.",
            "Ba dòng target_orders: (order_id, customer_id) = (10, 7), (20, 0), (30, -2). Order 20 và 30 vi phạm. Kết quả kỳ vọng violation_count = 2; order 10 đóng góp 0.",
            "customer_id < 0 bỏ sót số 0. Đếm tất cả dòng chỉ đo kích thước dữ liệu. NULL nghĩa là chưa biết, không phải 0: customer_id <= 0 không chọn NULL; fixtures của bài kiểm tra giá trị 0/âm.",
            "Trả một dòng, một cột số nguyên không âm tên violation_count: số dòng target_orders có customer_id <= 0. Đếm dòng, không đếm khách hàng khác nhau. Đây là kiểm tra giá trị cụ thể, chưa kiểm tra khách hàng tồn tại trong bảng khác. Phần giải thích được lưu, không được chấm theo ý nghĩa.",
            "1. FROM target_orders chọn bảng cần quan sát; quy tắc này không cần Source.\n2. WHERE customer_id <= 0 giữ dòng có ID khách hàng bằng 0 hoặc âm. WHERE lọc từng dòng trước khi đếm.\n3. COUNT(*) đếm dòng còn lại, kể cả hai order dùng cùng một ID không hợp lệ.\n4. AS violation_count đặt tên cột kết quả duy nhất. Không có dòng vi phạm thì trả 0, không trả tập kết quả rỗng.",
        ),
    },
    "lab_003_nulls": {
        "ENG": (
            "Check whether target_orders.net_amount is missing. NULL represents an unknown or absent value. It differs from a known amount of 0.00; a zero-value order can be valid.",
            "A mapping error leaves a refund-adjusted amount empty. Revenue may be understated because sums ignore NULL values. Data QA checks required amounts rather than assuming a successful load filled every field.",
            "Three target_orders rows: (order_id, net_amount) = (10, 10.00), (20, NULL), (30, 0.00). Only order 20 has an absent amount. Expected violation_count = 1; the zero on order 30 is valid for this check.",
            "net_amount = NULL does not test for missing data: ordinary comparisons with NULL are unknown. Replacing NULL with 0 before checking hides the missing value. Missing order keys need a separate completeness check.",
            "Return one row and one non-negative integer column named violation_count. Count target_orders rows where net_amount IS NULL; do not count zero amounts. If two rows have NULL, count 2, even if they share a key. A written answer is saved, not semantically graded.",
            "1. FROM target_orders reads observed order amounts.\n2. WHERE net_amount IS NULL tests absence explicitly; IS NULL is the SQL predicate for this purpose.\n3. COUNT(*) counts selected rows. COUNT(net_amount) would count none of those rows because that function skips NULL.\n4. AS violation_count supplies the output name. The three-row illustration returns 1.",
        ),
        "VIE": (
            "Kiểm tra target_orders.net_amount có bị thiếu không. NULL biểu diễn giá trị chưa biết hoặc chưa có. NULL khác số tiền đã biết là 0.00; order có giá trị 0 vẫn có thể hợp lệ.",
            "Lỗi ánh xạ để trống số tiền sau khi trừ hoàn tiền. Tổng doanh thu có thể bị thấp vì phép cộng bỏ qua NULL. Data QA kiểm tra trường bắt buộc thay vì cho rằng load thành công thì mọi trường đều có dữ liệu.",
            "Ba dòng target_orders: (order_id, net_amount) = (10, 10.00), (20, NULL), (30, 0.00). Chỉ order 20 thiếu số tiền. Kết quả kỳ vọng violation_count = 1; số 0 của order 30 hợp lệ với kiểm tra này.",
            "net_amount = NULL không kiểm tra được giá trị thiếu: so sánh thông thường với NULL cho kết quả chưa biết. Đổi NULL thành 0 trước khi kiểm tra sẽ che dữ liệu thiếu. Key order bị mất cần kiểm tra completeness riêng.",
            "Trả một dòng, một cột số nguyên không âm tên violation_count. Đếm dòng target_orders có net_amount IS NULL; không đếm số tiền bằng 0. Hai dòng có NULL thì tính 2, kể cả khi cùng key. Câu trả lời được lưu, không được chấm theo ý nghĩa.",
            "1. FROM target_orders đọc số tiền order đang quan sát.\n2. WHERE net_amount IS NULL kiểm tra trực tiếp giá trị thiếu; IS NULL là điều kiện SQL cho việc này.\n3. COUNT(*) đếm dòng đã lọc. COUNT(net_amount) sẽ không đếm dòng nào trong nhóm này vì hàm đó bỏ qua NULL.\n4. AS violation_count đặt tên cột kết quả. Ví dụ ba dòng trả về 1.",
        ),
    },
    "lab_001_record_count": {
        "ENG": (
            "Check that the same order keys exist in source_orders and target_orders. A business key identifies the real-world record; here it is order_id. Completeness means no expected key is missing and no unexpected key has appeared.",
            "An export loses order 30 but accidentally adds order 40. Source and Target still have three rows each, so a row-count check looks healthy. Data QA compares identities as well as sizes.",
            "Source order_id values [10, 20, 30]; Target [10, 20, 40]. Missing keys = {30}, unexpected keys = {40}. Expected violation_count = 2 (1 missing + 1 unexpected), although both row counts equal 3.",
            "Subtracting row counts returns 0 for a key replacement. Comparing only Source to Target misses unexpected keys. Set comparison ignores repeated copies, so it is not a uniqueness test.",
            "Return one row and one non-negative integer column named violation_count. Add the number of distinct Source keys absent from Target to the number of distinct Target keys absent from Source. One replacement contributes 2. Duplicate copies do not add set differences. Written answers are saved, not semantically graded.",
            "1. The first EXCEPT returns Source order_id values not present in Target. EXCEPT is a set difference: it removes repeated copies of a value.\n2. Its outer COUNT(*) counts the missing_keys result.\n3. The second EXCEPT reverses the direction; its COUNT(*) counts unexpected_keys.\n4. The two parenthesized scalar subqueries each produce one number. Adding them and naming the result violation_count yields 2 in the illustration. Zero proves matching key sets, not correct amounts or unique rows.",
        ),
        "VIE": (
            "Kiểm tra source_orders và target_orders có cùng các key order. Business key là giá trị nhận diện bản ghi ngoài thực tế; ở đây là order_id. Completeness nghĩa là không mất key kỳ vọng và không xuất hiện key ngoài kỳ vọng.",
            "File xuất làm mất order 30 nhưng thêm nhầm order 40. Source và Target vẫn có ba dòng nên kiểm tra số lượng có vẻ tốt. Data QA đối chiếu danh tính bản ghi bên cạnh số lượng.",
            "Source có order_id [10, 20, 30]; Target có [10, 20, 40]. Key thiếu = {30}, key thừa = {40}. Kết quả kỳ vọng violation_count = 2 (1 key thiếu + 1 key thừa), dù hai bảng đều có 3 dòng.",
            "Trừ hai row count sẽ trả 0 khi key bị thay thế. Chỉ so Source sang Target sẽ bỏ sót key thừa. So tập hợp bỏ qua bản sao lặp lại, nên chưa kiểm tra tính duy nhất.",
            "Trả một dòng, một cột số nguyên không âm tên violation_count. Cộng số key Source khác nhau không có ở Target với số key Target khác nhau không có ở Source. Một lần thay key đóng góp 2. Các bản sao cùng key không làm tăng chênh lệch tập hợp. Câu trả lời được lưu, không được chấm theo ý nghĩa.",
            "1. EXCEPT đầu tiên lấy order_id của Source không có trong Target. EXCEPT là phép lấy phần khác của hai tập hợp và loại các bản sao của cùng giá trị.\n2. COUNT(*) bên ngoài đếm kết quả missing_keys.\n3. EXCEPT thứ hai đảo chiều; COUNT(*) của nó đếm unexpected_keys.\n4. Mỗi truy vấn con trong ngoặc trả một số. Cộng hai số và đặt tên violation_count cho kết quả 2 trong ví dụ. Kết quả 0 chứng minh hai tập key khớp, chưa chứng minh đúng số tiền hay không trùng dòng.",
        ),
    },
    "lab_005_calculations": {
        "ENG": (
            "Check each matched order's calculated net_amount against gross_amount - discount_amount - refund_amount from Source. JOIN matches rows by order_id. NUMERIC is an exact decimal type, appropriate for money.",
            "A transformation forgets to subtract a refund or changes a cent. The load can succeed and row counts can match while customer revenue is wrong. Data QA recomputes the expected amount independently.",
            "Three Source rows (order_id, gross_amount, discount_amount, refund_amount): (10, 100.00, 10.00, 5.00), (20, 10.01, 0.00, 0.00), (30, 0.00, 0.00, 0.00). Target net_amount values: 10→85.00, 20→10.02, 30→NULL. Expected amounts are 85.00, 10.01, 0.00. Orders 20 and 30 each contribute 1; expected violation_count = 2.",
            "Floating-point conversion or rounding can conceal a cent. Using <> alone misses a NULL actual amount. This inner JOIN does not detect missing keys, and duplicate Target matches can create multiple joined rows.",
            "Return one row and one non-negative integer column named violation_count: count joined Source/Target rows with a distinct expected versus actual amount, including NULL versus a known amount. Compare exact decimals without tolerance. Missing keys are outside this check. Written answers are saved, not semantically graded.",
            "1. FROM source_orders s JOIN target_orders t ON s.order_id=t.order_id aligns matching orders; s and t are short table aliases.\n2. Compute s.gross_amount-s.discount_amount-s.refund_amount without converting NUMERIC to float.\n3. IS DISTINCT FROM compares safely with NULL: NULL and a known amount differ; two NULLs do not. Source fixture amounts are known.\n4. COUNT(*) counts joined rows whose amount differs; AS violation_count names the output. The example returns 2. Completeness and duplicate-group checks are separate requirements.",
        ),
        "VIE": (
            "Kiểm tra net_amount của từng order ghép được có bằng gross_amount - discount_amount - refund_amount từ Source. JOIN ghép dòng theo order_id. NUMERIC là kiểu số thập phân chính xác, phù hợp với tiền.",
            "Phép biến đổi quên trừ hoàn tiền hoặc làm lệch một cent. Load vẫn thành công và số dòng vẫn bằng nhau nhưng doanh thu khách hàng sai. Data QA tự tính lại số tiền kỳ vọng.",
            "Ba dòng Source (order_id, gross_amount, discount_amount, refund_amount): (10, 100.00, 10.00, 5.00), (20, 10.01, 0.00, 0.00), (30, 0.00, 0.00, 0.00). Target có net_amount: 10→85.00, 20→10.02, 30→NULL. Kỳ vọng là 85.00, 10.01, 0.00. Order 20 và 30 mỗi order đóng góp 1; kết quả kỳ vọng violation_count = 2.",
            "Đổi sang số thực float hoặc làm tròn có thể che sai lệch một cent. Chỉ dùng <> sẽ bỏ sót actual NULL. INNER JOIN này không tìm key thiếu; Target trùng key có thể tạo nhiều dòng ghép.",
            "Trả một dòng, một cột số nguyên không âm tên violation_count: đếm dòng Source/Target đã ghép có số tiền kỳ vọng khác thực tế, kể cả NULL so với số tiền đã biết. So decimal chính xác, không dùng dung sai. Key thiếu ngoài phạm vi kiểm tra này. Câu trả lời được lưu, không được chấm theo ý nghĩa.",
            "1. FROM source_orders s JOIN target_orders t ON s.order_id=t.order_id ghép order có key khớp; s và t là tên viết tắt của bảng.\n2. Tính s.gross_amount-s.discount_amount-s.refund_amount, không đổi NUMERIC sang float.\n3. IS DISTINCT FROM so an toàn với NULL: NULL khác số đã biết; hai NULL không khác nhau. Các số tiền Source trong fixtures đều đã biết.\n4. COUNT(*) đếm dòng đã ghép có số tiền khác; AS violation_count đặt tên cột. Ví dụ trả 2. Kiểm tra key thiếu và nhóm trùng là yêu cầu riêng.",
        ),
    },
    "lab_006_capstone": {
        "ENG": (
            "Combine five checks: order key completeness, required amounts, repeated order keys, exact order calculations and daily reconciliation. Grain means what one row represents: order tables contain orders; daily tables contain UTC calendar days.",
            "A pipeline reports SUCCESS yet publishes an empty amount and a wrong daily total. Data QA must check both detailed orders and the report used by finance. Execution success means the job ran, not that its output is correct.",
            "Source has orders 10, 20, 30 with expected net amounts 10.00, 20.00, 0.00, all on 2026-01-01 UTC. Target has the same keys with amounts 10.00, NULL, 0.00. Gold daily row: (2026-01-01, order_count=3, net_revenue=30.00); Target daily row: (2026-01-01, 3, 10.00). Counts: key differences 0, NULL rows 1, duplicate groups 0, amount mismatches 1, daily mismatch rows 1. Expected violation_count = 3; this is not three distinct bad orders.",
            "Adding checks can count one underlying defect more than once. COUNT(*) on a daily table counts days, not orders. Gold is the specified daily baseline; this check does not independently prove Gold itself is correct.",
            "Return one row and one non-negative integer column named violation_count: the sum of the five documented counts in the original contract above. A daily row counts once even when both order_count and net_revenue differ. A NULL order amount can contribute to both the NULL and calculation counts. Explain the evidence in your saved answer; its meaning is not automatically graded.",
            "1. The first scalar subquery adds both EXCEPT key differences, as in the completeness lesson.\n2. The second counts net_amount IS NULL rows. The third groups order_id and counts groups with more than one row.\n3. The fourth JOIN matches order keys and compares the exact Source formula using IS DISTINCT FROM. It counts violating joined rows.\n4. The fifth FULL JOIN preserves days found on either side. Missing dates or distinct order_count/net_revenue make a joined daily row fail; OR means several failed fields still count as one row.\n5. Add the five scalar counts as violation_count. Gold and Target are compared at day grain, so there is no JOIN between daily rows and individual orders. The illustration gives 0+1+0+1+1=3.",
        ),
        "VIE": (
            "Kết hợp năm kiểm tra: đủ key order, số tiền bắt buộc, key order lặp, phép tính tiền chính xác và đối soát theo ngày. Grain là ý nghĩa của một dòng: bảng order chứa order, bảng ngày chứa ngày lịch UTC.",
            "Pipeline báo SUCCESS nhưng công bố số tiền trống và tổng ngày sai. Data QA cần kiểm tra cả order chi tiết lẫn báo cáo tài chính. Thực thi thành công nghĩa là job chạy được, chưa có nghĩa dữ liệu đúng.",
            "Source có order 10, 20, 30 với net kỳ vọng 10.00, 20.00, 0.00, đều thuộc 2026-01-01 UTC. Target có cùng key, số tiền 10.00, NULL, 0.00. Dòng Gold ngày: (2026-01-01, order_count=3, net_revenue=30.00); dòng Target ngày: (2026-01-01, 3, 10.00). Số đếm: key khác 0, dòng NULL 1, nhóm trùng 0, dòng sai phép tính 1, dòng ngày sai 1. Kết quả kỳ vọng violation_count = 3; không phải ba order lỗi khác nhau.",
            "Cộng nhiều kiểm tra có thể tính cùng một lỗi gốc nhiều lần. COUNT(*) của bảng ngày đếm ngày, không đếm order. Gold là chuẩn ngày được quy định; kiểm tra này chưa tự chứng minh Gold đúng.",
            "Trả một dòng, một cột số nguyên không âm tên violation_count: tổng năm số đếm trong contract gốc bên trên. Một dòng ngày chỉ tính một lần dù cả order_count và net_revenue sai. Một amount NULL có thể đóng góp ở cả số đếm NULL và phép tính. Giải thích bằng chứng trong câu trả lời được lưu; nội dung không được chấm tự động theo ý nghĩa.",
            "1. Truy vấn con thứ nhất cộng hai chiều EXCEPT của key như bài completeness.\n2. Truy vấn thứ hai đếm dòng net_amount IS NULL. Truy vấn thứ ba nhóm order_id và đếm nhóm có nhiều hơn một dòng.\n3. Truy vấn thứ tư JOIN theo key order và so công thức Source chính xác bằng IS DISTINCT FROM; đếm dòng ghép vi phạm.\n4. Truy vấn thứ năm FULL JOIN giữ ngày có ở một trong hai phía. Ngày thiếu hoặc order_count/net_revenue khác làm dòng ngày vi phạm; điều kiện OR khiến nhiều trường sai vẫn tính một dòng.\n5. Cộng năm số đếm thành violation_count. Gold và Target được so ở grain ngày, không JOIN dòng ngày với từng order. Ví dụ trả 0+1+0+1+1=3.",
        ),
    },
    "lab_007_join_grain": {
        "ENG": (
            "Check each order's Target total against the sum of its order_lines. A line is one item within an order; a payment is one payment transaction. Their grains differ from one total row per order.",
            "An order has two lines and two payments. Joining every line to every payment produces four rows, repeats amounts and inflates revenue: this multiplication is JOIN fanout. Data QA derives totals from lines independently of payments.",
            "order_lines: (order_id, line_id, net_amount) = (10, 1, 10.00), (10, 2, 10.00), (20, 1, 0.00). order_payments: order 10 has payment IDs 1 and 2, each 10.00; order 20 has payment ID 1, amount 0.00. Expected order totals are 10→20.00 and 20→0.00. Target totals are 10→40.00 and 20→0.00. Only order 10 differs; expected violation_count = 1. The raw JOIN produces four line/payment pairs for order 10.",
            "SUM(DISTINCT net_amount) would discard the second valid 10.00 line and return 10.00. An exploratory JOIN can be wrong even when Target is clean. Equal grand totals can also hide wrong totals for individual orders.",
            "Return one row and one non-negative integer column named violation_count. Count FULL JOIN rows with missing/unexpected order keys or a distinct sum of line amounts versus Target amount. Target order keys are unique in these fixtures, so a failing order contributes once. Payments help illustrate fanout but do not define the expected amount. Written answers are saved, not semantically graded.",
            "1. WITH expected AS (...) creates a CTE, a named intermediate query result. GROUP BY order_id reduces line rows to one row per order; SUM(net_amount) adds exact decimal line amounts, including repeated equal amounts and zero.\n2. FULL JOIN expected to target_order_totals USING(order_id) aligns the key and preserves orders missing from either side.\n3. A NULL key on one side indicates an absent row; IS DISTINCT FROM catches unequal amounts or a NULL actual amount.\n4. COUNT(*) counts failing joined order rows. No order_payments JOIN is needed in this reference reconciliation. The illustration returns 1.",
        ),
        "VIE": (
            "Kiểm tra tổng Target của mỗi order có bằng tổng các order_lines. Line là một mặt hàng trong order; payment là một giao dịch thanh toán. Grain của chúng khác grain một dòng tổng cho mỗi order.",
            "Một order có hai line và hai payment. Ghép mỗi line với mỗi payment tạo bốn dòng, lặp số tiền và làm tăng doanh thu: sự nhân dòng này gọi là JOIN fanout. Data QA tính tổng từ line độc lập với payment.",
            "order_lines: (order_id, line_id, net_amount) = (10, 1, 10.00), (10, 2, 10.00), (20, 1, 0.00). order_payments: order 10 có payment ID 1 và 2, mỗi payment 10.00; order 20 có payment ID 1, số tiền 0.00. Tổng kỳ vọng: 10→20.00, 20→0.00. Tổng Target: 10→40.00, 20→0.00. Chỉ order 10 khác; kết quả kỳ vọng violation_count = 1. JOIN trực tiếp tạo bốn cặp line/payment cho order 10.",
            "SUM(DISTINCT net_amount) bỏ line 10.00 hợp lệ thứ hai và trả 10.00. JOIN dùng để khám phá có thể sai dù Target sạch. Tổng chung bằng nhau cũng có thể che tổng từng order sai.",
            "Trả một dòng, một cột số nguyên không âm tên violation_count. Đếm dòng FULL JOIN có key order thiếu/thừa hoặc tổng amount của line khác amount Target. Fixtures đảm bảo key order Target duy nhất nên mỗi order vi phạm tính một lần. Payment minh họa fanout, không xác định số tiền kỳ vọng. Câu trả lời được lưu, không được chấm theo ý nghĩa.",
            "1. WITH expected AS (...) tạo CTE, tức kết quả truy vấn trung gian có tên. GROUP BY order_id gom line thành một dòng mỗi order; SUM(net_amount) cộng decimal chính xác, kể cả hai line cùng số tiền và số 0.\n2. FULL JOIN expected với target_order_totals USING(order_id) ghép key và giữ order thiếu ở một trong hai phía.\n3. Key NULL ở một phía biểu thị dòng không có; IS DISTINCT FROM bắt amount khác hoặc actual NULL.\n4. COUNT(*) đếm dòng order ghép bị vi phạm. Đối soát tham chiếu không cần JOIN order_payments. Ví dụ trả 1.",
        ),
    },
    "lab_008_latest_version": {
        "ENG": (
            "Check that target_current_orders keeps the correct latest event for each order_id. An event is a recorded version. Latest means highest updated_at, then highest event_id when times tie; it does not mean highest amount.",
            "Two corrections reach an order at the same timestamp. A time-only rule can choose different results between runs. Data QA checks the explicit tie-breaker so the current report is reproducible.",
            "Source events (event_id, order_id, updated_at UTC, net_amount): (1, 10, 2026-01-01 12:00, 10.00), (2, 10, 2026-01-02 12:00, 12.00), (3, 10, 2026-01-02 12:00, 11.00), (4, 20, 2026-01-01 12:00, 0.00). Winners are event 3 for order 10 and event 4 for order 20. Target holds event 2/12.00 for order 10 and correct event 4 for order 20. Expected violation_count = 1; event 3 wins despite its smaller amount.",
            "MAX(updated_at) followed by a JOIN can return both tied events. ROW_NUMBER ordered only by time leaves the tie unresolved. Comparing only amounts can miss the wrong event identifier or timestamp.",
            "Return one row and one non-negative integer column named violation_count. Compare the winning Source row per order with Target; count joined rows with missing/unexpected keys or different event_id, updated_at or net_amount. Several wrong fields on the same joined row contribute 1. Fixtures use unique Target keys. Your written answer is saved, not semantically graded.",
            "1. WITH ranked names the version-ranking result. PARTITION BY order_id starts a separate ranking for each order.\n2. ROW_NUMBER assigns 1 to the first row under updated_at DESC,event_id DESC: DESC places greater values first and event_id resolves equal times.\n3. WHERE rn=1 keeps one winner. FULL JOIN to Target retains missing/unexpected keys.\n4. IS DISTINCT FROM compares event ID, time and amount safely with NULL. OR combines those failure reasons, and COUNT(*) counts each failing joined row once. The illustration returns 1.",
        ),
        "VIE": (
            "Kiểm tra target_current_orders giữ đúng event mới nhất cho mỗi order_id. Event là một phiên bản được ghi nhận. Mới nhất nghĩa là updated_at lớn nhất, rồi event_id lớn nhất khi thời gian bằng nhau; không phải amount lớn nhất.",
            "Hai bản sửa cùng một order có chung timestamp. Chỉ xét thời gian có thể cho kết quả khác nhau giữa các lần chạy. Data QA kiểm tra quy tắc phá hòa rõ ràng để báo cáo hiện tại có thể tái lập.",
            "Event Source (event_id, order_id, updated_at UTC, net_amount): (1, 10, 2026-01-01 12:00, 10.00), (2, 10, 2026-01-02 12:00, 12.00), (3, 10, 2026-01-02 12:00, 11.00), (4, 20, 2026-01-01 12:00, 0.00). Event thắng là 3 cho order 10 và 4 cho order 20. Target giữ event 2/12.00 cho order 10 và event 4 đúng cho order 20. Kết quả kỳ vọng violation_count = 1; event 3 thắng dù amount nhỏ hơn.",
            "MAX(updated_at) rồi JOIN có thể trả cả hai event cùng thời gian. ROW_NUMBER chỉ sắp theo thời gian chưa giải quyết hòa. Chỉ so amount có thể bỏ sót event ID hoặc timestamp sai.",
            "Trả một dòng, một cột số nguyên không âm tên violation_count. So dòng Source thắng của từng order với Target; đếm dòng ghép thiếu/thừa key hoặc khác event_id, updated_at, net_amount. Nhiều trường sai trong cùng dòng ghép đóng góp 1. Fixtures có key Target duy nhất. Câu trả lời được lưu, không được chấm theo ý nghĩa.",
            "1. WITH ranked đặt tên kết quả xếp hạng phiên bản. PARTITION BY order_id xếp hạng riêng cho từng order.\n2. ROW_NUMBER gán 1 cho dòng đứng đầu theo updated_at DESC,event_id DESC: DESC đưa giá trị lớn lên trước; event_id phá hòa khi thời gian bằng nhau.\n3. WHERE rn=1 giữ một dòng thắng. FULL JOIN với Target giữ cả key thiếu/thừa.\n4. IS DISTINCT FROM so event ID, thời gian và số tiền an toàn với NULL. OR kết hợp các lý do sai; COUNT(*) đếm mỗi dòng ghép vi phạm một lần. Ví dụ trả 1.",
        ),
    },
    "lab_009_utc_dates": {
        "ENG": (
            "Check daily order counts and exact revenue using UTC calendar dates. A timestamp is an instant; its displayed date depends on a timezone. UTC is the timezone fixed by this report's contract.",
            "A report groups late-night orders by the operator's local date instead of UTC. The grand revenue stays the same, but yesterday's dashboard moves sales to today. Data QA checks each day, including midnight and year-end.",
            "Three source_time_orders (order_id, ordered_at UTC, net_amount): (10, 2026-01-01 23:30, 10.01), (20, 2026-01-02 00:00, 0.00), (30, 2026-01-02 00:30, 7.00). Expected daily rows: 2026-01-01→(1,10.01), 2026-01-02→(2,7.00). Target incorrectly puts all three on 2026-01-02→(3,17.01). Jan 1 is missing and Jan 2 has wrong totals; expected violation_count = 2, not 3 bad orders.",
            "Casting ordered_at directly to date uses the connection timezone. In UTC+07, 23:30 UTC displays on the next date. A row exactly at 00:00 UTC belongs to the new day; a zero amount still contributes one order.",
            "Return one row and one non-negative integer column named violation_count. Count FULL JOIN daily rows with a missing/unexpected UTC date or distinct order_count/net_revenue. Count a day once even when both totals differ. COUNT measures orders per day; SUM measures exact revenue. Written answers are saved, not semantically graded.",
            "1. The expected CTE applies ordered_at AT TIME ZONE 'UTC' before ::date. The timezone is explicit rather than inherited from the connection.\n2. GROUP BY that date creates one row per UTC day. COUNT(*) counts orders and SUM(net_amount) adds exact decimal amounts.\n3. FULL JOIN by order_date preserves absent or unexpected days.\n4. Missing-side keys or IS DISTINCT FROM comparisons flag the joined daily row. COUNT(*) counts failing days once. In the example it counts the absent Jan 1 row and the incorrect Jan 2 row: 2.",
        ),
        "VIE": (
            "Kiểm tra số order và doanh thu chính xác theo ngày UTC. Timestamp là một thời điểm; ngày hiển thị phụ thuộc múi giờ. UTC là múi giờ được contract của báo cáo này quy định.",
            "Báo cáo gom order ban đêm theo ngày local của người vận hành thay vì UTC. Tổng doanh thu không đổi nhưng dashboard chuyển doanh số hôm qua sang hôm nay. Data QA kiểm tra từng ngày, kể cả nửa đêm và cuối năm.",
            "Ba dòng source_time_orders (order_id, ordered_at UTC, net_amount): (10, 2026-01-01 23:30, 10.01), (20, 2026-01-02 00:00, 0.00), (30, 2026-01-02 00:30, 7.00). Dòng ngày kỳ vọng: 2026-01-01→(1,10.01), 2026-01-02→(2,7.00). Target gom sai cả ba vào 2026-01-02→(3,17.01). Jan 1 bị thiếu và Jan 2 sai tổng; kết quả kỳ vọng violation_count = 2, không phải 3 order lỗi.",
            "Đổi trực tiếp ordered_at sang date sẽ dùng múi giờ connection. Ở UTC+07, 23:30 UTC hiển thị sang ngày tiếp theo. Dòng đúng 00:00 UTC thuộc ngày mới; amount bằng 0 vẫn được tính là một order.",
            "Trả một dòng, một cột số nguyên không âm tên violation_count. Đếm dòng FULL JOIN ngày có ngày UTC thiếu/thừa hoặc order_count/net_revenue khác. Một ngày tính một lần dù cả hai tổng sai. COUNT đo order mỗi ngày; SUM đo doanh thu chính xác. Câu trả lời được lưu, không được chấm theo ý nghĩa.",
            "1. CTE expected dùng ordered_at AT TIME ZONE 'UTC' trước ::date. Múi giờ được chỉ rõ thay vì lấy từ connection.\n2. GROUP BY ngày đó tạo một dòng mỗi ngày UTC. COUNT(*) đếm order; SUM(net_amount) cộng decimal chính xác.\n3. FULL JOIN bằng order_date giữ cả ngày thiếu hoặc thừa.\n4. Key thiếu ở một phía hoặc so IS DISTINCT FROM đánh dấu dòng ngày vi phạm. COUNT(*) đếm mỗi ngày sai một lần. Ví dụ đếm Jan 1 thiếu và Jan 2 sai: 2.",
        ),
    },
    "lab_010_incremental": {
        "ENG": (
            "Check the current Target against all events that have arrived by lab_context.as_of. Incremental loading handles batches of changes; replay processes a batch again. The correct current version uses greatest (event_at,event_id), not last arrival. Late arrival means an old business event reaches the loader later.",
            "A batch retry must not publish the same order twice. An event-time watermark (a saved cutoff used to skip older events) can also discard an old event for a previously unseen order. Data QA reconciles the observable current snapshot after each batch/replay using the fixed evaluation clock.",
            "All times UTC; as_of = 2026-01-04 12:00. Three incremental_events: event 1/order 10/event_at Jan 1 12:00/arrived_at Jan 2 12:00/amount 10.00; event 2/order 10/event_at Jan 3 12:00/arrived_at Jan 3 12:00/amount 12.00; event 3/order 20/event_at Jan 1 12:00/arrived_at Jan 4 12:00/amount 7.00. Expected winners: event 2 and event 3. Target has two identical copies of event 2 and no order 20. Missing-match rows = 1, incorrect matched rows = 0, duplicate key groups = 1. Expected violation_count = 2.",
            "Filtering only by event_at can miss the late new key. Appending on replay duplicates rows. The score is not always one per order: two incorrect duplicate rows can contribute two mismatches plus one duplicate-group violation.",
            "Return one row and one non-negative integer column named violation_count: count failing FULL JOIN rows against winners among arrived_at <= as_of events, plus duplicated order_id groups in incremental_target. Compare event_id,event_at,net_amount. An event arriving exactly at as_of is included; a later arrival is excluded. A clean replay keeps the same winners and Target rows. The saved written answer is not semantically graded.",
            "1. CROSS JOIN lab_context supplies its single evaluation clock to each event. WHERE arrived_at <= as_of selects evidence already received, including the boundary; it does not filter by event_at.\n2. ROW_NUMBER partitions by order_id and orders event_at DESC,event_id DESC. expected keeps rn=1, so stale late updates cannot replace newer versions.\n3. mismatches FULL JOINs winners to Target and compares keys/event ID/business time/amount using IS DISTINCT FROM. Each failing joined row counts; several wrong fields still count once.\n4. duplicates uses GROUP BY order_id and HAVING COUNT(*)>1 to count repeated key groups independently.\n5. Add mismatch rows and duplicate groups as violation_count. The example's correct duplicate copies fail only the duplicate rule, and the missing late order fails reconciliation: 1+1=2. This snapshot check does not itself prove every past simulator step.",
        ),
        "VIE": (
            "Kiểm tra Target hiện tại với mọi event đã đến trước hoặc đúng lab_context.as_of. Load incremental xử lý các batch thay đổi; replay là xử lý lại một batch. Phiên bản đúng dùng bộ (event_at,event_id) lớn nhất, không lấy dòng đến cuối. Late arrival nghĩa là event nghiệp vụ cũ đến loader muộn hơn.",
            "Chạy lại batch không được công bố cùng order hai lần. Watermark theo thời gian event (mốc đã xử lý dùng để bỏ qua event cũ hơn) cũng có thể loại event cũ của một order chưa từng xuất hiện. Data QA đối soát snapshot hiện tại sau mỗi batch/replay với đồng hồ đánh giá cố định.",
            "Mọi thời gian là UTC; as_of = 2026-01-04 12:00. Ba incremental_events: event 1/order 10/event_at Jan 1 12:00/arrived_at Jan 2 12:00/amount 10.00; event 2/order 10/event_at Jan 3 12:00/arrived_at Jan 3 12:00/amount 12.00; event 3/order 20/event_at Jan 1 12:00/arrived_at Jan 4 12:00/amount 7.00. Dòng thắng là event 2 và 3. Target có hai bản sao giống nhau của event 2, không có order 20. Dòng thiếu khi đối soát = 1, dòng đã ghép nhưng sai = 0, nhóm key trùng = 1. Kết quả kỳ vọng violation_count = 2.",
            "Chỉ lọc theo event_at có thể bỏ sót key mới đến muộn. Append khi replay tạo dòng trùng. Điểm không luôn là một cho mỗi order: hai dòng trùng sai có thể đóng góp hai dòng đối soát sai cộng một nhóm trùng.",
            "Trả một dòng, một cột số nguyên không âm tên violation_count: số dòng FULL JOIN vi phạm so với dòng thắng trong các event arrived_at <= as_of, cộng số nhóm order_id trùng trong incremental_target. So event_id,event_at,net_amount. Event đến đúng as_of được tính; đến sau thì chưa tính. Replay sạch giữ nguyên dòng thắng và Target. Câu trả lời được lưu, không được chấm theo ý nghĩa.",
            "1. CROSS JOIN lab_context gắn đồng hồ đánh giá duy nhất với mỗi event. WHERE arrived_at <= as_of chọn dữ liệu đã nhận, kể cả đúng mốc; không lọc theo event_at.\n2. ROW_NUMBER chia theo order_id, sắp event_at DESC,event_id DESC. expected giữ rn=1 nên update cũ đến muộn không thay phiên bản mới.\n3. mismatches FULL JOIN dòng thắng với Target và so key/event ID/thời gian nghiệp vụ/amount bằng IS DISTINCT FROM. Mỗi dòng ghép sai tính một lần dù nhiều trường sai.\n4. duplicates dùng GROUP BY order_id, HAVING COUNT(*)>1 để đếm riêng nhóm key lặp.\n5. Cộng dòng đối soát sai và nhóm trùng thành violation_count. Hai bản sao đúng trong ví dụ chỉ vi phạm tính duy nhất; order muộn bị mất vi phạm đối soát: 1+1=2. Kiểm tra snapshot này chưa tự chứng minh mọi step trước đó của simulator.",
        ),
    },
    "lab_011_freshness": {
        "ENG": (
            "Check required datasets are present, successful and recent enough at a fixed as_of time. Freshness measures data age. An SLA is the maximum age allowed for each dataset; last_success_at measures load recency and last_event_at measures business-data recency.",
            "A dashboard refresh job succeeds today but republishes yesterday's events. Its execution succeeded while its data is stale. Data QA checks both clocks and explicitly notices missing observations.",
            "as_of = 2026-01-04 12:00 UTC. Three requirements: orders SLA 5 minutes, payments SLA 15, customers SLA 60. Observations: orders SUCCESS, last_success_at=11:55 and last_event_at=11:55; payments SUCCESS, last_success_at=11:59 and last_event_at=11:44; customers has no observation. Orders is exactly at its allowed boundary; payments has 16-minute-old events; customers is missing. Expected violation_count = 2.",
            "Checking only SUCCESS misses stale events. Using NOW() makes a fixed-clock exercise change over time. Age equal to the SLA is allowed; age greater than the SLA fails. A future timestamp is invalid, not evidence of extra freshness.",
            "Return one row and one non-negative integer column named violation_count. Count failing requirement/observation joined rows: missing observation, non-SUCCESS or NULL status, missing timestamps, future timestamps or either age strictly greater than sla_minutes. Several reasons on one row still count 1. Fixtures have one observation per dataset; observations for unrequired datasets are outside this LEFT JOIN check. Written answers are saved, not semantically graded; SQL execution errors remain ERROR.",
            "1. FROM freshness_requirements r LEFT JOIN freshness_observations o USING(dataset_id) keeps every required dataset, even one with no observation.\n2. Missing keys, execution_status IS DISTINCT FROM 'SUCCESS' and IS NULL timestamps detect unavailable or invalid evidence.\n3. Each timestamp greater than as_of fails. Subtracting the timestamp from as_of gives an interval; sla_minutes * INTERVAL '1 minute' creates the permitted age. The strict > comparison allows the exact SLA boundary.\n4. OR combines failure reasons and COUNT(*) counts selected joined rows once. The illustration returns 2, while orders at exactly 5 minutes passes.",
        ),
        "VIE": (
            "Kiểm tra dataset bắt buộc có dữ liệu quan sát, thực thi thành công và đủ mới tại mốc as_of cố định. Freshness đo tuổi dữ liệu. SLA là tuổi tối đa cho từng dataset; last_success_at đo lần load thành công gần nhất, last_event_at đo độ mới của event nghiệp vụ.",
            "Job refresh dashboard thành công hôm nay nhưng lại công bố event hôm qua. Thực thi thành công trong khi dữ liệu đã cũ. Data QA kiểm tra cả hai đồng hồ và nhận ra khi thiếu thông tin quan sát.",
            "as_of = 2026-01-04 12:00 UTC. Ba yêu cầu: orders SLA 5 phút, payments SLA 15, customers SLA 60. Quan sát: orders SUCCESS, last_success_at=11:55 và last_event_at=11:55; payments SUCCESS, last_success_at=11:59 và last_event_at=11:44; customers không có dòng quan sát. Orders đúng ranh giới cho phép; event payments đã 16 phút; customers bị thiếu. Kết quả kỳ vọng violation_count = 2.",
            "Chỉ kiểm tra SUCCESS sẽ bỏ sót event cũ. Dùng NOW() khiến bài có đồng hồ cố định đổi kết quả theo thời gian. Tuổi bằng SLA được chấp nhận; lớn hơn SLA thì sai. Timestamp tương lai không có nghĩa dữ liệu đặc biệt mới.",
            "Trả một dòng, một cột số nguyên không âm tên violation_count. Đếm dòng ghép yêu cầu/quan sát vi phạm: thiếu quan sát, trạng thái không phải SUCCESS hoặc NULL, thiếu timestamp, timestamp tương lai, hoặc một trong hai tuổi lớn hơn sla_minutes. Nhiều lý do trong cùng dòng vẫn tính 1. Fixtures có một quan sát mỗi dataset; quan sát của dataset không được yêu cầu nằm ngoài LEFT JOIN này. Câu trả lời được lưu, không được chấm theo ý nghĩa; lỗi thực thi SQL vẫn là ERROR.",
            "1. FROM freshness_requirements r LEFT JOIN freshness_observations o USING(dataset_id) giữ mọi dataset bắt buộc, kể cả khi không có quan sát.\n2. Key thiếu, execution_status IS DISTINCT FROM 'SUCCESS' và timestamp IS NULL phát hiện bằng chứng thiếu hoặc không hợp lệ.\n3. Timestamp lớn hơn as_of là sai. Lấy as_of trừ timestamp cho khoảng thời gian; sla_minutes * INTERVAL '1 minute' tạo tuổi tối đa. So sánh nghiêm ngặt > chấp nhận đúng ranh giới SLA.\n4. OR kết hợp các lý do sai; COUNT(*) đếm mỗi dòng ghép vi phạm một lần. Ví dụ trả 2, còn orders đúng 5 phút thì đạt.",
        ),
    },
    "lab_012_scd_type1": {
        "ENG": (
            "Check one current customer row against the latest Source change. A dimension stores descriptive attributes such as tier. Slowly Changing Dimension (SCD) Type 1 keeps the current value, overwriting old attributes instead of retaining every historical version.",
            "A customer upgrades from BRONZE to GOLD, but the report still uses the old tier. Another correction shares the same effective time. Data QA checks the latest business change and its event_id tie-breaker, not just valid-looking tier text.",
            "Three Source changes (event_id, customer_id, effective_at UTC, tier): (1, 10, 2026-01-01 00:00, BRONZE), (2, 10, 2026-01-02 00:00, GOLD), (3, 20, 2026-01-01 00:00, SILVER). Target customer 10 still has event 1/BRONZE/Jan 1; customer 20 correctly has event 3/SILVER/Jan 1. Customer 10's three compared fields differ, but expected violation_count = 1.",
            "Keeping every historical row in a Type 1 current table uses the wrong grain. A correct row count or an allowed tier value does not prove freshness. Time ties require event_id; MAX(tier) is not a version rule.",
            "Return one row and one non-negative integer column named violation_count. Count FULL JOIN rows with missing/unexpected customer keys or distinct tier,effective_at,event_id against the latest change ordered by effective_at DESC,event_id DESC. Several changed fields on one matched customer contribute once; fixtures have unique current Target keys. Written answers are saved, not semantically graded.",
            "1. ranked uses ROW_NUMBER with PARTITION BY customer_id, so each customer has its own ranking.\n2. ORDER BY effective_at DESC,event_id DESC selects the latest business-effective change, resolving simultaneous corrections with the greater event_id.\n3. rn=1 keeps the current expectation. FULL JOIN by customer_id also retains missing/unexpected customers.\n4. IS DISTINCT FROM compares tier, effective time and event ID safely with NULL; OR and COUNT(*) count each failing joined row once. The example's stale customer contributes 1, not 3. This checks current state; historical analysis belongs to Type 2.",
        ),
        "VIE": (
            "Kiểm tra một dòng customer hiện tại với thay đổi Source mới nhất. Dimension lưu thuộc tính mô tả như tier. Slowly Changing Dimension (SCD) Type 1 giữ giá trị hiện tại, ghi đè thuộc tính cũ thay vì giữ mọi phiên bản lịch sử.",
            "Khách hàng nâng từ BRONZE lên GOLD nhưng báo cáo vẫn dùng tier cũ. Một bản sửa khác có cùng thời gian hiệu lực. Data QA kiểm tra thay đổi nghiệp vụ mới nhất và quy tắc phá hòa bằng event_id, không chỉ nhìn tier có vẻ hợp lệ.",
            "Ba thay đổi Source (event_id, customer_id, effective_at UTC, tier): (1, 10, 2026-01-01 00:00, BRONZE), (2, 10, 2026-01-02 00:00, GOLD), (3, 20, 2026-01-01 00:00, SILVER). Target customer 10 vẫn giữ event 1/BRONZE/Jan 1; customer 20 giữ đúng event 3/SILVER/Jan 1. Ba trường so sánh của customer 10 đều khác nhưng kết quả kỳ vọng violation_count = 1.",
            "Giữ mọi dòng lịch sử trong bảng current Type 1 là sai grain. Số dòng đúng hoặc tier hợp lệ chưa chứng minh cập nhật đúng. Khi thời gian bằng nhau cần event_id; MAX(tier) không phải quy tắc chọn phiên bản.",
            "Trả một dòng, một cột số nguyên không âm tên violation_count. Đếm dòng FULL JOIN thiếu/thừa key customer hoặc khác tier,effective_at,event_id so với thay đổi mới nhất theo effective_at DESC,event_id DESC. Nhiều trường sai của cùng customer ghép được tính một lần; fixtures có key Target current duy nhất. Câu trả lời được lưu, không được chấm theo ý nghĩa.",
            "1. ranked dùng ROW_NUMBER với PARTITION BY customer_id để xếp hạng riêng từng khách hàng.\n2. ORDER BY effective_at DESC,event_id DESC chọn thay đổi có hiệu lực nghiệp vụ mới nhất; event_id lớn hơn giải quyết bản sửa đồng thời.\n3. rn=1 giữ kỳ vọng hiện tại. FULL JOIN bằng customer_id giữ cả khách hàng thiếu/thừa.\n4. IS DISTINCT FROM so tier, thời gian hiệu lực và event ID an toàn với NULL; OR và COUNT(*) đếm mỗi dòng ghép sai một lần. Customer cũ trong ví dụ đóng góp 1, không phải 3. Bài kiểm tra trạng thái hiện tại; phân tích lịch sử thuộc Type 2.",
        ),
    },
    "lab_013_scd_type2": {
        "ENG": (
            "Check customer attribute history against Source changes and validity rules. SCD Type 2 keeps multiple versions. A half-open interval [valid_from,valid_to) includes its start but excludes its end. NULL valid_to represents an open-ended final version.",
            "Finance asks which tier a customer had when an order occurred. Overlapping history can assign two tiers to one instant; a missing version can assign none. Data QA checks history content, interval boundaries and current flags together.",
            "Three Source changes, all UTC: event 1/customer 10/2026-01-01 00:00/BRONZE; event 2/customer 10/2026-01-02 00:00/GOLD; event 3/customer 20/2026-01-01 00:00/BRONZE. Target has three versions: customer 10 BRONZE [Jan 1,Jan 2), is_current=false; customer 10 GOLD [Jan 2,NULL), true; customer 20 BRONZE [Jan 1,NULL), false. All ranges/tier values match; customer 20's flag is wrong. Counts: reference mismatches 1, overlaps 0, wrong current-count groups 1, nonpositive ranges 0, duplicate start groups 0. Expected violation_count = 2. Exactly Jan 2 belongs to customer 10's GOLD version; touching endpoints are not overlap.",
            "Using <= for overlap falsely flags adjacent intervals. A missing entire customer has no Target current-count group: its expected versions fail reconciliation instead. This diagnostic sum counts rule violations, not unique customers or unique defective versions.",
            "Return one row and one non-negative integer column named violation_count: sum the five components of the unchanged contract above. Match history by (customer_id,valid_from); count failing joined rows, distinct overlapping version pairs, Target customer groups with current count <>1, rows with valid_to<=valid_from, and duplicate (customer_id,valid_from) groups. NULL ends are allowed; same-time Source corrections keep highest event_id. Written answers are saved, not semantically graded.",
            "1. ranked partitions Source by customer_id,effective_at and orders event_id DESC. Keeping rn=1 resolves same-time corrections before building intervals, avoiding an artificial zero-length version.\n2. expected uses LEAD(effective_at), a window function that reads the next effective time for the same customer. It becomes valid_to; the last version has NULL and should be current.\n3. mismatches FULL JOINs expected and Target by customer_id,valid_from. It compares tier,end,current flag with IS DISTINCT FROM and preserves missing/unexpected versions. Several wrong fields still count one joined row.\n4. overlap_pairs self-JOINs Target, meaning the table is compared with itself. a.version_id<b.version_id counts a pair once. Both strict < interval conditions must hold; COALESCE replaces NULL ends with infinity. Adjacent endpoints therefore do not overlap.\n5. current_keys groups Target customers; COUNT(*) FILTER(WHERE is_current) counts only current rows and HAVING <>1 selects wrong groups. bad_ranges counts known ends <= starts; NULL ends do not satisfy this predicate. duplicates counts repeated customer/start groups, not excess rows.\n6. Add the five counts. The illustration returns 1+0+1+0+0=2 for one bad flag. Reference comparison also catches gaps or lost versions even if remaining intervals look valid.",
        ),
        "VIE": (
            "Kiểm tra lịch sử thuộc tính customer với thay đổi Source và quy tắc hiệu lực. SCD Type 2 giữ nhiều phiên bản. Khoảng nửa mở [valid_from,valid_to) bao gồm mốc đầu, không bao gồm mốc cuối. valid_to NULL biểu thị phiên bản cuối chưa có mốc kết thúc.",
            "Bộ phận tài chính muốn biết tier của khách hàng khi order phát sinh. Lịch sử chồng nhau có thể gán hai tier cho cùng thời điểm; mất phiên bản có thể không gán được tier nào. Data QA kiểm tra nội dung lịch sử, ranh giới và cờ current cùng nhau.",
            "Ba thay đổi Source, đều UTC: event 1/customer 10/2026-01-01 00:00/BRONZE; event 2/customer 10/2026-01-02 00:00/GOLD; event 3/customer 20/2026-01-01 00:00/BRONZE. Target có ba phiên bản: customer 10 BRONZE [Jan 1,Jan 2), is_current=false; customer 10 GOLD [Jan 2,NULL), true; customer 20 BRONZE [Jan 1,NULL), false. Khoảng và tier đều khớp; cờ của customer 20 sai. Số đếm: dòng đối soát sai 1, cặp chồng 0, nhóm sai số current 1, khoảng không dương 0, nhóm trùng mốc đầu 0. Kết quả kỳ vọng violation_count = 2. Đúng Jan 2 thuộc phiên bản GOLD của customer 10; chung mốc giữa hai khoảng không phải chồng.",
            "Dùng <= để kiểm tra chồng sẽ báo sai cho hai khoảng liền nhau. Customer mất hoàn toàn không có nhóm current-count trong Target: các phiên bản kỳ vọng của customer đó bị tính ở đối soát. Tổng chẩn đoán đếm vi phạm quy tắc, không đếm customer hay phiên bản lỗi duy nhất.",
            "Trả một dòng, một cột số nguyên không âm tên violation_count: cộng năm thành phần của contract giữ nguyên bên trên. Ghép lịch sử theo (customer_id,valid_from); đếm dòng ghép sai, cặp phiên bản chồng khác nhau, nhóm customer Target có số current <>1, dòng valid_to<=valid_from và nhóm (customer_id,valid_from) trùng. Mốc cuối NULL được phép; bản sửa Source cùng thời gian giữ event_id lớn nhất. Câu trả lời được lưu, không được chấm theo ý nghĩa.",
            "1. ranked chia Source theo customer_id,effective_at, sắp event_id DESC. Giữ rn=1 giải quyết bản sửa cùng thời gian trước khi dựng khoảng, tránh tạo phiên bản dài bằng 0 giả tạo.\n2. expected dùng LEAD(effective_at), hàm cửa sổ đọc thời gian hiệu lực tiếp theo của cùng customer. Đó là valid_to; phiên bản cuối có NULL và cần là current.\n3. mismatches FULL JOIN kỳ vọng với Target bằng customer_id,valid_from; so tier,mốc cuối,cờ current bằng IS DISTINCT FROM và giữ phiên bản thiếu/thừa. Nhiều trường sai vẫn tính một dòng ghép.\n4. overlap_pairs tự JOIN Target, tức so bảng với chính nó. a.version_id<b.version_id tính mỗi cặp một lần. Hai điều kiện khoảng với < phải cùng đúng; COALESCE thay mốc cuối NULL bằng vô hạn. Hai khoảng liền nhau vì vậy không chồng.\n5. current_keys nhóm customer Target; COUNT(*) FILTER(WHERE is_current) chỉ đếm dòng current, HAVING <>1 chọn nhóm sai. bad_ranges đếm mốc cuối đã biết <= mốc đầu; NULL không thỏa điều kiện này. duplicates đếm nhóm customer/mốc đầu lặp, không đếm dòng dư.\n6. Cộng năm số đếm. Ví dụ trả 1+0+1+0+0=2 cho một cờ sai. Đối soát Source còn bắt khoảng hở hoặc phiên bản mất dù các khoảng còn lại trông hợp lệ.",
        ),
    },
})


def apply_guidance(catalog):
    for lab_id, translations in GUIDANCE.items():
        for language, (checking, purpose, example, mistake, challenge, solution) in translations.items():
            text = catalog[lab_id][language]
            text["theory"] = sections(language, ((0, checking), (1, purpose), (2, example), (3, mistake)))
            text["requirement"] += "\n\n" + sections(language, ((4, challenge),))
            text["explanation"] = sections(language, ((5, solution),))
